### PR TITLE
[WIP] Tree hash update - added padding

### PR DESCRIPTION
**Pull request by mjkeating**
## Issue Addressed

Which issue # does this PR address?

#193 

Please list or describe the changes introduced by this PR.

Adds padding according to spec

### CODE REVIEW

**Comment by paulhauner** [comment]
Hi @mjkeating, very sorry for the inconvenience but could you please implement these changes here: https://github.com/sigp/lighthouse-common

If you'd like to see the rationale for this re-org, please see #197.

I promise we won't do this again for a while!

**Comment by paulhauner** [comment]
Sorry about the conflicts! Let me know if you need a hand to resolve :)

**Comment by paulhauner** [comment]
@mjkeating should I close this in favor of #236, please?

**Comment by mjkeating** [comment]
Yes, please close this PR in favor of #238

**Comment by AgeManning** [comment]
Closed in favour of #238

**Pull request closed without merging**
