### PR TITLE
[Merged by Bors] - Add metric for re-org distance

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Add a metric to track the re-org distance.

## Additional Info

NA

### CODE REVIEW

**Review by realbigsean — COMMENTED** [review]
Is there a reason for using a gauge over a histogram?

**Comment by michaelsproul** [comment]
I think a gauge is nicer because it's more precise. The default histogram buckets will ruin an integer value like the re-org distance. Related: if we want to set nicer histogram buckets we should merge https://github.com/sigp/lighthouse/pull/3391.

**Comment by realbigsean** [comment]
makes sense to me!

**Review by realbigsean — APPROVED** [review]

**Pull request closed without merging**
