### PR TITLE
[Merged by Bors] - Release v3.2.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump version to `v3.2.0`

## Additional Info

- ~~Blocked on #3597~~
- ~~Blocked on #3645~~
- ~~Blocked on #3653~~
- ~~Requires additional testing~~

### CODE REVIEW

**Comment by paulhauner** [comment]
I just rebased to include #3653.

**Comment by michaelsproul** [comment]
bors retry

**Comment by paulhauner** [comment]
It seems like the rate limiter is happy but now Windows tests are being dodgy. Third time's the charm :crossed_fingers: 

bors retry

**Pull request closed without merging**
