### PR TITLE
[Merged by Bors] - Split common crates out into their own repos

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Split out several crates which now exist in separate repos under `sigp`.

- [`ssz` and `ssz_derive`](https://github.com/sigp/ethereum_ssz)
- [`tree_hash` and `tree_hash_derive`](https://github.com/sigp/tree_hash)
- [`ethereum_hashing`](https://github.com/sigp/ethereum_hashing)
- [`ethereum_serde_utils`](https://github.com/sigp/ethereum_serde_utils)
- [`ssz_types`](https://github.com/sigp/ssz_types)

For the published crates see: https://crates.io/teams/github:sigp:crates-io?sort=recent-updates.

## Additional Info

- [x] Need to work out how to handle versioning. I was hoping to do 1.0 versions of several crates, but if they depend on `ethereum-types 0.x` that is not going to work. EDIT: decided to go with 0.5.x versions.
- [x] Need to port several changes from `tree-states`, `capella`, `eip4844` branches to the external repos.

### CODE REVIEW

**Comment by michaelsproul** [comment]
This is ready for review by a brave soul.

To verify the contents of the external repos, one could try copying the current crate contents from `unstable` to the right spot in each external repo, and then looking at the diff. The diff should show only renames, minor changes and no backdoors :wink:

**Comment by michaelsproul** [comment]
Will batch this actually

bors r-
bors r+

**Comment by michaelsproul** [comment]
Shit! Wrong PR

bors r-

**Comment by jimmygchen** [comment]
@michaelsproul I noticed some of these crates already have newer versions released (>0.5.0), is there any value in updating to latest? or are we not bumping because some of those changes are for `tree-states`/`eip4844`?

Minor one - the repo link for `ethereum_ssz_derive` on crates.io is incorrect, I think it should be updated to https://github.com/sigp/ethereum_ssz

https://crates.io/crates/ethereum_ssz_derive

**Comment by michaelsproul** [comment]
Thanks for reviewing Jimmy!

The semver-compatible patch updates are already applied in the `Cargo.lock`, e.g. here:

https://github.com/sigp/lighthouse/blob/4db6552b220179a262b073a84f8700f750a1d2e8/Cargo.lock#L2382-L2391

Generally changing the dependency spec (in `Cargo.toml`) is only necessary for _minor_ version changes, e.g. going from v0.5.x to v0.6.0. For other changes running `cargo update` will update the versions used in `Cargo.lock` without touching `Cargo.toml`. This tends to be a lot more convenient than editing the `Cargo.toml`.

Good catch on the `ethereum_ssz_derive` repo link! I've opened an issue to track it and we can get it next week: https://github.com/sigp/ethereum_ssz/issues/8

**Comment by jimmygchen** [comment]
Thanks for the explanation @michaelsproul ! I think this also explains my  next question re serde versions (they're now 1.0.0 instead of 1.0.xxx in some of the Cargo.toml).

Another one, in the `tree_hash` repo,  it uses the old `ethereum_ssz` 1.0.0-beta versions in dependencies, but it looks like you decided to not do 1.0, should we "update" to 0.5.0 to match Lighthouse? and is it worth removing the beta release from Github / crates just in case it might get confusing when we get to 1.0?
https://github.com/sigp/tree_hash/blob/v0.5.0/tree_hash/Cargo.toml#L21-L22

**Comment by michaelsproul** [comment]
> Another one, in the tree_hash repo, it uses the old ethereum_ssz 1.0.0-beta versions in dependencies, but it looks like you decided to not do 1.0, should we "update" to 0.5.0 to match Lighthouse?

Good catch yeah! It's not too impactful because they're dev-dependencies, so we're not pulling 1.0.0-beta into Lightouse (it would show in the Cargo.lock). I agree we should yank them and remove the releases to avoid confusion

**Review by jimmygchen — APPROVED** [review]
I've went through all the listed repos, looks good! Tests are passing too \o/
(one failing due to port conflicts - but that should be fixed with the PR that was merged last night)

**Comment by divagant-martian** [comment]
What would you think about importing the whole lighthouse history into the repos and removing the unrelated files? I'ts a bit sad to lose all the history of those crates. While this is merged it should also make way easier to migrate changes from lighthouse to the repos via a rebase

**Comment by divagant-martian** [comment]
Also, have you thought how to do some kind of continuous integrations testing? as in, making sure these crates remain compatible between individual releases?

**Comment by michaelsproul** [comment]
> What would you think about importing the whole lighthouse history into the repos and removing the unrelated files?

This is also something @paulhauner raised and I regret not doing this from the start. I didn't know about [`git filter-repo`](https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository) when I did the initial split. However, now that it's done I don't want to re-do it. My reasons for wanting to leave it as-is:

- History _is_ still available, it's just less accessible. We could link to the history from each repo to make bridging the gap easier, e.g.
  * [Commit history for `consensus/ssz`](https://github.com/sigp/lighthouse/commits/v4.0.1/consensus/ssz)
  * [Blame for `consensus/ssz/src/lib.rs`](https://github.com/sigp/lighthouse/blame/v4.0.1/consensus/ssz/src/lib.rs)
Using a tag name or commit in these links ensures they don't bitrot and can continue to be referred to.
- Contributor stats are hard to get right regardless of the approach we take. With the current approach the contributor stats for LH are still accurate, but the commits by me to create the external repos give me a bunch of extra green "additions". If we copied the whole lighthouse repo and then deleted stuff we'd be double-counting everyone's work on every external repo, and there'd be a huge red commit where someone (me?) deletes everything. The `filter-repo` approach would create external repos with the most accurate stats, but has other downsides (below).
- The `filter-repo` approach rewrites the history so that the commits on the external repo are no longer the _real_ commits from `sigp/lighthouse` with their larger context. This could make it moderately hard to track down why changes were made, because we'd need to refer back to the `sigp/lighthouse` repo anyway via pull-request numbers, etc.
- Duplicating the Lighthouse repo and then deleting the irrelevant bits would bloat the size of every external repo to the same size as Lighthouse. By my estimate (`du -sh .git`) this is around 240MB. This wouldn't impact the size of the crates on crates.io, but it would amount to 5x 250MB = 1.25GB of extra space for devs.
- We would need to rewrite the history for the external repos. We'd need to re-do the changes that have been made outside of `sigp/lighthouse` including renames, [adding CI](https://github.com/sigp/ssz_types/tree/910be255aa60a0d18dd9d7a1595363fd2ce174c4/.github/workflows), and changes that never made it to `unstable` like https://github.com/sigp/ssz_types/pull/3 and https://github.com/sigp/ssz_types/pull/6. Further, we'd need to decide whether to preserve the history of the current external repos, which were used to publish the current releases on crates.io. We _could_ delete the current repo history entirely by force-pushing, but this would really be a permanent loss. We'd probably have to archive the current repos and start from scratch with new ones.
- This PR has been a lot of work to get into a reviewable state, and I would like to be able to merge it soon without re-doing a bunch of work.

All in all, I'd prefer to just push ahead with the current approach and take these learnings on board for future crate extractions :tooth:

> While this is merged it should also make way easier to migrate changes from lighthouse to the repos via a rebase

AFAIK there aren't any outstanding changes on Lighthouse that aren't in the repos. If we merge soon, hopefully the propagation of this PR to 4844-land will be virtually conflict-free, and 4844 can just use the new versions of the crates as-is.

> Also, have you thought how to do some kind of continuous integrations testing? as in, making sure these crates remain compatible between individual releases?

Do you mean compatible with Lighthouse, or compatible with new compiler releases? I think compatibility with Lighthouse is adequately covered by the tests in Lighthouse itself, like the ones in [`consensus/types`](https://github.com/sigp/lighthouse/blob/a53830fd60a119bf3f659b253360af8027128e83/consensus/types/src/attestation.rs#L151). For compiler versions we could add some [scheduled actions](https://jasonet.co/posts/scheduled-actions/) that run on the external repos every 1/2/4 weeks and report any breakages?

**Review by paulhauner — APPROVED** [review]
I agree with @divagant-martian that it's sad to see the history go. I also see @michaelsproul's points about the baggage it contains. I also appreciate that, contrary to popular belief, Michael is a mortal human being and there are Git operations outside his knowledge. (Either that or his developers forgot to include `git --help` in his training data 🤖).

In terms of volume, I think I have the most to lose in the history. Some of my favorite bits of work are in those crates, however Git history isn't *actual* history and I can live with that! Anyway, the *true* history lives on in sigp/lighthouse!

That being said, my cup runneth over when it comes to Lighthouse attribution so it's totally valid for others to feel differently.

I think we can separate the issues at hand into two:

1. The need to split the crates into different repos.
1. How to balance full attribution against it's drawbacks.

I think we all agree that (1) is something we should do and this PR achieves (1) without making any decisions about (2) that aren't already made. Given that, I think we should merge this PR but consider the attribution topic still open (although I'm personally OK with attribution where it is now).

**Comment by paulhauner** [comment]
I'm happy to see a `ready-for-bors` flag on this once the conflict is resolved.

**Comment by michaelsproul** [comment]
I've fixed the merge conflicts and marked it ready for bors!

**Comment by michaelsproul** [comment]
bors r+

:open_mouth:

**Pull request closed without merging**
