### PR TITLE
Remove generic Id param from RequestId

### PR DESCRIPTION
**Pull request by jxs**
## Issue Addressed

In an effort to start cleaning unrequired generics from Lighthouse structures.
Reviewing by commit suggested. I had to move the `network` RequestId's to `lighthouse_networ` as `network` depends on `lighthouse_network`, feel free to suggest a better place than `api_types` for them.

### CODE REVIEW

**Review by ackintosh — APPROVED** [review]
Thanks @jxs, looks good to me!

**Review by dapplion — APPROVED** [review]

**Review by AgeManning — APPROVED** [review]
I'm down for simplifying things :)

**Comment by jimmygchen** [comment]
Marking this as ready since we've got triple ticks ✅

**Comment by jxs** [comment]
@mergifyio queue

**Pull request merged**
