### PR TITLE
[Merged by Bors] - Enable slasher broadcast by default

### PR DESCRIPTION
**Pull request by Gua00va**
## Issue Addressed

This PR addresses issue https://github.com/sigp/lighthouse/issues/4350

## Proposed Changes

This change will enable slasher broadcast in the following cases:
No flag is passed,
`--slasher-broadcast` is passed and,
`--slasher-broadcast=true` is passed.

Only when an explicit false value is passed the slasher does not broadcast.(`--slasher-broadcast=false`).

## Additional Info

TODO

- [x] Modify CLI parsing logic
- [x] Write test

Refer to #4353

### CODE REVIEW

**Comment by Gua00va** [comment]
I based on @michaelsproul lmdb-default branch. Hence, this is showing those changes too. #4360

**Comment by Gua00va** [comment]
This should work now as anvil as been fixed as of #4381

**Comment by michaelsproul** [comment]
@Gua00va looks like there's a small merge conflict, would you mind resolving it by merging in `unstable` (or rebasing)?

**Comment by Gua00va** [comment]
> @Gua00va looks like there's a small merge conflict, would you mind resolving it by merging in `unstable` (or rebasing)?

I have resolved the merge conflict.

**Review by michaelsproul — APPROVED** [review]
Perfect, thanks

**Comment by michaelsproul** [comment]
bors retry

**Comment by michaelsproul** [comment]
bors retry

🙏

**Pull request closed without merging**
