### PR TITLE
Make proposer duties work pre-genesis

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Quick PR for block explorers to be able to dump the Holesky genesis epoch validators prior to genesis.

## Additional Info

In further work we could/should:

- [ ] Do the same for attester duties
- [ ] Add some pre-genesis HTTP API tests

### CODE REVIEW

**Comment by michaelsproul** [comment]
Here's the Holesky genesis epoch proposer for reference:

```json
{
  "dependent_root": "0xab09edd9380f8451c3ff5c809821174a36dce606fea8b5ea35ea936915dbf889",
  "execution_optimistic": false,
  "data": [
    {
      "pubkey": "0xb7694a513894425211eec8babbca67a77c0f9aab22cda30d17107feba3009f116ae01777671d9f8d620fb8735b5b4b50",
      "validator_index": "209949",
      "slot": "0"
    },
    {
      "pubkey": "0xa74dd3f8a0249756f04c89d6c5935ec73e1cdbf9ef78911a110a2b6468c95591736e4ddf4bd5d36506698728068adfe5",
      "validator_index": "921241",
      "slot": "1"
    },
    {
      "pubkey": "0x9306835e5b34119524f491ec89e9de432f1131179f9d64854977ab3873d2a94f06519737b56dbc37320d01f2b04b8273",
      "validator_index": "746759",
      "slot": "2"
    },
    {
      "pubkey": "0xb5a4f0b00288033bacfa7a318894e481fbc4cfe79dce79898c5430f8e89251e2c64756921b8e1193d01199f144a5cfc0",
      "validator_index": "1407741",
      "slot": "3"
    },
    {
      "pubkey": "0xb06629d4e9cb58c0510a1fba8db52d8ee3537872c9ef896734f2903c83906013a86e229d4741e66cd8b88815bbb3ec41",
      "validator_index": "649475",
      "slot": "4"
    },
    {
      "pubkey": "0xa9346dbb2dc50c6c45291df89e1806aea1be1a48aa1cb2c07e68e8a05aaca86079736b0e5095b4a3e104e6edba20f6fd",
      "validator_index": "1260165",
      "slot": "5"
    },
    {
      "pubkey": "0x801e0695a610d68842a7287f9763ce126fd22c86f2205a31b553167cbff72c65fea90cc2e6c7c4807c134c3c2beca72a",
      "validator_index": "228247",
      "slot": "6"
    },
    {
      "pubkey": "0xaf2d7d20aee5057c6faca38f9e6b8fff456e2b75b2d5f5ec0091020231dce0d9b1eec70306da35438da89e8d14ec6814",
      "validator_index": "1048297",
      "slot": "7"
    },
    {
      "pubkey": "0x996dbcaf24e514e5d8ecac3536da0e49bb52d7ce5353dea29dde007662ca8cd3f087157dc9da5ea1bbc1ca66ef21d226",
      "validator_index": "1164944",
      "slot": "8"
    },
    {
      "pubkey": "0xac23e12e291c0fa231ed07040ac54c53f4a74c653554ac28a4b26dc610a3d40567e1fabd95525c90a53113d796789ff3",
      "validator_index": "1263827",
      "slot": "9"
    },
    {
      "pubkey": "0xac7142a07fd1a4544e085035153fd4524d682f9dd3c928b0b312b59f1b114dac661c348411b0414c63af544c799b9382",
      "validator_index": "1222963",
      "slot": "10"
    },
    {
      "pubkey": "0xa91b3353b40b6f56157d4cd614561339d0a782dd71e1b3a0a8f98285d904bbb6512e481d214cc0678ba5da09dc78746d",
      "validator_index": "288569",
      "slot": "11"
    },
    {
      "pubkey": "0xa86cbc4a54da398c4c83c2bd55a97be1b843fa43182d7bde5bfbfaef1f3302bd69351bff9d34dc97cad2d23196f0221c",
      "validator_index": "424627",
      "slot": "12"
    },
    {
      "pubkey": "0xa7290e39b3179487176e6766a66f0aa950e400075c17a4ed680e92b2e56f9b79c49671fe63c5832c1a903412a1a1ce85",
      "validator_index": "339437",
      "slot": "13"
    },
    {
      "pubkey": "0x841b7647bed60aa6860729ec42f07a18cac9d43d5fdb0748088521ec36399738282acac288e2574edd7c946eec1c7573",
      "validator_index": "637073",
      "slot": "14"
    },
    {
      "pubkey": "0xb8c97891242d6651590c4e89db5d268fe51056e3eb3a421d06f72885a89592310d4b663cd0abad82f1e178da7f657b26",
      "validator_index": "807545",
      "slot": "15"
    },
    {
      "pubkey": "0xb5f657c43731d347e208a86b6a6dc90e10da851d7f5ea9f08e29786e41168632d39fe42d60a4e1881287fbda9efeac1b",
      "validator_index": "24240",
      "slot": "16"
    },
    {
      "pubkey": "0xa187cd2a62d2eabd4840b6d6f891f638f42f8f89ac921294ea19a8c83de5102316f24b0b4f74a299f5f4a5a56825f1f3",
      "validator_index": "676653",
      "slot": "17"
    },
    {
      "pubkey": "0x8e1b416a29ebb66fb36d1c2b093a9dd621ce7a2fe7e872a7c3c9aa0a91b050e5aa2ab379068eed61496c6d0cadacf54a",
      "validator_index": "748673",
      "slot": "18"
    },
    {
      "pubkey": "0xadc148b2e35fcdafca1bfde7933c4bf61808d0d0ae2d9754b79089d95a4855e9130ac1ec8aa541b990d444dbc464a9a8",
      "validator_index": "1413484",
      "slot": "19"
    },
    {
      "pubkey": "0xa1fa9d93e33b26be6ca266db28cb6d49287bf16f66cbdf85288d0051cc9209da42d5973bd3e364032548ca0c4b05e949",
      "validator_index": "217532",
      "slot": "20"
    },
    {
      "pubkey": "0xb60073a219a3df42df6c5ab20cef9876d556ef9bddad574021da504a897935cc1c7ca3a1e7ee78fa6a1d41f20bf90943",
      "validator_index": "154682",
      "slot": "21"
    },
    {
      "pubkey": "0xb93a6cbf9ecd1e830ac8a05194130ea5d70d72a7d880c161a50db326e3fb5be0378d4b5090ca2a21fbafcef55745a237",
      "validator_index": "1137293",
      "slot": "22"
    },
    {
      "pubkey": "0x81113eb017e0975d26fa80497f86594d5d15bca38c4c274be268e9128cff4bdc3af7b9d11e265fb3a5bdec37ef7720ed",
      "validator_index": "314298",
      "slot": "23"
    },
    {
      "pubkey": "0xb73b971828eb6b518e15d2319e7e68b3d88e11d05c8cf563408bcbb50b3c8f106231c021f1eb72ec97d69295836b3f89",
      "validator_index": "543066",
      "slot": "24"
    },
    {
      "pubkey": "0x8f8ed745f71649446cbd261486b18d5c487a5a54e730daab593a43b926f1754afc9dec1ab32d8cb3b77cca88da684780",
      "validator_index": "527800",
      "slot": "25"
    },
    {
      "pubkey": "0x86eb0d27e2d298caa4039ea66b0b3390814de4fe4b6b3e70b1b2fbdcce5b0aa2f14ee1901b5dd05a36b68babb204d26c",
      "validator_index": "1336799",
      "slot": "26"
    },
    {
      "pubkey": "0xa0d2cb9269b170ddf8a2ea076a71b1b6099caa94e236e5db0332dec55abb83325b78f10f17414528597b6ffd8bade9c3",
      "validator_index": "25950",
      "slot": "27"
    },
    {
      "pubkey": "0x932efe5361d93f7e0ae19ff7e61a3128024315350b825774425a5b9ad65150e23c0d72b73b043e0ad4772007aae12d43",
      "validator_index": "630282",
      "slot": "28"
    },
    {
      "pubkey": "0xa3c54fe51db91d18cda758d4e81787c1be858cdc14a5f8100e5487782bcc70ef705a539a07df3b588fc3b8782fe333b2",
      "validator_index": "1208071",
      "slot": "29"
    },
    {
      "pubkey": "0x808ceffe3daf5ad02f0f1920118010dcca13c5d220f884d966ede55cc931edccb2f51a7fed117897bea22f37c5af411f",
      "validator_index": "613012",
      "slot": "30"
    },
    {
      "pubkey": "0xaa8a8bf8d1c97d5cfce270e0b2e8df2c632be350f3382314f7a45cee00be49dbb1c9c2e765e9e9d0c4eeb86f7f10d92b",
      "validator_index": "1393679",
      "slot": "31"
    }
  ]
}
```

Aside: I'd never noticed that we assign a non-zero proposer for slot 0. That's a bit weird but it makes sense given how the proposer is computed.

**Review by dapplion — APPROVED** [review]
This change looks good to me, doesn't seem risky. Should it really wait to have tests?

**Comment by michaelsproul** [comment]
Yeah let's just merge it

**Comment by michaelsproul** [comment]
@mergify queue

**Pull request merged**
