### PR TITLE
Add `bls_to_execution_change` topic to `eth1/v1/events`

### PR DESCRIPTION
**Pull request by chong-he**
Add `bls_to_execution_change` topic to the beacon API  `eth1/v1/events`

### CODE REVIEW

**Comment by michaelsproul** [comment]
We're going to discuss adding tests to this PR later today

**Comment by chong-he** [comment]
Adding `.deterministic_withdrawal_keypairs(VALIDATOR_COUNT)` works, thanks so much @michaelsproul

**Review by jimmygchen — APPROVED** [review]
Looks great! 👏

**Review by michaelsproul — APPROVED** [review]

**Comment by michaelsproul** [comment]
@mergifyio queue

**Pull request merged**
