### PR TITLE
Add minimal list validators

### PR DESCRIPTION
**Pull request by winksaville**
## Issue Addressed

There is no issue, I thought it was a nice to have.

## Proposed Changes

Added list_validator.rs based on import_validators.rs, this command
lists all of the validators present on the target node.

## Additional Info

Currently there are no tests,

### CODE REVIEW

**Comment by pahor167** [comment]
I also added this command (among others) in the following PR https://github.com/sigp/lighthouse/pull/5347 - please let me know if I should remove it from there

**Comment by winksaville** [comment]
> I also added this command (among others) in the following PR #5347 - please let me know if I should remove it from there

Whatever the powerful say is fine with me, this a decision that is above my pay grade, LoL!

**Comment by dapplion** [comment]
Thank you @winksaville for the contribution! This PR uses `get_lighthouse_validators` which is a lighthouse specific route. The `VC_URL_FLAG` description states `A HTTP(S) address of a validator client using the keymanager-API.` which contradicts the above. 

Given the existence of the keymanager API (see https://github.com/ethereum/keymanager-APIs) it is best to use its list endpoint. Speced here https://github.com/ethereum/keymanager-APIs/blob/a71e126e369a4ca762906f1d0884edcad70ee0ed/apis/local_keystores.yaml#L2)

EDIT: @pahor167 's PR uses the keymanager API to list keystores, see https://github.com/sigp/lighthouse/pull/5347/files#diff-748ad38a4d2e54eeef556475f65a7d67a53fb644e416d87d7f0c68202fba1468R77 maybe we can focus on that one as it's closer to the end goal :)

**Comment by winksaville** [comment]
> EDIT: @pahor167 's PR uses the keymanager API to list keystores, see https://github.com/sigp/lighthouse/pull/5347/files#diff-748ad38a4d2e54eeef556475f65a7d67a53fb644e416d87d7f0c68202fba1468R77 maybe we can focus on that one as it's closer to the end goal :)

SGTM, if @pahor is closer definitely use it.

**Comment by winksaville** [comment]
Closing in preference to #5347

**Pull request closed without merging**
