### PR TITLE
[Merged by Bors] - Add TTD and Bellatrix epoch for Prater

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Adds the TTD and Bellatrix values for Prater, as per https://github.com/eth-clients/eth2-networks/pull/77.

## Additional Info

- ~~Blocked on https://github.com/eth-clients/eth2-networks/pull/77~~

### CODE REVIEW

**Review by pawanjay176 — APPROVED** [review]

**Review by michaelsproul — APPROVED** [review]

**Comment by michaelsproul** [comment]
bors retry

**Comment by michaelsproul** [comment]
damnit Github CI, fix your C compiler!

bors retry

**Pull request closed without merging**
