### PR TITLE
Move sync active requests to own modules

### PR DESCRIPTION
**Pull request by dapplion**
## Issue Addressed

PeerDAS will add two more sync `ActiveRequest*`. Currently there are only two: `ActiveBlocksByRootRequest`, `ActiveBlobsByRootRequest` as spaghetti in the same file

## Proposed Changes

Move each `ActiveRequest*` to its own file to make space for upcoming PeerDAS PR with additional requests.

No change in logic or code, just copy pasted into new files

### CODE REVIEW

**Comment by dapplion** [comment]
Fixed conflicts 👍

**Review by AgeManning — APPROVED** [review]
lgtm

**Comment by jimmygchen** [comment]
@mergify queue

**Comment by jimmygchen** [comment]
@mergify dequeue

**Comment by jimmygchen** [comment]
@mergify queue

**Comment by jimmygchen** [comment]
@mergify requeue

**Comment by jimmygchen** [comment]
@mergify requeue

**Pull request merged**
