### PR TITLE
[Merged by Bors] - Add UPnP support for Lighthouse

### PR DESCRIPTION
**Pull request by darcys22**
Adding UPnP support will help grow the DHT by allowing NAT traversal for peers with UPnP supported routers.

## Issue Addressed

#927 

## Proposed Changes

Using IGD library: https://docs.rs/igd/0.10.0/igd/

Adding the  the libp2p tcp port and discovery udp port. If this fails it simply logs the attempt and moves on

### CODE REVIEW

**Review by AgeManning — CHANGES_REQUESTED** [review]
This is great! Thanks for the help!

I think it would be good to add a few more things in here. 

Firstly, I think we should set the lease times to 0 (infinity) and then delete the mappings when the client shuts down. The client shuts down [here](https://github.com/sigp/lighthouse/blob/master/beacon_node/network/src/service.rs#L195) so could remove the mappings there. 

I think this is a better approach, as a 60 second lease time could mean the router closes the mappings early. 

Secondly, I think we should add a CLI flag that allows the user to disable this. To see how do do this, we could mimic the behaviour of the --disable-discovery flag works: https://github.com/sigp/lighthouse/blob/master/beacon_node/src/cli.rs#L113
You just follow the logic here and in config.rs and create a new field on the network config. Then only run the upnp logic if this config is true. 

There are some failing tests now. I assume it has to do with timeouts waiting for the router's response. Having the config mentioned above, will allow us to disable the upnp mapping during the local network tests and we should then be able to pass those tests. 

Another test that is failiing is clippy. You need to update the suggestion that are given from the output of `cargo clippy`. 

Let me know what you think, this look great so far.

**Review by AgeManning — APPROVED** [review]
I hijacked this PR and completed it. 

This is my code, so naturally it LGTM.

**Comment by darcys22** [comment]
Thank you!

Apologies I had some other items come up and wasn't able to put the time into finishing this PR.

Awesome work by the Sigma Prime team

**Pull request closed without merging**
