### PR TITLE
Small typo in testing config

### PR DESCRIPTION
**Pull request by AgeManning**
Fixes an obvious typo, that is annoying if someone copy/pastes.

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]

**Comment by michaelsproul** [comment]
@mergifyio queue

**Comment by michaelsproul** [comment]
@mergifyio dequeue

**Comment by realbigsean** [comment]
@Mergifyio queue

**Comment by realbigsean** [comment]
@mergifyio refresh

**Comment by realbigsean** [comment]
@Mergifyio queue

**Comment by realbigsean** [comment]
@mergifyio requeue

**Comment by realbigsean** [comment]
@mergifyio queue

**Comment by realbigsean** [comment]
@mergifyio requeue

**Comment by jimmygchen** [comment]
@mergify requeue

**Comment by michaelsproul** [comment]
@mergifyio requeue

**Pull request merged**
