### PR TITLE
removed state-cache-size flag from beacon_node/src

### PR DESCRIPTION
**Pull request by thor314**
## Issue Addressed
#1115

## Proposed Changes

removed state-cache-size flag-related code from the results of:
`grep -R * -e 'state-cache-size'`
* beacon_node cli.rs
* beacon_node congig.rs
* Several (4) binary files contain the term, built the repo and:
Got a warning in `tests/ef_tests/src/cases/bls_sign_msg.rs:24:13`
Took 5 mins to build. Ran
`grep -R * -e 'state-cache-size'`
again and nothing comes up. 

## Note
I made a pull request 7 hours ago, but used the wrong email id for github, simplest soln appeared to be to  re-fork the repo with the right email id, so this is a duplicate of a pull I made earlier (and deleted).

### CODE REVIEW

**Comment by thor314** [comment]
Huh, missed those. Done.

**Comment by michaelsproul** [comment]
Nice, thanks!

The Makefile contains lots of targets for testing Lighthouse in slightly subtle configurations (with and without certain optimisations, and downloaded tests), so it's still appropriate to use `cargo build` sometimes (or even better: `cargo check`). The real arbiter of quality is the continuous integration (CI) testing that happens via GitHub actions, which we require to pass before merging.

For new contributors, enabling GitHub actions is a bit of a pain, you have to go into the Settings tab on your fork of the Lighthouse repo, go to `Actions > Enable` (either variety of "enable" should work AFAIK). I think the URL for you should be: https://github.com/thor314/lighthouse/settings/actions

On this occasion you should also merge `master` back into your feature branch, because `master` contains a fix that prevents CI from running for 4 hours. Something like:

```
git fetch origin
git merge origin/master
git push <your_fork> master
```

(assuming `origin` points to `sigp/lighthouse`)

**Comment by thor314** [comment]
Thanks for the explainer! Github actions are enabled. 
At risk of further betraying ignorance, I was under the impression that I should have my fork, `thor314/lighthouse` as `origin`, and `sigp/lighthouse` as upstream. `git remote -v` confirms this is the case:
```
origin	https://github.com/thor314/lighthouse (fetch)
origin	https://github.com/thor314/lighthouse (push)
upstream	https://github.com/sigp/lighthouse.git (fetch)
upstream	https://github.com/sigp/lighthouse.git (push)
```

With regards to the merging and pushing,
The results of (after having fetched and merged) is `% git push origin master`
is: `Everything up-to-date` 

I'm uncertain if I've done this correctly.

**Comment by michaelsproul** [comment]
Yeah, that's fine too, you'll just have to merge `upstream/master` instead, so:

```
git fetch upstream
git merge upstream/master
git push origin master
```

That should show up as a new (merge) commit in this PR, and also trigger CI

**Comment by michaelsproul** [comment]
I had to trigger CI manually, it didn't seem to run on your repo (Actions tab on your fork). Maybe double check the settings?

**Comment by thor314** [comment]
Screen Shot 2020-05-14 at 9 50 14 PM

**Pull request merged**
