### PR TITLE
Cargo update

### PR DESCRIPTION
**Pull request by AgeManning**
## Issue Addressed

Cargo update currently breaks something. Hoping for some help to fix. See CI

### CODE REVIEW

**Comment by jimmygchen** [comment]
`local-testnet` issues are kurtosis related, addressed in https://github.com/sigp/lighthouse/pull/6555
Looking into sim tests now

**Comment by jimmygchen** [comment]
Sim tests and local testnet tests are all passing now! 🎉

**Comment by michaelsproul** [comment]
Maybe we can do a targeted cargo update of the crates we need to update? Doing wholesale `cargo update` isn't necessary for v6.0.0, especially if it's slowing down node startup

**Comment by michaelsproul** [comment]
I've isolated the issue to the update of rust_eth_kzg. Opened this PR to pin it:

- https://github.com/sigp/lighthouse/pull/6608

**Pull request closed without merging**
