### PR TITLE
[Merged by Bors] - v3.1.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

- Bump versions

## Additional Info

- ~~Blocked on #3508~~
- ~~Blocked on #3526~~
- ~~Requires additional testing.~~
- Expected release date is 2022-09-01

### CODE REVIEW

**Comment by paulhauner** [comment]
Rebased onto `unstable`.

**Comment by michaelsproul** [comment]
Can you throw in a `cargo update` for `pest` and `plotters` so that we don't get any warnings about yanked packages while compiling? I think doing a full `cargo update` might be too drastic this late in the game, but the `pest` and `plotters` packages are non-critical (build system stuff).

```
cargo update -p plotters -p pest
```

**Review by AgeManning — APPROVED** [review]
lgtm

**Pull request closed without merging**
