### PR TITLE
[Merged by Bors] - Expose the startup timestamp to Prometheus

### LINKED ISSUE #1788: Metrics: Startup time
## Description

There is currently no way to tell the startup time of lighthouse components, except using OS features. Accessing this information on OS level rises security concerns.

## Present Behaviour

No metrics of startup time/up time present.

## Expected Behaviour

Publishing information about startup time on `process_start_time_seconds` like teku and prysm do.

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

Resolves #1788

## Proposed Changes

As per #1788, expose the time at which the process started via the `process_start_time_seconds` Prometheus metric. This will help users track uptime.

## Additional Info

NA

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
LGTM

**Review by pawanjay176 — APPROVED** [review]

**Comment by michaelsproul** [comment]
Chose the wrong bisection bors!

bors r-

**Comment by michaelsproul** [comment]
Will put this in the next merge batch, as it conflicted with #2239

**Pull request closed without merging**
