### PR TITLE
[Merged by Bors] - Fix typo in advanced networking docs

### PR DESCRIPTION
**Pull request by platschi**
## Proposed Changes

Fixing a typo in the advanced networking docs which mentions ``--target-peer`` instead of the correct ``--target-peers`` flag

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Great, thank you!

bors r+

**Comment by paulhauner** [comment]
Sorry @platschi, I think Github is having trouble figuring out that this branch actually targets unstable now :thinking: Do you mind pushing an [empty commit](https://riptutorial.com/git/example/4170/creating-an-empty-commit) to see if that fixes it? :pray:

**Comment by platschi** [comment]
> Sorry @platschi, I think Github is having trouble figuring out that this branch actually targets unstable now thinking Do you mind pushing an [empty commit](https://riptutorial.com/git/example/4170/creating-an-empty-commit) to see if that fixes it? pray

Sorry, my bad. Empty commit just pushed :rocket:

**Comment by paulhauner** [comment]
> Sorry, my bad.

No worries! Github is a bit awkward here, we can't specify a default branch for PRs (that's different to our "homepage" default) *and* it can't detect properly when the branch is changed.

Thanks again for the typo fix!

bors r+

**Pull request closed without merging**
