### PR TITLE
Fix for issue 4860 - Added in process_justification_and_finalization

### PR DESCRIPTION
**Pull request by zack-scott**
## Issue Addressed
This PR addresses the issue of compute_attestation_rewards_altair not taking into account the justified epochs attestation rewards when coming out of an inactivity leak.

Which issue # does this PR address?
#4860 

## Proposed Changes
Added in process_justification_and_finalization to the compute_attestation_rewards_altair function as suggested in issue.

Please list or describe the changes introduced by this PR.
The changes allow for calculation of attestation rewards when coming out of an inactivity leak.

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

### CODE REVIEW

**Comment by zack-scott** [comment]
@jimmygchen hey, I added in the logic `process_justification_and_finalization` for the `compute_attestation_rewards_altair` function, but I wasn't sure if we also needed to add in the `process_justification_and_finalization` to the phase0 logic `compute_attestation_rewards_base` as well?

**Comment by michaelsproul** [comment]
> I wasn't sure if we also needed to add in the process_justification_and_finalization to the phase0 logic compute_attestation_rewards_base as well?

Good point. I think we do, as phase0 rewards calculation also uses `is_in_inactivity_leak`.

**Comment by zack-scott** [comment]
> > I wasn't sure if we also needed to add in the process_justification_and_finalization to the phase0 logic compute_attestation_rewards_base as well?
> 
> Good point. I think we do, as phase0 rewards calculation also uses `is_in_inactivity_leak`.

@michaelsproul sounds good, I will get the logic added for phase0 and tested as well

**Comment by zack-scott** [comment]
@michaelsproul I have added in the logic for phase0 to process the justification and finalization and added in tests to ensure it is working as expected.

**Comment by zack-scott** [comment]
@michaelsproul @jimmygchen this PR is ready for review

**Review by jimmygchen — APPROVED** [review]
Looks great! Thanks @zack-scott

**Pull request merged**
