### PR TITLE
Delete milagro library

### PR DESCRIPTION
**Pull request by chong-he**
## Proposed Changes

Delete Milagro BLS library from the source code as it is not used anymore

### CODE REVIEW

**Review by jxs — APPROVED** [review]
codewise lgtm :) are we not using the milagro feature anymore?

**Comment by michaelsproul** [comment]
> are we not using the milagro feature anymore?

Yeah the Milagro library is not really recommended for production use, and AFAIK was only being used by 1 user on an ancient CPU (like 2008) that wasn't supported by `blst`.

**Comment by jxs** [comment]
@mergifyio queue

**Comment by michaelsproul** [comment]
@mergifyio requeue

**Pull request merged**
