### PR TITLE
[Merged by Bors] - Libp2p v0.48.0 upgrade

### PR DESCRIPTION
**Pull request by divagant-martian**
## Issue Addressed

Upgrades libp2p to v.0.47.0. This is the compilation of
- [x] #3495 
- [x] #3497 
- [x] #3491 
- [x] #3546 
- [x] #3553

### CODE REVIEW

**Comment by divagant-martian** [comment]
this is running on mast

**Comment by michaelsproul** [comment]
Wondering if we should consider delaying this until after The Merge, in case we need to hotfix release from `unstable` and aren't sure about shipping this with the hotfix? The other changes to `unstable` recently have been more cosmetic.

**Pull request closed without merging**
