### PR TITLE
[WIP] Bring get_shuffling() up to date

### LINKED ISSUE #151: Implement/update `get_shuffling`
## Description

Implement `get_shuffling` from the spec.

There is an [existing implementation](https://github.com/sigp/lighthouse/blob/master/beacon_chain/validator_shuffling/src/shuffle.rs) that I highly suspect has been outdated.

## Steps to complete

- Rename the existing function to `get_shuffling` (instead of `shard_and_committees_for_cycle`).
- Identify and fix any logic differences between the spec and our implementation.
- Test thoroughly.

### PR DESCRIPTION
**Pull request by drozdziak1**
This implements the get_shuffling() function as per the spec on commit
date. However, shuffle() was not adjusted because of possible phasing it
out by the Foundation.

beacon_state.rs:
* Change the old function name to get_shuffling

spec:
* Add FAR_FUTURE_SLOT
* Rearrange variables to match the spec
* Use FAR_FUTURE_SLOT for test data (process_deposit induces new
validators with same values)

types::validator_record.rs:
validator_induction::inductor:
* Amends for ChainSpec changes

validator_shuffling:
* Move shuffle.rs to lib.rs
* Add all get_shuffling() and all related helper functions

## Issue Addressed
Closes #151.

### TODO
* [x] - Fix the block production tests (The tests somehow overflow the stack)
* [ ] - Agree on and use more appropriate modules for the helpers I introduce, identify any that may overlap with Alex (Many were very simple so I just hacked on them)
* [ ] - Unit testing (My guess is this might work best with Mamy's YAMLs)

### CODE REVIEW

**Comment by drozdziak1** [comment]
Fixed block production, turned out to be ssz problems (Important note! Field order is very easy to confuse, especially between fields of same type!)

**Comment by drozdziak1** [comment]
Rebased on top of #140, also used Alex's `get_active_validator_indices` and `is_active_at`. @paulhauner do unit tests make sense for this while we still don't know the fate of `shuffle()` (ethereum/eth2.0-pm#323, asked if current shuffling has to go)?

**Comment by paulhauner** [comment]
#180 moved shuffling on the `BeaconState` struct and removed the validator_shuffling crate (yay, less crates).

This new implementation doesn't have any tests and hasn't been tested. If you're interested, you could check it out and see if you can do it better. 

https://github.com/sigp/lighthouse/blob/af35bccd7c7df8bc93344fcbb4cbccbab9f782af/eth2/types/src/beacon_state.rs#L596

I also understand if you're frustrated by the overridden PRs. My apologies for that.

**Comment by paulhauner** [comment]
I'm going to close this, let me know if you want to re-open :)

**Pull request closed without merging**
