### PR TITLE
[Merged by Bors] - Linkcheck fix

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

I think we're running into this in our linkcheck, so I'm going to frist verify linkcheck fails on the current version, and then try downgrading it to see if it passes https://github.com/chronotope/chrono/issues/755

### CODE REVIEW

**Comment by realbigsean** [comment]
Oh I think we need to change the lighthouse book for the linkcheck to run in CI.. but this worked for me locally

**Review by michaelsproul — APPROVED** [review]
Happy to try this, although I don't see how the `chrono` issue is implicated

**Comment by realbigsean** [comment]
image

The panic is here, this is from the gas limit API CI run

**Comment by realbigsean** [comment]
The mdbook docker container uses chrono, was digging into it earlier. Sorry for the lack of description 😊

**Pull request closed without merging**
