### PR TITLE
Delete PRE_CAPELLA_ENGINE_CAPABILITIES

### PR DESCRIPTION
**Pull request by chong-he**
## Issue Addressed

* #4848 

## Proposed Changes

Delete PRE_CAPELLA_ENGINE_CAPABILITIES

## Additional Info

This is no longer required since the mainnet is post Capella for a while

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Perfect, thanks CK!

**Review by dapplion — APPROVED** [review]

**Comment by michaelsproul** [comment]
@mergifyio queue

**Comment by jimmygchen** [comment]
@mergify queue

**Comment by jimmygchen** [comment]
@mergifyio requeue

**Comment by michaelsproul** [comment]
@mergifyio requeue

**Comment by realbigsean** [comment]
@Mergifyio requeue

**Comment by realbigsean** [comment]
@mergifyio refresh

**Comment by realbigsean** [comment]
@Mergifyio requeue

**Comment by realbigsean** [comment]
@Mergifyio requeue

**Pull request merged**
