### PR TITLE
Testnet: `merge-devnet-5`

### PR DESCRIPTION
**Pull request by paulhauner**
## Description

This PR is intended for `merge-devnet-5` users. Whilst `unstable` is compatible, we recommend this branch since it includes the "baked-in" network config (i.e., you can do `--network merge-devnet-5`).

## Notes

This PR is equivalent to `unstable`, except for:

- Addition of `--network merge-devnet-5` support.
- Addition of Github Action to publish a `sigp/merge-devnet-5` dockerhub image.

### CODE REVIEW

**Comment by paulhauner** [comment]
This branch was just rebased onto the latest `unstable`.

**Comment by paulhauner** [comment]
I've just rebased to include this fix: https://github.com/sigp/lighthouse/pull/3043#issuecomment-1061380501

**Comment by paulhauner** [comment]
Rebased onto latest `unstable`.

**Comment by pawanjay176** [comment]
`merge-devnet-5` is getting deprecated today. I think we are good to close this.

**Pull request closed without merging**
