### PR TITLE
[Merged by Bors] - Implement API for block rewards

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Add an API endpoint for retrieving detailed information about block rewards.

For information on usage see [the docs](https://github.com/sigp/lighthouse/blob/block-rewards-api/book/src/api-lighthouse.md#lighthouseblock_rewards), and the source.

### CODE REVIEW

**Comment by michaelsproul** [comment]
TODO before this is ready to merge:

* Basic API tests
* Remove `unwrap`s

**Comment by michaelsproul** [comment]
Update: I've added an SSE event to the `/eth/v1/events` endpoint with the topic name `block_reward`. It outputs a `BlockReward` JSON object for each block that is processed, suitable for sending to the classifier. For a demo see the event listener in `blockprint`: https://github.com/sigp/blockprint/blob/b296431f706443c4a83969068bed532e6bd3e0c9/event_listener.py

**Comment by michaelsproul** [comment]
I'm going to add the number of skipped slots from the parent to the reward information, because rewards at skipped slots are usually higher (and they should be). This will be a breaking change to the API between Lighthouse and blockprint but I'll update both together.

**Comment by michaelsproul** [comment]
I'd been getting memory leaks* running large queries against this API and I think I've finally found the cause. Profiling with [dhat-rs](https://github.com/nnethercote/dhat-rs) shows huge amounts of memory being allocated by the tree hash cache, on the order of 370GB in 30 minutes (12GB per minute).

thc_372gb

This is exacerbated by running on a machine with 32 cores, in which case GNU malloc will use up to 64 memory arenas. As a workaround setting `MALLOC_ARENA_MAX=1` seems to stop the fragmentation and reduce the memory usage from 60GB+ (OOM) to <2GB when running for an extended period.

I'm planning to write a new generic `BlockReplayer` which can be used for this API and internally by the database. It will avoid re-calculating state roots unnecessarily as per https://github.com/sigp/lighthouse/pull/2431, and provide callbacks to hook into the block replay (e.g. for the block rewards we want to run a hook before each block is applied).

**Comment by michaelsproul** [comment]
Rebased on #2863, although it hasn't entirely solved the memory issues on high-core machines so I'm going to continue using a `MALLOC_ARENA_MAX` limit

**Review by paulhauner — APPROVED** [review]
LGTM!

**Comment by michaelsproul** [comment]
bors r-

gonna batch

**Pull request closed without merging**
