### PR TITLE
[Merged by Bors] - Remove unused deps

### PR DESCRIPTION
**Pull request by gilescope**
Found some deps you're possibly not using.

Please shout if you think they are indeed still needed.

### CODE REVIEW

**Comment by paulhauner** [comment]
Thanks for taking the initiative here @gilescope. It seems that CI deems at least some of these dependencies as necessary.

Notably, we do already run `cargo udeps` in our CI so that our test-suite fails if we have any unused deps:

https://github.com/sigp/lighthouse/blob/b0ac3464ca5fb1e9d75060b56c83bfaf990a3d25/.github/workflows/test-suite.yml#L223-L238

Do you have reason to believe that `cargo udeps` is giving false negatives?

**Comment by gilescope** [comment]
Good question. Running udeps after this PR gives these results:
```
unused dependencies:
`beacon_chain v0.2.0 (/home/gilescope/git/lighthouse/beacon_node/beacon_chain)`
└─── dependencies
     └─── "tempfile"
`genesis v0.2.0 (/home/gilescope/git/lighthouse/beacon_node/genesis)`
└─── dependencies
     └─── "environment"
`store v0.2.0 (/home/gilescope/git/lighthouse/beacon_node/store)`
└─── dependencies
     └─── "sloggers"
`types v0.2.0 (/home/gilescope/git/lighthouse/consensus/types)`
└─── dependencies
     ├─── "itertools"
     ├─── "merkle_proof"
     └─── "tempfile"
```
Of these the "merkel_proof" can be removed. All the others can't as they are used and leads to compile errors.
Why didn't undepend detect that merkel_proof could be removed? It was because one of the features depended on it: 
 "merkle_proof/arbitrary",
and currently cargo-edit's rm won't automagically remove feature references to a crate that has been removed. (Have raised this as an issue: https://github.com/killercup/cargo-edit/issues/490 )

Will take a look at the CI and see where we have been too aggressive.

**Comment by gilescope** [comment]
@paulhauner right ready for review now it's passed all the CI.

**Comment by paulhauner** [comment]
This is awesome, thanks @gilescope! I love seeing 264 lines removed :tada: 

Would you mind resolving the conflict, please? I'll merge after that :)

**Comment by gilescope** [comment]
@paulhauner ok looks good from my side.

**Review by michaelsproul — APPROVED** [review]
Will batch this with a few other PRs

**Pull request closed without merging**
