### PR TITLE
rustfmt & clippy in CI builds

### PR DESCRIPTION
**Pull request by spble**
## Issue Addressed

N/A

## Proposed Changes
- Jenkins will fail the build if rustfmt check does not pass.
- Travis will do the rustfmt check before building (to fail quicker)

### CODE REVIEW

**Comment by paulhauner** [comment]
@AgeManning thoughts about failing on clippy lints?

I definitely think it's a good idea in the long term, I am just cautious to make sure it's not going to cause short-term grief with your new service stuff.

**Comment by AgeManning** [comment]
I like the idea of failing on clippy lints. 
For sure, all my new stuff will fail. But I'm not concerned with that. Eventually, it will be clippy linted and nice.

**Comment by paulhauner** [comment]
So you're fine with nothing going to master unless it passes clippy?

**Comment by AgeManning** [comment]
Oh yeah I see, because the master will fail if we do...... I was just thinking about the PR's and was thinking we just merge exceptions. 

Yeah, in this case, I think it would be good to have, but maybe later when our project is a little more robust, without massive PR's and code all over the place. 

Otherwise I think there will be more overhead in putting clippy ignores all over the place when at the moment we just need to get stuff done, rather than worrying about clippy.

**Comment by spble** [comment]
Ok, labelled this as 'wontfix' for now, we can merge this in future; maybe after the testnet is ready.

**Comment by paulhauner** [comment]
Can we close this one?

**Comment by spble** [comment]
I've just commented out clippy for now, until he comes back later on.

However, the other changes including `rustfmt`in Jenkins, and moving it up in the queue, are still useful.

**Pull request merged**
