### PR TITLE
v4.6.0-rc.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions

## Additional Info

NA

### CODE REVIEW

**Comment by paulhauner** [comment]
I just force-pushed to recognise updates to `unstable` and to add #5049 and #5048.

**Comment by pawanjay176** [comment]
Pushed michael's commit to upgrade the `ethereum_serde_utils` dependency since this branch was referencing the deleted branch. 
Feel free to rebase again if required.

**Comment by paulhauner** [comment]
Rebased on `unstable` to include recently merged PRs.

**Comment by paulhauner** [comment]
I've checked over the logs and metrics and I'm happy to (pre-)release this!

**Review by michaelsproul — APPROVED** [review]
Let's goo!

**Review by AgeManning — APPROVED** [review]
Just getting in to double approve!

**Pull request merged**
