### PR TITLE
replace instant with web-time

### PR DESCRIPTION
**Pull request by jxs**
`instant` has been abandoned, see https://github.com/sebcrozet/instant/issues/52#issuecomment-1975120097

### CODE REVIEW

**Review by ackintosh — APPROVED** [review]
LGTM!

**Comment by jxs** [comment]
@mergifyio queue

**Review by pawanjay176 — APPROVED** [review]
Just noting here that `web-time` simply re-exports `std::time` for non wasm targets so we aren't using any specialized implementations of `Instant` in Lighthouse, so no heartbeat issues can arise from this.

**Comment by jxs** [comment]
@mergifyio queue

**Comment by realbigsean** [comment]
@mergify queue

**Pull request merged**
