### PR TITLE
Space-efficient archive node

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Builds on `tree-states` to drastically reduce the size of archive nodes with SPRP=32. This is achieved using two main optimisations:

- Avoid storing the duplicated immutable parts of the validator in the `PartialBeaconState`s of the DB. The immutable parts of the validator are its public key and withdrawal credentials.
- Apply `zstd` compression to all `PartialBeaconState`s stored in the DB: this is effective at compressing the remaining fields that are likely to be similar, e.g. the mutable parts of `state.validators`, the `state.balances`, and the eth1 data votes.

## Additional Info

My plan is to clean this up and merge it into #3206 along with #3583, which will give us `tree-states` + all the new database optimisations in one schema migration. To ease backwards-compatibility I'm going to investigate how to make the new schemas for restore points and frozen blocks _optional_, so that old nodes can keep running as they are, but new nodes and early adopters can switch to the more efficient schema.

### CODE REVIEW

**Comment by michaelsproul** [comment]
I've merged this down into `tree-states` but will leave the branch up for anyone relying on it (just @alex88 I think).

**Comment by alex88** [comment]
@michaelsproul I can just switch to that branch to continue testing it, not a problem! Thank you for thinking about it

**Comment by michaelsproul** [comment]
@alex88 I've just made a bunch of backwards-incompat changes on `tree-states`, so for your existing node you should keep using this branch. The main `tree-states` branch is also going to undergo a bunch of other renovations in the next few days, so isn't really a stable target for new nodes either

**Comment by alex88** [comment]
I've cloned it into my fork, just in case you change your mind :)

**Pull request merged**
