### PR TITLE
Add CLI Flag for logging to JSON file

### PR DESCRIPTION
**Pull request by kirk-baird**
## Issue Addressed

#382 

## Proposed Changes

Add a CLI flag in validator client, beacon node and account manager `--logger <filepath>` OR `--logger=<filepath>`

Logging to file is in JSON, logging to terminal to remain formatted in existing style.

### CODE REVIEW

**Comment by paulhauner** [comment]
@kirk-baird are you still intending to do the `logger` -> `log` change? :)

**Comment by kirk-baird** [comment]
Yep, I'll do that now.

**Comment by paulhauner** [comment]
This is blocked on #413 as it will have conficts.

**Comment by paulhauner** [comment]
#413 has been merged, issue unblocked!

**Comment by paulhauner** [comment]
There seems to still be merge conflicts?

**Comment by paulhauner** [comment]
Looks good to me, but I noticed there's an `unverified` commit.

If you're comfortable with that unverified commit, feel free to merge when ready :)

**Comment by kirk-baird** [comment]
Excellent, yep that was my bad. Tried to sign it with the wrong email address.

**Pull request merged**
