### PR TITLE
Spadina support

### LINKED ISSUE #1651: Add a Spadina testnet flag
## Description

Add the testnet config for Spadina: https://github.com/goerli/medalla/tree/master/spadina

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

Resolves #1651 

## Proposed Changes

Add spadina compressed config. Also changes the testnet zip file naming from 
`testnet_{name}_{commit}_{genesis_is_known} -> testnet_{name}_{genesis_is_known}` since we don't download the config files from github anymore.

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Looks good to me!

I tested by running a Spadina BN, which detected deposits and started waiting for genesis.

I also made a new wallet and validator, and created a deposit which was recognised as valid :tada: 
(https://spadina.beaconcha.in/validator/0xb6fa68083a609c1ec0482bfa657b7b7ae56595fd9332c834d0f790a94c0843d6021d7d7d9b1394cbb4b4408d18605832)

I can see you've simplified the ZIP handling a bit, and I think the new code looks good. ~~Just wondering if we should keep the commit hashes in there. I recall @paulhauner put them in there because of some caching/statefulness issue?~~ EDIT: nvm, just read your explanation about GitHub

If we don't need the commit hashes, do we also not need the `genesis_known` bool in the file path?

**Comment by pawanjay176** [comment]
> If we don't need the commit hashes, do we also not need the `genesis_known` bool in the file path?

I assumed we needed the `genesis_known` to distinguish between an empty and a valid `genesis.ssz` in the config directory. It's not strictly required though. We could push a new zip with the valid `genesis.ssz` once we reach genesis.

**Comment by paulhauner** [comment]
>It's not strictly required though.

Agreed :+1: 

> We could push a new zip with the valid genesis.ssz once we reach genesis.

I'm pretty sure we can get a genesis state now. I recall seeing someone say they pushed the validator count past the minimum. I'll try generate it now and send it through to you @pawanjay176.

**Comment by paulhauner** [comment]
> I'm pretty sure we can get a genesis state now. I recall seeing someone say they pushed the validator count past the minimum. I'll try generate it now and send it through to you @pawanjay176.

Oh, we haven't found min genesis time yet.

I'm torn about removing the `genesis_known` bool. It's not necessary so strictly it should be removed. I'm tempted to just merge this, then come back to it later. *But*, the result of that is adding another ~1.3mb to git history forever.

I think my preference is to remove the `genesis_known` flag in this PR and avoid the history bloat.

**Comment by paulhauner** [comment]
Closed in favour of #1670. I've just copied this PR over there so we can get it merged whilst Pawan is on leave :)

**Pull request closed without merging**
