### PR TITLE
[Merged by Bors] - Release v4.3.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions

## Additional Info

NA

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Looks good to me! Happy to release

**Comment by michaelsproul** [comment]
Looks like it was just the `eth1-simulator` that hung: https://github.com/sigp/lighthouse/actions/runs/5450108402

bors retry

**Comment by paulhauner** [comment]
Third time's the charm

bors retry

**Comment by paulhauner** [comment]
Did I say third? I meant fourth.

bors retry

**Comment by antondlr** [comment]
bors retry

**Comment by jimmygchen** [comment]
bors retry

**Comment by realbigsean** [comment]
bors retry

**Pull request closed without merging**
