### PR TITLE
[Merged by Bors] - Fix clippy errors on tests

### PR DESCRIPTION
**Pull request by ackintosh**
## Issue Addressed

There are some clippy error on tests.

## Proposed Changes

Enable clippy check on tests and fix the errors. 💪

### CODE REVIEW

**Comment by ackintosh** [comment]
Phew, the clippy check has passed!

**Review by paulhauner — APPROVED** [review]
Very nice, thank you!!

bors r+

**Comment by paulhauner** [comment]
bors retry

**Comment by paulhauner** [comment]
bors retry

**Pull request closed without merging**
