### PR TITLE
Re-apply removal of duplicated ssz_tests

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

In one of the big merges, the removal of the duplicated SSZ tests  got dropped.

## Proposed Changes

I cherry-picked the lost commits back onto the master branch.

### CODE REVIEW

**Comment by paulhauner** [comment]
For something exciting, I tried resolving this with the github web editor...

I'll be very surprised if it passes tests.

**Comment by michaelsproul** [comment]
If it fails, I'll just do a rebase.

**Comment by paulhauner** [comment]
It failed on rustfmt! I added the newline with the web-editor!

This is going so well I'm thinking of ditching vim and just doing it all in the browser.

**Comment by paulhauner** [comment]
Oh no, I merged some other PRs and now there's tons of conflicts :(

**Comment by paulhauner** [comment]
Closed in favor of #300

**Pull request closed without merging**
