### PR TITLE
[Merged by Bors] - Builder profit threshold flag

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

Resolves https://github.com/sigp/lighthouse/issues/3517

## Proposed Changes

Adds a `--builder-profit-threshold <wei value>` flag to the BN. If an external payload's value field is less than this value, the local payload will be used. The value of the local payload will not be checked (it can't really be checked until the engine API is updated to support this).

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
This is great!

Users seem to like seeing their CLI params reflected in the logs, maybe we could add an info log on start-up, or include the threshold in an existing info log about the builder API?

**Comment by realbigsean** [comment]
Good idea! Added here: ec3227803d93aa93506f5e971bd38a0c135ad4fd

**Review by michaelsproul — APPROVED** [review]
Nice, LGTM

**Pull request closed without merging**
