### PR TITLE
[Merged by Bors] - Add Content-Type to metrics server

### LINKED ISSUE #2013: Missing Content-Type header for metrics
## Description

Not really a bug but the http response of the prometheus endpoint lacks a `Content-Type` header (should be `text/plain`). Unfortunately influxdb2 fails to properly scrap the endpoint without that.

## Version

`sigp/lighthouse:v1.0.2`

## Present Behaviour

```
http -h http://172.17.0.1:5054/metrics
HTTP/1.1 200 OK
content-length: 40138
date: Sun, 29 Nov 2020 19:45:14 GMT
server: Lighthouse/v1.0.2-f7183098e/x86_64-linux
```

## Expected Behaviour

```
http -h http://172.17.0.1:5054/metrics
HTTP/1.1 200 OK
content-length: 40138
content-type: text/plain; charset=utf-8
date: Sun, 29 Nov 2020 19:45:14 GMT
server: Lighthouse/v1.0.2-f7183098e/x86_64-linux
```

Exemple Geth output:

```
http -h http://172.17.0.1:6060/debug/metrics/prometheus
HTTP/1.1 200 OK
Content-Length: 46840
Content-Type: text/plain
Date: Sun, 29 Nov 2020 19:44:46 GMT
```

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

- Resolves #2013

## Proposed Changes

Adds the `Content-Type text/plain` header as per #2013

## Additional Info

NA

### CODE REVIEW

**Review by realbigsean — APPROVED** [review]

**Review by realbigsean — APPROVED** [review]
LGTM

**Comment by realbigsean** [comment]
Oh this is pointing at stable..

**Comment by paulhauner** [comment]
Thanks @realbigsean! I'm going to block this one until after `v1.0.3`.

**Comment by paulhauner** [comment]
bors r-

(Attempting to batch)

**Pull request closed without merging**
