### PR TITLE
[Merged by Bors] - Fix clippy lints for rust 1.62

### PR DESCRIPTION
**Pull request by divagant-martian**
## Issue Addressed

Fixes some new clippy lints after the last rust release
### Lints fixed for the curious:
- [cast_abs_to_unsigned](https://rust-lang.github.io/rust-clippy/master/index.html#cast_abs_to_unsigned)
- [map_identity](https://rust-lang.github.io/rust-clippy/master/index.html#map_identity) 
- [let_unit_value](https://rust-lang.github.io/rust-clippy/master/index.html#let_unit_value)
- [crate_in_macro_def](https://rust-lang.github.io/rust-clippy/master/index.html#crate_in_macro_def) 
- [extra_unused_lifetimes](https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes)
- [format_push_string](https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string)

### CODE REVIEW

**Review by pawanjay176 — APPROVED** [review]
LGTM.

**Review by realbigsean — APPROVED** [review]

**Comment by paulhauner** [comment]
[Re-run license CLA](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3300)

**Pull request closed without merging**
