### PR TITLE
[Merged by Bors] - Release v4.1.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions.

## Additional Info

NA

### CODE REVIEW

**Comment by paulhauner** [comment]
Current ETA for this release is 20th of April, tentative on testing.

**Comment by paulhauner** [comment]
I'm happy with the results of our testing. This is ready for review and release.

**Review by michaelsproul — APPROVED** [review]
I'm also happy with the testing, let's go! 🚀

**Review by jimmygchen — APPROVED** [review]
Looks good!

**Pull request closed without merging**
