### PR TITLE
[Merged by Bors] - Improve compile time

### LINKED ISSUE #1264: Update web3 to remove duplicate deps
## Description

I started investigating crates with multiple versions present in our dep graph using [`cargo deny`](https://github.com/EmbarkStudios/cargo-deny), and found that our dependency on `web3` v0.11.0 is a source of many duplicated versions, including `tokio`, `hyper` (x2!) and `url`. An excerpt from the condensed dep graph for `tokio` is shown here:

@AgeManning and @pawanjay176 may have known about this already from their quest to upgrade all ours deps to `std::future::Future`, but I figured I'd open this issue because it accounted for the majority of the 40 multiple-version crates in our dep graph.

It looks like this recent PR to `web3` https://github.com/tomusdrw/rust-web3/pull/351 will solve this perfectly! :star_struck:

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Closes #1264

## Proposed Changes

* Milagro BLS: tweak the feature flags so that Milagro doesn't get compiled if we're using BLST. Profiling showed that it was consuming about 1 minute of CPU time out of 60 minutes of CPU time (real time ~15 mins). A 1.6% saving.
* Reduce monomorphization: compiling for 3 different `EthSpec` types causes a heck of a lot of generic functions to be instantiated (monomorphized). Removing 2 of 3 cuts the LLVM+linking step from around 250 seconds to 180 seconds, a saving of 70 seconds (real time!). This applies only to `make` and not the CI build, because we test with the minimal spec on CI.
* Update `web3` crate to v0.13. This is perhaps the most controversial change, because it requires axing some deposit contract tools from `lcli`. I suspect these tools weren't used much anyway, and could be maintained separately, but I'm also happy to revert this change. However, it does save us a lot of compile time. With #1839, we now have 3 versions of Tokio (and all of Tokio's deps). This change brings us down to 2 versions, but 1 should be achievable once web3 (and reqwest) move to Tokio 0.3.
* Remove `lcli` from the Docker image. It's a dev tool and can be built from the repo if required.

### CODE REVIEW

**Comment by michaelsproul** [comment]
Test failure is just that racy DHT test.

This is ready for review

**Review by paulhauner — APPROVED** [review]
Nice, I'm happy to lose those `lcli` commands. I'm pretty sure I'm the only one that uses/used them.

I'm sure this will collectively save *a lot* of time for devs! :D

**Comment by michaelsproul** [comment]
Yay!

bors r+

**Comment by michaelsproul** [comment]
bors retry

**Comment by AgeManning** [comment]
racey DHT should be fixed in current `unstable`, is this not up to date? :thinking:

**Comment by michaelsproul** [comment]
It wasn't up to date when the DHT test failed, but it is now. Looks like Bors failed because of some issue with Ganache in the eth1 simulator: https://github.com/sigp/lighthouse/runs/1515897230?check_suite_focus=true

bors retry

**Comment by michaelsproul** [comment]
Grr, that eth1 simulator. I'm going to see if I've somehow broken it on this branch by testing locally

**Comment by michaelsproul** [comment]
Looks like I was overeager in removing `compat()` shims. They're also required for Tokio 0.2. Think I've got them all now. Will r+ optimistically:

bors retry

**Comment by michaelsproul** [comment]
Fiiiiiinally

**Pull request closed without merging**
