### PR TITLE
[Merged by Bors] - Update checkpoint-sync.md

### PR DESCRIPTION
**Pull request by Madman600**
Remove infura checkpoint sync instructions.

### CODE REVIEW

**Review by pawanjay176 — APPROVED** [review]
Perfect! Thank you so much :)

**Comment by Madman600** [comment]
No problem I appreciate everything you guys do.

**Comment by paulhauner** [comment]
@Madman600 it we've had a failure due to a quirk in Github where it doesn't recognise that the target branch was changed until a new commit is pushed. Could you please push an empty commit?

For your convenience, here's the command for an empty commit:

```
git commit --allow-empty -m "Empty commit"
```

**Comment by Madman600** [comment]
@paulhauner hmmm I didn't actually fork the repo, I just made those changes directly on github so how should I go about doing that?

**Comment by Madman600** [comment]
OK I think I did it.

**Review by paulhauner — APPROVED** [review]
Thanks! This is good to merge, but blocked on the #3862 release. We can merge as soon as that release is done. We don't even need to wait until the release is stable, since this PR only changes docs.

**Pull request closed without merging**
