### PR TITLE
[Merged by Bors] - Harden slot notifier against clock drift

### LINKED ISSUE #3518: Remove interval slot timers from the slasher in favour of dynamic waits
## Description

Currently Lighthouse has two ways of running regular tasks at an offset within a slot:

1. Using interval timers which fire every 12 seconds beginning at the correct offset
2. Using a duration to the desired offset in the slot, which is constantly remeasured using the slot clock

As time has gone on we've realised that (2) is superior in the presence of clock drift, and have ported instances of (1) to (2).

This issue tracks the removal of the remaining interval timers. There are some spots where an interval timer is fine, where the offset of the task from the slot is irrelevant.

## Steps to resolve

Remove the slot-based interval timers from:

- [x] [`beacon_node/client/src/notifier.rs`](https://github.com/sigp/lighthouse/blob/18c61a5e8be3e54226a86a69b96f8f4f7fd790e4/beacon_node/client/src/notifier.rs#L49)
- [ ] [`slasher/service/src/service.rs`](https://github.com/sigp/lighthouse/blob/18c61a5e8be3e54226a86a69b96f8f4f7fd790e4/slasher/service/src/service.rs#L97)

Other interval timers in `eth1`, `monitoring_api`, and `lighthouse_network` can remain, as they're not slot-related.

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Partly resolves #3518

## Proposed Changes

Change the slot notifier to use `duration_to_next_slot` rather than an interval timer. This makes it robust against underlying clock changes.

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Nice! This changes the behaviour slightly regarding degenerate cases, if the function takes longer than one slot to execute then we'll skip slots. Previously we'd form a queue and process them all at once.

I think this new behaviour is better since with the current queuing approach we'd end up producing multiple events for the same slot. That seems to have little value, if any.

Happy to merge!

**Comment by michaelsproul** [comment]
> I think this new behaviour is better since with the current queuing approach we'd end up producing multiple events for the same slot. That seems to have little value, if any.

Yeah I think this might have been what @ethDreamer observed a few weeks ago!

**Comment by paulhauner** [comment]
Penta-batch!

bors r+

**Comment by paulhauner** [comment]
There are conflicts in this batch, but I'll let bors figure it out.

bors r+

**Pull request closed without merging**
