### PR TITLE
Remove EL redundancy, bump VC warning to error

### LINKED ISSUE #3127: Feature: Change "Unable to connect to a beacon node" to ERR or CRIT instead of WARN
## Description

The validator client currently logs inability to connect to any beacon node as a warning: `WARN Unable to connect to a beacon node`

The same severity as a single beacon node being down when failover is configured: `WARN Offline beacon node`

I'd like to see the inability to connect to any beacon node become an ERR or CRIT log, please. Something like `ERR Unable to connect to a beacon node`

## Rationale

This simplifies alerting. Instead of needing to parse logs for "Unable to connect", I can use `error_total` and `crit_total` to raise critical alerts that wake someone up, and `warn_total` as a non-critical alert that gets handled during business hours.

### LINKED ISSUE #3307: Remove redundancy in the ulrs in the execution layer' config
## Description

After removing the fallback for engines in the execution_layer crate, we don't need the `secret_files` and `execution_endpoint` to be able to hold more than one in each field. Those could be changed to be options or even mandatory fields.

The relevant code is [here](https://github.com/sigp/lighthouse/blob/748475be1ded2c9a29cbd8b985f6ae2980720a36/beacon_node/execution_layer/src/lib.rs#L119-L123)

### PR DESCRIPTION
**Pull request by AndyBarnard**
## Issue Addressed

Resolves #3307
Resolves #3127

## Proposed Changes

- remove execution layer redundancy
- change the warning to an error when "Unable to connect to a beacon node"

### CODE REVIEW

**Comment by michaelsproul** [comment]
It looks like you've rolled your changes from #3366 into this PR, which is fine, we can review it all in one go.

I'll close #3366 for now seeing as this PR seems to have the latest changes, but feel free to reopen it if you would prefer to merge them separately

**Review by michaelsproul — CHANGES_REQUESTED** [review]
Currently CI is failing because of a formatting failure. You can fix it up by running

```
cargo fmt --all
```

**Comment by divagant-martian** [comment]
it seems to be there are some failures. You can check the failures by going to the root lighthouse dir and running `make lint`, it will show you both some compilation issues in the tests and if there is any clippy failure it will show it too

**Comment by paulhauner** [comment]
Closing due to inactivity, please feel free to reopen if you'd like to continue these efforts :pray:

**Pull request closed without merging**
