### PR TITLE
Verify whether validators really are unknown during sync committee duty API request

### PR DESCRIPTION
**Pull request by dknopik**
## Issue Addressed

- #4717

## Proposed Changes

- `BeaconState::get_sync_committee_duties` now reports `UnknownValidator` for every requested unknown validator instead of only for the first. 
- For every `UnknownValidator`, we check the state at `request_epoch`. If the validator is known there, instead report that the validator has no duties. If the validator is still unknown, respond with an error.
- The state at `request_epoch` is loaded lazily, so this change should not a incur significant performance impact if all validators are found initially. 

## Additional Info

Additionally to a fix for #4714, I introduced that a HTTP 400 response is sent if the validator really is unknown in order to conform to the Beacon API spec.

### CODE REVIEW

**Comment by dknopik** [comment]
@michaelsproul test failures seem to be spurious

**Review by michaelsproul — APPROVED** [review]
LGTM, thanks!

**Comment by jimmygchen** [comment]
Tagging `v5.2.0` since this has been approved (not merging now due to 5.1.0 release).

**Comment by realbigsean** [comment]
@Mergifyio queue

**Comment by realbigsean** [comment]
@Mergifyio requeue

**Pull request merged**
