### PR TITLE
[WIP] Added Block Rewards To Rewards Tests

### PR DESCRIPTION
**Pull request by Gua00va**
## Issue Addressed
Solves #4856
## Tasks
- [x] Add block rewards to the given test cases.
- [x] Add new enum to avoid calcualting proposer rewards for the rewards API.
## Additional Information
`inclusion_delay` in attestation rewards response does include proposer rewards amount for when calcuating attestation rewards for rewards API.

### CODE REVIEW

**Comment by Gua00va** [comment]
@jimmygchen, Can't figure out why 
https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L130

is  passing even though I have added block rewards seperately.

**Comment by zack-scott** [comment]
>[lighthouse/beacon_node/beacon_chain/tests/rewards.rs](https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L130)
>
>https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L130
>
> async fn test_verify_attestation_rewards_base() { 
>is passing even though I have added block rewards seperately.

@Gua00va I checked out the PR and ran locally. I am seeing the test fail that you mention above:

Screenshot 2023-10-26 085928

**Comment by Gua00va** [comment]
> > [lighthouse/beacon_node/beacon_chain/tests/rewards.rs](https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L130)
> > https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L130
> > 
> > async fn test_verify_attestation_rewards_base() {
> > is passing even though I have added block rewards seperately.
> 
> @Gua00va I checked out the PR and ran locally. I am seeing the test fail that you mention above:
> 
> Screenshot 2023-10-26 085928

Ahh.. sorry!! I mean this test :
https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L223

**Comment by zack-scott** [comment]
@Gua00va you may also want to remove line:
https://github.com/sigp/lighthouse/blob/71ef86be46a82f1e9d044c790d46e081ef4ad2ec/beacon_node/beacon_chain/tests/rewards.rs#L143

This is due to you moving the slot in the while loop:
https://github.com/sigp/lighthouse/blob/71ef86be46a82f1e9d044c790d46e081ef4ad2ec/beacon_node/beacon_chain/tests/rewards.rs#L167
The above line 143 would put you an epoch past the rewards you are needing to check. I was seeing a big difference in actual balances vs expected balances until I removed the line 143 locally.

**Comment by zack-scott** [comment]
> > > [lighthouse/beacon_node/beacon_chain/tests/rewards.rs](https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L130)
> > > https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L130
> > > 
> > > async fn test_verify_attestation_rewards_base() {
> > > is passing even though I have added block rewards seperately.
> > 
> > 
> > @Gua00va I checked out the PR and ran locally. I am seeing the test fail that you mention above:
> > Screenshot 2023-10-26 085928
> 
> Ahh.. sorry!! I mean this test :
> 
> https://github.com/sigp/lighthouse/blob/fc7f1ba6b94ac3300338aad4d5168aaac5df3fac/beacon_node/beacon_chain/tests/rewards.rs#L223

@Gua00va looks like the test is only checking balances for 3 validators:

https://github.com/sigp/lighthouse/blob/71ef86be46a82f1e9d044c790d46e081ef4ad2ec/beacon_node/beacon_chain/tests/rewards.rs#L370

The test is passing due to that fact that it's very likely that those validators did not propose a block during the epoch the test is checking.

**Comment by Gua00va** [comment]
@zack-scott, I have added some changes to reward calculations, but the tests are still failing. Can't seem to understand why ?

**Comment by jimmygchen** [comment]
Hi @Gua00va could you provide some details on the failure you're seeing?

**Comment by zack-scott** [comment]
@jimmygchen I am not sure what the issue is here. I can try to take a deeper look into the codebase soon, but I did come across something strange while validating something on the indexer I am writing. The information below is regarding mainnet data using Lighthouse node v4.5.0.

I believe that the proposal reward calculation for at least one validator is potentially incorrect. I think I have found more, but I am going to upload images of validator 9. Validator 9 at slot `1938051` earned a proposal reward, but when I compare this to the double counting of the inclusion_delay in attestation rewards, I seem to see a completely different value i.e. proposal reward for phase0 seems to be off potentially. I say proposal reward for phase0 because when looking at the balance deltas (`/eth/v1/beacon/states/{state_id}/validators`) I see the change reflect the phase0 attestation reward instead of the phase0 proposal reward. The assumption here is that the attestation reward for epoch `60564` is correct and includes double counting in inclusion delay for validator 9.

If proposal reward calculation is off, I am wondering if this would throw off the tests that @Gua00va is trying to write?

Screenshot 2023-11-13 at 4 25 10 PM

The above image is the result of validator 9 during the epoch `60564` for phase0. We have two rewards during this epoch for validator 9 of type Proposal and Attestation. The `value` field is the sum of the attestation pieces or for proposal just a direct mapping from response.

Proposal reward_type is retrieved from `/eth/v1/beacon/rewards/blocks/{block_id}`
Attestation reward_type is retrieved from `/eth/v1/beacon/rewards/attestations/{epoch}`

@jimmygchen could you look into those values for validator 9 given the information above to see if you are seeing the same issue?

Actually, I think the proposal reward earned at slot `1938051` for validator 9 was applied over two different epochs. Is this a possibility potentially for proposal reward to be applied over two different epochs? 

The image below is taking a look at the delta balance changes starting with 60564 - 60566, which looks like the proposal reward was applied over two epochs.
Screenshot 2023-11-15 at 11 07 13 AM

If proposal rewards can be applied to balance snapshot `/eth/v1/beacon/states/{state_id}/validators` over two epochs @Gua00va , this also might be throwing off the calculation when taking into account proposal rewards manually.

**Comment by jimmygchen** [comment]
@zack-scott thanks for the interesting findings!

I think it may be related to this line below - the standard block rewards api goes through the below code path, where the last bool `include_attestations` is set to `true`, and should probably be `false` in the block rewards API scenario: (although I haven't look deep enough to be sure)
https://github.com/sigp/lighthouse/blob/07f53b18fcd01bb83385c4c62332d960e6dd3b4e/beacon_node/beacon_chain/src/beacon_block_reward.rs#L180

I don't have an mainnet archive node available right now to test, but I think it would be useful to compare the standard block rewards API result against the Lighthouse custom endpoint: `POST lighthouse/analysis/block_rewards` for this slot:

```
curl -X GET "http://localhost:5052/lighthouse/analysis/block_rewards?start_slot=1&end_slot=1" | jq
```

**Comment by zack-scott** [comment]
@Gua00va I think the way the altair fork and later apply proposal rewards to balances and the way the phase0 apply proposal rewards may be different. I.e. altair applies change to balance the same slot the proposal reward was earned. The phase0 looks to be delayed a little in applying balance changes for proposal rewards potentially. This may be why you are getting balance changes that do not make sense.

I removed the block proposal reward calculation and saw balances match more with a few being off that are probably proposal rewards differences but prior to when you tried to calculate manually for proposal rewards.

**Comment by michaelsproul** [comment]
Something else that could be causing the discrepancy is this: https://github.com/sigp/lighthouse/issues/4929

I've had that issue in the back of my mind for a while and was meaning to write it up so we could fix it as part of the rewards API polishing.

**Comment by dknopik** [comment]
>Something else that could be causing the discrepancy is this: https://github.com/sigp/lighthouse/issues/4929

Unfortunately, my fixes at https://github.com/sigp/lighthouse/pull/5101 did not make the adjusted tests in this PR pass. However, as @zack-scott has mentioned, the phase0 block rewards are credited at epoch boundaries. In detail, the problem is:

The test first generates epoch 0, including the first epoch boundary. At this boundary, no proposer rewards are given, as all attestations have target epoch 0, and thus rewards are given out at the end of epoch 1. Then, the test captures the current balances. While generating epoch 1, the test captures all proposer and attestation rewards. At the end of epoch 1, most epoch 1 proposer rewards are not credited yet, as now most attestations will have target epoch 1, for which rewards are credited at the end of epoch 2! Unfortunately, we can not simply shift the balance captures by one epoch, as in the first slot of epoch 1, there are still attestations with target 0, which are credited at the end of epoch 1...

The various points in time where different rewards are actually credited makes this a bit annoying to test. I believe the best approach would be to generate 2 epochs with blocks, calculating all rewards for attestations and proposals, and then generate 2 epochs of empty slots to make sure all rewards are credited (without causing more rewards). Then, we check if the calculated and summed rewards (+ starting balance) match the current balances.

**Comment by zack-scott** [comment]
@Gua00va @jimmygchen 
I was able to get the test to pass by making adjustments. I started calculation at epoch 0, and I added proposal rewards into mapping to be calculated if the proposal happened in epoch 0. Then, I ensured in the for loop for calculation we continued processing until epoch 2.

One issue with previous test is that we were missing proposal rewards for epoch 0 in the proposal_rewards_map.

The below snippet is of the test that I have working on my local station. I don't think I have access to update PR directly. Please review to see if this is working for you guys.

```
#[tokio::test]
async fn test_verify_attestation_rewards_base() {
    let harness = get_harness(E::default_spec());

    // epoch 0 (N), only two thirds of validators vote.
    let two_thirds = (VALIDATOR_COUNT / 3) * 2;
    let two_thirds_validators: Vec<usize> = (0..two_thirds).collect();

    let initial_balances: Vec<u64> = harness.get_current_state().balances().clone().into();

    let mut proposal_rewards_map: HashMap<u64, u64> = HashMap::new();

    for _ in 0..(E::slots_per_epoch() * 2) {
        let state = harness.get_current_state();
        let slot = state.slot() + Slot::new(1);

        let ((signed_block, _maybe_blob_sidecars), mut state) =
            harness.make_block_return_pre_state(state, slot).await;
        let beacon_block_reward = harness
            .chain
            .compute_beacon_block_reward(
                signed_block.message(),
                signed_block.canonical_root(),
                &mut state,
            )
            .unwrap();

        if harness.get_current_slot().epoch(E::slots_per_epoch()) < 1 {
            let total_proposer_reward = proposal_rewards_map
                .get(&beacon_block_reward.proposer_index)
                .unwrap_or(&0u64)
                + beacon_block_reward.total;
            proposal_rewards_map.insert(beacon_block_reward.proposer_index, total_proposer_reward);
        }

        harness
        .extend_slots_some_validators(1, two_thirds_validators.clone())
        .await;
    }

    // compute reward deltas for all validators in epoch N
    let StandardAttestationRewards {
        ideal_rewards,
        total_rewards,
    } = harness
        .chain
        .compute_attestation_rewards(Epoch::new(0), vec![])
        .unwrap();

    // assert no inactivity penalty for both ideal rewards and individual validators
    assert!(ideal_rewards.iter().all(|reward| reward.inactivity == 0));
    assert!(total_rewards.iter().all(|reward| reward.inactivity == 0));

    // apply attestation rewards to initial balances
    let expected_balances = apply_attestation_rewards(&initial_balances, total_rewards);
    let expected_balances = apply_beacon_block_rewards(&proposal_rewards_map, expected_balances);

    // verify expected balances against actual balances
    let balances: Vec<u64> = harness.get_current_state().balances().clone().into();
    assert_eq!(expected_balances, balances);
}
```

**Comment by zack-scott** [comment]
@Gua00va @jimmygchen I just edited the above code snippet to also include below logic of what was in original test. The below logic has been moved to for loop and increments by one in the comment https://github.com/sigp/lighthouse/pull/4882#issuecomment-2108589121.
```
harness
        .extend_slots_some_validators(1, two_thirds_validators.clone())
        .await;
```

**Comment by zack-scott** [comment]
@Gua00va I created PR against your fork/branch https://github.com/Gua00va/lighthouse/pull/2

**Comment by zack-scott** [comment]
test_verify_attestation_rewards_base_inactivity_leak is failing. I need to also account for proposal rewards that happen beforehand as well. Hopefully, I will have something within the next couple of days to fix this test.

**Comment by zack-scott** [comment]
@Gua00va @jimmygchen @michaelsproul the test test_verify_attestation_rewards_base_inactivity_leak  has also been fixed and pushed to PR against https://github.com/Gua00va/lighthouse/pull/2/files. Maybe we can get this merged into this PR branch?

**Comment by michaelsproul** [comment]
@zack-scott I've merged your PR into this one, and I also merged the latest unstable. Let's see if the tests pass, and if they do I'll dig in for a review

**Comment by zack-scott** [comment]
@michaelsproul looks like the unstable merge into this branch has caused some regression test failures. I will work on fixing these regression tests as well as fixing the lint issue.

**Comment by zack-scott** [comment]
@michaelsproul I was able to fix the lint error and the beacon test error with PR https://github.com/Gua00va/lighthouse/pull/3 , but I am having issue troubleshooting `ef-tests-ubuntu` locally. I keep getting `handler dir lighthouse/testing/ef_tests/consensus-spec-tests/tests/minimal/phase0/rewards/basic exists: 0s { code: 2, kind: NotFound, message:"No such file or directroy" }`. I am wondering if I need to run some commands prior to the `make nextest-ef` command?

**Comment by zack53** [comment]
@michaelsproul 
I am trying to troubleshoot the ef-tests-ubuntu. I believe a macro is used to generate tests dynamically. I am not sure where to look for test creation logic, but I believe since we removed block proposal counting from attestation value that we need to add in test logic to calculate proposal rewards for ef-tests-ubuntu phase0. Could you help point me in the right location to make the changes?

**Comment by zack53** [comment]
Actually @michaelsproul looks like an updated PR is being reviewed at https://github.com/sigp/lighthouse/pull/5101. Do you know the status on that PR and should we close this PR?

**Comment by michaelsproul** [comment]
Closing in favour of:

- https://github.com/sigp/lighthouse/pull/5101.

**Comment by michaelsproul** [comment]
Thanks @Gua00va for your work. Sorry this took so long to get merged. You should get some green github dots when 5101 makes it into the stable branch :grin:

**Pull request closed without merging**
