### PR TITLE
[Merged by Bors] - upgrade to libp2p 0.52

### PR DESCRIPTION
**Pull request by divagant-martian**
## Issue Addressed

Upgrade libp2p to v0.52

## Proposed Changes
- **Workflows**: remove installation of `protoc`
- **Book**: remove installation of `protoc`
- **`Dockerfile`s and `cross`**: remove custom base `Dockerfile` for cross since it's no longer needed. Remove `protoc` from remaining `Dockerfiles`s
- **Upgrade `discv5` to `v0.3.1`:** we have some cool stuff in there: no longer needs `protoc` and faster ip updates on cold start
- **Upgrade `prometheus` to `0.21.0`**, now it no longer needs encoding checks
- **things that look like refactors:** bunch of api types were renamed and need to be accessed in a different (clearer) way
- **Lighthouse network**
	- connection limits is now a behaviour
	- banned peers no longer exist on the swarm level, but at the behaviour level
	- `connection_event_buffer_size` now is handled per connection with a buffer size of 4
	- `mplex` is deprecated and was removed
	- rpc handler now logs the peer to which it belongs

## Additional Info

Tried to keep as much behaviour unchanged as possible. However, there is a great deal of improvements we can do _after_ this upgrade:
- Smart connection limits: Connection limits have been checked only based on numbers, we can now use information about the incoming peer to decide if we want it
- More powerful peer management: Dial attempts from other behaviours can be rejected early
- Incoming connections can be rejected early
- Banning can be returned exclusively to the peer management: We should not get connections to banned peers anymore making use of this
- TCP Nat updates: We might be able to take advantage of confirmed external addresses to check out tcp ports/ips

### CODE REVIEW

**Comment by divagant-martian** [comment]
@AgeManning delegating to you

**Comment by divagant-martian** [comment]
@AgeManning @pawanjay176 ping for review and workflow approval :roll_eyes: can you guys please deploy this in your infra and lmk how it goes?

**Comment by divagant-martian** [comment]
this now includes the libp2p release with the denial fixed. Can you guys redeploy please?

**Comment by AgeManning** [comment]
This seems to be running fine to me on the testnets. 

Keen to merge this down, to pave the way for some more :hot_pepper: upgrades!

**Review by AgeManning — APPROVED** [review]

**Pull request closed without merging**
