### PR TITLE
[Merged by Bors] - Release v0.3.4

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Bump version to v0.3.4 and update dependencies with `cargo update`.

### CODE REVIEW

**Comment by michaelsproul** [comment]
Waiting on the green light from @AgeManning for networking fixes in `master`, then we can merge this. Maybe today (Friday), or otherwise Monday.

No great rush except that it ships the database fix to Medalla users.

**Review by paulhauner — APPROVED** [review]
LGTM!

**Review by AgeManning — APPROVED** [review]
I got the last PR in. 

This is ready to go once merged!

**Pull request closed without merging**
