### PR TITLE
add logging functionality for aligning key value pairs after message

### LINKED ISSUE #453: Improve logging format
## Description

I think the logs would be nicer if we have a dedicated space between the message title and the key-values associated with `slog`. 

An example of this format is in geth. 

```
INFO [07-26|12:31:47.821] Maximum peer count                       ETH=25 LES=0 total=25
INFO [07-26|12:31:47.826] Starting peer-to-peer node               instance=Geth/v1.9.0-unstable-78d90c47/linux-amd64/go1.12.3
INFO [07-26|12:31:47.826] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
```

This issue involves changing the format of the `slog::Logger`. Hopefully a single change in `main.rs` will propagate this format through the codebase :).

### PR DESCRIPTION
**Pull request by blacktemplar**
## Issue Addressed

resolves #453

## Proposed Changes

This adds a wrapped Decorator used in the main logger for aligning key value pairs after the messages.

## Additional Info

I was a little bit surprised that there is no "easy" method for changing the logging format in slog-term. The way I did it now using wrapper around already existing decorators and finally doing the work of adding the right amount of whitespaces in a wrapped RecordDecorator seems a little bit like a hack to me. 

The only other possibility I saw was to implement a totally new Drain in which we also have to consider serialization of the records and so on (there is a Serialization class in slog-term, but its not public :/). So the way it is now was to try to reuse as much as possible from slog-term.

### CODE REVIEW

**Comment by paulhauner** [comment]
Hey @blacktemplar, looks great. Thank you!

I'm doing some merging today and I'll work towards getting this reviewed and merged.

**Comment by paulhauner** [comment]
I'm not familiar with customizing slog, but this implementation looks elegant. The actual CLI format looks good too.

I'd agree that this should go into it's own crate -- @blacktemplar let me know if you're happy to do that :)

Thanks again

**Comment by blacktemplar** [comment]
Ok I created now an own crate for the logging functionality and use it now also in validator_client.

Furthermore, I changed the message width to 40 characters (as geth also does it), this should give a little bit more space for message titles...

**Comment by paulhauner** [comment]
Thank you!

Two things, sorry:

1. We just merged the v0.8 spec update into master and there's a conflict (it's super small and simple).
2. Would you mind dropping the new crate into `eth2/utils` -- I know it's not actually eth2-related, but our directory structure is a bit legacy at the moment. There's a directory restructure coming soon, this will keep things consistent until then :)

**Comment by blacktemplar** [comment]
Ok I merged master and moved logging to eth2/utils/logging. Had to force-push once since my first merge didn't update the submodule (I am not so used to submodules ...)

**Pull request merged**
