### PR TITLE
[Merged by Bors] - v1.2.1

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

- Bump version.
- Add some new ENR for Prater
    - Afri: https://github.com/eth2-clients/eth2-testnets/pull/42
    - Prysm: https://github.com/eth2-clients/eth2-testnets/pull/43
- Apply the fixes from #2181 to the no-eth1-sim to try fix CI issues. 

## Additional Info

NA

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Ship it!

**Comment by michaelsproul** [comment]
bors retry

**Comment by paulhauner** [comment]
bors retry

**Comment by michaelsproul** [comment]
In the 2nd run, it failed with this error:

```
2021-03-17T23:34:52.0585839Z thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Get head via http failed: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: \"http\", username: \"\", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(35809), path: \"/eth/v1/beacon/states/head/finality_checkpoints\", query: None, fragment: None }, source: TimedOut })"', testing/simulator/src/no_eth1_sim.rs:161:41
```

As far as I can tell we don't even have timeouts set up on `reqwest` so I'm not sure where this is coming from. Will investigate further.

**Comment by paulhauner** [comment]
I just realised we need to update Prater boot nodes. I'll do that, please don't merge until then.

**Comment by paulhauner** [comment]
Boot ENR added, happy to merge now.

**Pull request closed without merging**
