### PR TITLE
error on slot duration mismatch

### PR DESCRIPTION
**Pull request by divagant-martian**
## Issue Addressed

Which issue # does this PR address?

## Proposed Changes

Please list or describe the changes introduced by this PR.

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
LGTM!

I'm interested as to how this came about, was it just something in a custom testnet?

**Comment by divagant-martian** [comment]
no, I was doing some testing on the attestation service and noticed we use one of these values for unsubscriptions and the other for subscriptions so I got curious

**Comment by divagant-martian** [comment]
I'll clean this up

**Comment by divagant-martian** [comment]
I can't find a good solution for this since the spec requires slots in seconds and tests depends on slots of less than a second. Also since we use separate crates I also can't prevent this check from running in other crate tests

**Pull request closed without merging**
