### PR TITLE
[Merged by Bors] - Use unique arg names for eth1-sim

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

When trying to run `eth1-sim` locally, the simulator doesn't start for me, and panicked due to duplicate arg names for `proposer-nodes` (using same arg names as `nodes`). Not sure why this isn't failing on CI but failing on mine 🤔 

```
thread 'main' panicked at 'Argument short must be unique
thread 'main' panicked at 'Argument long must be unique
```

### CODE REVIEW

**Review by pawanjay176 — APPROVED** [review]
Nice catch!

**Comment by michaelsproul** [comment]
re-batching because of the simulator failure

bors r-

**Comment by michaelsproul** [comment]
bors r-
bors +

**Pull request closed without merging**
