### PR TITLE
[Merged by Bors] - v4.2.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions

## Additional Info

NA

### CODE REVIEW

**Comment by paulhauner** [comment]
Rebased onto the latest `unstable`.

**Comment by paulhauner** [comment]
I think we might be getting an excess of "Connected to beacon node" logs from the VC. Potentially related to #4295.

I haven't had time to investigate, just making a note so we don't forget.

**Comment by paulhauner** [comment]
Rebased on `unstable` to include #4315, which fixes the aforementioned VC logs.

**Comment by paulhauner** [comment]
Rebased to include dependency changes in #4074.

**Review by divagant-martian — APPROVED** [review]

**Review by jimmygchen — APPROVED** [review]

**Pull request closed without merging**
