### PR TITLE
[Merged by Bors] - Allow compilation with no slasher backend

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Allowing compiling without MDBX by running:

```bash
CARGO_INSTALL_EXTRA_FLAGS="--no-default-features" make
```

The reasons to do this are several:

- Save compilation time if the slasher won't be used
- Work around compilation errors in slasher backend dependencies (our pinned version of MDBX is currently not compiling on FreeBSD with certain compiler versions).

## Additional Info

When I opened this PR we were using resolver v1 which [doesn't disable default features in dependencies](https://doc.rust-lang.org/cargo/reference/features.html#resolver-version-2-command-line-flags), and `mdbx` is default for the `slasher` crate. Even after the resolver got changed to v2 in #3697 compiling with `--no-default-features` _still_ wasn't turning off the slasher crate's default features, so I added `default-features = false` in all the places we depend on it.

### CODE REVIEW

**Comment by airflow2010** [comment]
I understand that this PR was not included in the latest release v3.5.0. Will this PR be merged and be available in a release before the Shanghai hardfork?

**Comment by michaelsproul** [comment]
@airflow2010 I'm nominating this for inclusion in v3.5.1 which will go out before Capella on Goerli :crossed_fingers:

**Review by paulhauner — APPROVED** [review]
LGTM!

**Comment by airflow2010** [comment]
> @airflow2010 I'm nominating this for inclusion in v3.5.1 which will go out before Capella on Goerli 🤞

I tested the new release already on my system and now I can run the current release of Lighthouse again on FreeBSD. Thanks a lot! 👍

**Pull request closed without merging**
