### PR TITLE
[Merged by Bors] - Ensure protoc is installed for release CI

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

The release CI is currently broken due to the addition of the `protoc` dependency. Here's a failure of the release flow running on my fork: https://github.com/michaelsproul/lighthouse/actions/runs/3155541478/jobs/5134317334

## Proposed Changes

- Install `protoc` on Windows and Mac so that it's available for `cargo install`.
- Install an x86_64 binary in the Cross image for the aarch64 platform: we need a binary that runs on the host, _not_ on the target.
- Fix `macos` local testnet CI by using the Github API key to dodge rate limiting (this issue: https://github.com/actions/runner-images/issues/602).

### CODE REVIEW

**Comment by michaelsproul** [comment]
This is ready for review.

Here's a run mostly working on my fork:

- Release: https://github.com/michaelsproul/lighthouse/actions/runs/3155878354 (fails at the GPG step as expected)
- Docker: https://github.com/michaelsproul/lighthouse/actions/runs/3155878356/jobs/5135005933

**Comment by michaelsproul** [comment]
Actually, `lcli` is still broken. Will fix.

**Comment by michaelsproul** [comment]
Fixed: https://github.com/michaelsproul/lighthouse/actions/runs/3156313582

**Review by paulhauner — APPROVED** [review]
Nice! The simplification of cross Dockerfiles is tidy :relaxed:

**Comment by michaelsproul** [comment]
Thanks!

bors r+

**Pull request closed without merging**
