### PR TITLE
[Merged by Bors] - CommitteeCache.get_all_beacon_committees: set correct capacity to avoid realloc

### PR DESCRIPTION
**Pull request by zhiqiangxu**

### CODE REVIEW

**Comment by michaelsproul** [comment]
Can you please re-target this PR at unstable? You'll need to rebase in order to re-trigger Github's CI

**Comment by zhiqiangxu** [comment]
> Can you please re-target this PR at unstable? You'll need to rebase in order to re-trigger Github's CI

Done.

**Comment by michaelsproul** [comment]
sorry, I think it needs one more force push (you've gotta push a new commit _after_ changing the base branch, github is fussy).

**Comment by zhiqiangxu** [comment]
> sorry, I think it needs one more force push (you've gotta push a new commit _after_ changing the base branch, github is fussy).

Done again:)

**Review by paulhauner — APPROVED** [review]
Nice one, I like it! Thank you.

Out of interest, did you find this by reading the code or by runtime analysis (e.g., `heaptrack`)?

**Comment by zhiqiangxu** [comment]
> Nice one, I like it! Thank you.
> 
> Out of interest, did you find this by reading the code or by runtime analysis (e.g., `heaptrack`)?

The former :)

**Pull request closed without merging**
