### PR TITLE
[Merged by Bors] - Subscribe to subnets only when needed

### PR DESCRIPTION
**Pull request by divagant-martian**
## Issue Addressed

We currently subscribe to attestation subnets as soon as the subscription arrives (one epoch in advance), this makes it so that subscriptions for future slots are scheduled instead of done immediately. 

## Proposed Changes

- Schedule subscriptions to subnets for future slots.
- Finish removing hashmap_delay, in favor of [delay_map](https://github.com/AgeManning/delay_map). This was the only remaining service to do this.
- Subscriptions for past slots are rejected, before we would subscribe for one slot.
- Add a new test for subscriptions that are not consecutive.

## Additional Info

This is also an effort in making the code easier to understand

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]
This looks good. Probably needs some thorough testing on testnets. 

I like the cleaner grouping of logic. This probably corrects any potential issues with overlapping subscriptions as it simplifies the logic.

**Review by AgeManning — APPROVED** [review]
I think this looks fine. We just might need to be careful on over-loaded nodes with how early we are subscribing. Worst case, I think is that we can miss aggregating some attestations.

**Comment by divagant-martian** [comment]
@AgeManning  I changed the fraction of a slot to a whole slot here https://github.com/sigp/lighthouse/pull/3419/commits/e4d8a9487366c945f3bed07f716b5ce2e8b870f8 let me know if we can now get ready for bors

**Pull request closed without merging**
