### PR TITLE
[Merged by Bors] - CommitteeCache.initialized: fail early if possible

### PR DESCRIPTION
**Pull request by zhiqiangxu**

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Thanks for the contribution.

I don't think we will ever actually run this code, a `state.validators` with a length of `2**64 - 1` would be hundreds of thousands of petabytes. However, I'm happy to merge this since it is technically/theoretically better.

**Comment by paulhauner** [comment]
Oh, could you please push an empty commit to make Github realise that I've changed the target branch 🙏

**Comment by zhiqiangxu** [comment]
> Oh, could you please push an empty commit to make Github realise that I've changed the target branch 🙏

Done:)

**Pull request closed without merging**
