### PR TITLE
[Merged by Bors] - Bump the MSRV to 1.62 and using `#[derive(Default)]` on enums

### PR DESCRIPTION
**Pull request by ackintosh**
## Issue Addressed

N/A

## Proposed Changes

Since Rust 1.62, we can use `#[derive(Default)]` on enums. ✨ 

https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#default-enum-variants

There are no changes to functionality in this PR, just replaced the `Default` trait implementation with `#[derive(Default)]`.

### CODE REVIEW

**Comment by ackintosh** [comment]
> test-suite / check-msrv (pull_request) 

https://github.com/sigp/lighthouse/runs/7158153165?check_suite_focus=true

Oh, now I noticed that `rust-version = "1.58"` in [lighthouse/Cargo.toml](https://github.com/sigp/lighthouse/blob/5de00b7ee821dc28f80285acbce083edda4f14a1/lighthouse/Cargo.toml#L7). 👀

**Comment by michaelsproul** [comment]
Yeah, we've had our minimum Rust version pinned to 1.58 for a little while, as we noticed that when we bump the version several users complain about compilation issues while trying to use the old compiler.

We could wait a few weeks before merging this PR? Or I'm also not opposed to merging it now and triggering a compiler version bump.

**Comment by realbigsean** [comment]
I'm pro bumping the MSRV but should we consider only including MSRV bumps in minor lighthouse releases? As in we always consider it breaking? I'm gonna mark this as backwards incompat for now. 

cc @paulhauner @michaelsproul

**Comment by michaelsproul** [comment]
Yeah I agree we should only bump MSRV on minor releases.

The next release has to be v2.4.0 anyway because of the changes to the execution endpoint flags (and maybe some other breaking changes) that we've already merged

**Review by michaelsproul — APPROVED** [review]
Let's do it

**Pull request closed without merging**
