### PR TITLE
[Merged by Bors] - Reduce temp allocations in network metrics

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

Using `heaptrack` I could see that ~75% of Lighthouse temporary allocations are caused by temporary string allocations here.

## Proposed Changes

Reduces temporary `String` allocations when updating metrics in the `network` crate. The solution isn't perfect since we rebuild our caches with each call, but it's a significant improvement.

## Additional Info

NA

### CODE REVIEW

**Comment by paulhauner** [comment]
@blacktemplar I can see there's a few other places in here where we might be able to remove some allocations, but I don't quite have the time to grok it all at the moment. It would be great if you could help reduce the allocations here, since they have a tangible impact on our memory footprint (since Rust doesn't have a GC it suffers from fragmentation if we go crazy allocation small chunks of memory).

**Comment by paulhauner** [comment]
E.g.,

```rust
                .map_or("Unknown".to_string(), |peer_info| {
                    peer_info.client.kind.to_string()
                });
```

Using `map` + `unwrap_or_else`here instead of `map_or` will change it from allocation to the heap *only* when we don't have peer info, instead of on every run.

**Review by AgeManning — APPROVED** [review]
LGTM

**Comment by paulhauner** [comment]
bors retry

**Pull request closed without merging**
