### PR TITLE
BlockProcessing testing

### LINKED ISSUE #354: Block Processing Tests - Proposer Slashing
# Detail

Block processing lives in the `state_processing` crate, specifically in the `per_block_processing.rs` file and `per_block_processing/` dir.

Tests are implemented in the file: ... `state_processing/src/per_block_processing/tests.rs`.

The task will primarily consist of:

For each test, modify the valid block (or state?) to trigger some invalidity condition and assert that that condition was triggered by inspecting the error chain (i.e., ensure the returned Result is erroneous and the Error is correct).

## Proposer Slashing Errors

- [ ]  Invalid::MaxProposerSlashingsExceeded
-  [ ] Invalid::ProposerUnknown
- [ ] Invalid::ProposalSlotMismatch
- [ ] Invalid::ProposalsIdentical
- [ ] Invalid::ProposerAlreadySlashed
- [ ] Invalid::ProposerAlreadyWithdrawn
- [ ] Invalid::BadProposal1Signature
- [ ] Invalid::BadProposal2Signature

### LINKED ISSUE #355: Block Processing Tests - Attester Slashing
# Detail

Block processing lives in the `state_processing` crate, specifically in the `per_block_processing.rs` file and `per_block_processing/` dir.

Tests are implemented in the file: ... `state_processing/src/per_block_processing/tests.rs`.

The task will primarily consist of:

For each test, modify the valid block (or state?) to trigger some invalidity condition and assert that that condition was triggered by inspecting the error chain (i.e., ensure the returned Result is erroneous and the Error is correct).

## Attester Slashing Errors

- [ ] Invalid::MaxAttesterSlashingsExceed
- [ ] Invalid::AttestationDataIdentical
- [ ] Invalid::NotSlashable
- [ ] Invalid::SlashableAttestation1Invalid
- [ ] Invalid::SlashableAttestation2Invalid

### LINKED ISSUE #356: Block Processing Tests - Attestations
# Detail

Block processing lives in the `state_processing` crate, specifically in the `per_block_processing.rs` file and `per_block_processing/` dir.

Tests are implemented in the file: ... `state_processing/src/per_block_processing/tests.rs`.

The task will primarily consist of:

For each test, modify the valid block (or state?) to trigger some invalidity condition and assert that that condition was triggered by inspecting the error chain (i.e., ensure the returned Result is erroneous and the Error is correct).

## Attestation Errors

- [ ] Invalid::MaxAttestationsExceeded

_validate_attestation_
- [ ] Invalid::PreGenesis
- [ ] Invalid::IncludedTooLate
- [ ] Invalid::IncludedTooEarly
- [ ] Invalid::BadPreviousCrosslink
- [ ] Invalid::AggregationBitfieldIsEmpty
- [ ] Invalid::CustodyBitfieldHasSetBits
- [ ] Invalid::NoCommitteeForShard
- [ ] Invalid::BadCustodyBitfieldLength
- [ ] Invalid::BadAggregationBitfieldLength
- [ ] Invalid::ShardBlockRootNotZero

_verify_justified_epoch_and_root_
- [ ] Invalid::WrongJustifiedEpoch (current)
- [ ] Invalid::WrongJustifiedRoot (current)
- [ ] Invalid::WrongJustifiedEpoch (previous)
- [ ] Invalid::WrongJustifiedRoot (previous)

_verify_attestation_signature_
- [ ] Invalid::BadAggregationBitfieldLength
- [ ] Invalid::BadCustodyBitfieldLength  
- [ ] BeaconStateError::UnknownValidator
- [ ] Invalid::BadSignature

### LINKED ISSUE #357: Block Processing Tests - Deposits
# Detail

Block processing lives in the `state_processing` crate, specifically in the `per_block_processing.rs` file and `per_block_processing/` dir.

Tests are implemented in the file: ... `state_processing/src/per_block_processing/tests.rs`.

The task will primarily consist of:

For each test, modify the valid block (or state?) to trigger some invalidity condition and assert that that condition was triggered by inspecting the error chain (i.e., ensure the returned Result is erroneous and the Error is correct).

## Deposits Errors

- [ ] Invalid::MaxDepositsExceeded

_verify_deposit_
- [ ] Invalid::BadProofOfPossession
- [ ] Invalid::BadMerkleProof

_verify_deposit_index_
- [ ] Invalid::BadIndex

### LINKED ISSUE #358: Block Processing Tests - Exits
# Detail

Block processing lives in the `state_processing` crate, specifically in the `per_block_processing.rs` file and `per_block_processing/` dir.

Tests are implemented in the file: ... `state_processing/src/per_block_processing/tests.rs`.

The task will primarily consist of:

For each test, modify the valid block (or state?) to trigger some invalidity condition and assert that that condition was triggered by inspecting the error chain (i.e., ensure the returned Result is erroneous and the Error is correct).

## Exits Errors

- [ ] Invalid::MaxExitsExceeded

_verify_exit_
- [ ] Invalid::ValidatorUnknown
- [ ] Invalid::AlreadyExited
- [ ] Invalid::AlreadyInitiatedExited
- [ ] Invalid::FutureEpoch
- [ ] Invalid::TooYoungToLeave
- [ ] Invalid::BadSignature

### LINKED ISSUE #359: Block Processing Tests - Transfers
# Detail

Block processing lives in the `state_processing` crate, specifically in the `per_block_processing.rs` file and `per_block_processing/` dir.

Tests are implemented in the file: ... `state_processing/src/per_block_processing/tests.rs`.

The task will primarily consist of:

For each test, modify the valid block (or state?) to trigger some invalidity condition and assert that that condition was triggered by inspecting the error chain (i.e., ensure the returned Result is erroneous and the Error is correct).

## Transfer Errors

- [ ] Invalid::MaxTransfersExceed

_verify_transfer_
- [ ] Invalid::FromValidatorUnknown
- [ ] Invalid::FeeOverflow
- [ ] Invalid::FromBalanceInsufficient (amount)
- [ ] Invalid::FromBalanceInsufficient (fee)
- [ ] Invalid::InvalidResultingFromBalance
- [ ] Invalid::TransferSlotInPast
- [ ] Invalid::StateSlotMismatch
- [ ] Invalid::FromValidatorUnknown
- [ ] Invalid::FromValidatorIneligableForTransfer
- [ ] Invalid::WithdrawalCredentialsMismatch
- [ ] Invalid::BadSignature

### PR DESCRIPTION
**Pull request by pscott**
## Issue Addressed

Closes #354 , closes #355 , closes #356 , closes #357 , closes #358 , closes #359 

## Additional Info

Decided to merge every branch I had created for each individual issues into one big PR, as originally proposed by #323 .

Removed all tests trying to insert MaxOperations + 1 per block, as they were really long, and added about 1-2 minutes of testing on my computer.

### Deposits
- [x] Valid: Insert multiple valid deposits
- [x] Invalid: Insert block and increment deposit_count
- [x] Invalid: Insert block and decrement deposit_count
- [x] Invalid: Insert block with incorrect merkle proof
- [x] Invalid: Insert block with incorrect public key
- [x] Invalid: Insert block with incorrect block signature
- [x] Invalid: Insert block with invalid public key (i.e. not a valid BLS point)

#### Additional Info

- Removed `BadIndex` enum variant for `DepositInvalid` as it was never called.
- Side note: small optimization, we're verifying the public key twice, when doing it once should be enough : first time is here https://github.com/sigp/lighthouse/blob/2399b9bbe0e521fa092fef8bcf592b7b82f7ce3f/eth2/state_processing/src/per_block_processing.rs#L430 and the second time just afterwards here https://github.com/sigp/lighthouse/blob/2399b9bbe0e521fa092fef8bcf592b7b82f7ce3f/eth2/state_processing/src/per_block_processing.rs#L447 .

---

### Exits

- [x] Valid: Insert n deposits
- [x] Invalid: Validator Unknown
- [x] Invalid: Already Exited
- [x] Invalid: Already Initiated
- [x] Invalid: Future Epoch
- [x] Invalid: TooYoungToLeave
- [x] Invalid: Not Active
- [x] Invalid: BadSignature

---

### Attestations
- [x] Valid: Insert Attestations
- [x] Invalid: BadParentCrossLinkStartEpoch
- [x] Invalid: BadParentCrossLinkEndEpoch
- [x] Invalid: NoCommitteeForShard
- [x] Invalid: BadParentCrossLinkDataRoot
- [x] Invalid: BadTargetTooLow
- [x] Invalid: BadTargetTooHigh
- [x] Invalid: WrongJustifiedCheckpoint
- [x] Invalid: BadIndexedAttestation(BadSignature)
- [x] Invalid: BadShard
- [x] Invalid: IncludedTooEarly
- [x] Invalid: IncludedTooLate (see additional info)
- [x] Invalid: BadTargetEpoch (see additional info)
- [x] Invalid: CustodyBitfieldHasSetBits
- [x] Invalid: BadCustodyBitfieldLength (see additional info)
- [x] Invalid: BadAggregationBitfieldLength (see additional info)
- [x] Invalid: CustodyBitfieldNotSubset
- [x] Invalid: BadSignature

#### Additional Info
- BadCustodyBitfieldLength is not called in the code, I nevertheless added a test `invalid_attestation_bad_custody_bitfield_len` (the error returned is `BeaconStateError::InvalidBitfield`)
- BadAggregationBitfieldLength is not called in the code, I nevertheless added a test `invalid_attestation_bad_aggregation_bitfield_len` (the error returned is `BeaconStateError::InvalidBitfield`)
- I've removed the `UnknownValidator` variant in the enum as it is never returned.

-> Need help / ideas / reviews:
- `BadTargetEpoch` is hard to reach : if target epoch is too low, we trigger `BadTargetTooLow`. If it is too high, we trigger `NoCommitteeForShard`, or `EpochTooHigh`.
- `IncludedTooLate` triggers `NoCommitteeForShard` even with 2048 validators, because we are setting the target epoch to be earlier than the current epoch.

---

### AttesterSlashings

- [x] Valid: Insert valid attester slashing 
- [x] Invalid: NotSlashable
- [x] Invalid: IndexedAttestation1Invalid
- [x] Invalid: IndexedAttestation1Invalid

#### Additional Info
- Removed `AttestationDataIdentical` enum variant as it was never called in the code.

---

### ProposerSlashings

- [x] Valid: Insert proposer slashing
- [x] Invalid: ProposerUnknown
- [x] Invalid: ProposalsIdentical
- [x] Invalid: ProposalEpochMismatch
- [x] Invalid: ProposerNotSlashable
- [x] Invalid: BadProposal1Signature
- [x] Invalid: BadProposal2Signature

### CODE REVIEW

**Comment by paulhauner** [comment]
This looks like an awesome effort, thank you!

Could you please confirm this is ready for review? If so, I'll review mid-late next week (I'm still traveling sorry). I think @michaelsproul was keen to have a peek too.

**Comment by pscott** [comment]
@paulhauner Yup, everything should be good to go. 

@paulhauner @michaelsproul Please let me know what needs to be changed / what I could've done better, as I'm still learning (and have a lot to learn from you guys!!). I'd also like to point out the `BadTargetEpoch` and `IncludedTooLate` tests (see original PR post). They're not getting properly tested.

**Comment by paulhauner** [comment]
I just triggered CI :)

**Comment by pscott** [comment]
Fixed cargo fmt as my rustfmt was not up to date when I ran cargo fmt before creating this PR.
Re: test failures -> the failing test for both `test_dev` and `test_release` are coming from `signatures_minimal::deposit`.
However here's what's for the test: https://github.com/pscott/lighthouse/blob/8bc94297c2b244f47dd919605b8a47a5080bbf3b/eth2/state_processing/tests/tests.rs#L178-L191

It's explicitly a TODO for failing the test. Should I do anything about it? Not sure what to do here. Thanks!

**Comment by paulhauner** [comment]
> There's an explicit TODO for fixing the test. Should I do anything about it? Not sure what to do here. Thanks!

Oh, so it looks like we expect that test to panic (`#[should_panic]`), but it's not panic-ing! So, I would guess that we have indirectly fixed that test.

I would remove the `// TODO` and the `#[should_panic]` and count this one as a win :)

It looks like there's another `cargofmt` fail in there too, sorry.

**Comment by pscott** [comment]
Updated rustfmt and ran it again.
Found out where the deposit test bug was coming from! Fixed it (it should indeed panic, but I had previously modified the `insert_deposits` method, it is now fixed).
Had to merge conflicts in cargo.toml, I kept everything on master and simply added the dependency to `merkle_proof` that was needed for generating proofs for the tests.

**Comment by paulhauner** [comment]
CI triggered :)

**Comment by paulhauner** [comment]
It failed CI, sorry :(

Seems to be related to deposits.

**Comment by pscott** [comment]
Argh! Adapted previous change to work with all test cases. Ran tests on my computer and cargo fmt, this push should be the last! :)

**Comment by paulhauner** [comment]
CI triggered :)

**Pull request merged**
