### PR TITLE
Starting up from in a weak subjectivity period

### PR DESCRIPTION
**Pull request by adaszko**
Syncing won't proceed.  The weakly subjective block's parent is rejected as unknown:
`Aug 18 12:13:51.931 INFO Starting from a weak subjectivity point, parent: 0x0f3a…6075, block: 0x09d5…eb36, service: beacon`
`Aug 18 12:16:17.034 DEBG Batch processing failed                 error: Block has an unknown parent: 0x09d5…eb36, id: 1, service: sync`

### CODE REVIEW

**Comment by adaszko** [comment]
Somewhat as expected, I'm getting [`Aug 17 09:29:48.234 ERRO Block in the chain is not in the store  request_root: 0x0bd8…c4e5`](https://github.com/sigp/lighthouse/blob/114a0457a4f088f35260c69288cc489fc0c340ce/beacon_node/network/src/router/processor.rs#L415) errors now.

**Comment by adaszko** [comment]
Prior to the error above, I'm getting `Aug 17 10:24:32.823 WARN Batch failed to download. Dropping chain scoring peers, id: 1, chain_id: 15300288226967156199, score_adjustment: Low Tolerance Error, service: sync` which is caused by

```
Aug 17 10:24:32.705 DEBG Processing batch                        end_slot: 71680, start_slot: 71617, blocks: 48, id: 1, service: sync
Aug 17 10:24:32.813 DEBG Batch processing failed                 error: Block has an unknown parent: 0xc610…b9f9, id: 1, service: sync
Aug 17 10:24:32.823 DEBG Batch processing failed                 client: Lighthouse: version: v0.2.3-c75c06cf, os_version: x86_64-linux, peer: 16Uiu2HAmHqM4TrijBEy8VJfXDNEdF63nbhY7adqqJUJXwacFpFYV, id: 1, chain_id:
15300288226967156199, service: sync
```

**Comment by adaszko** [comment]
Syncing won't proceed.  The weakly subjective block's parent is rejected as unknown:
`Aug 18 12:13:51.931 INFO Starting from a weak subjectivity point, parent: 0x0f3a…6075, block: 0x09d5…eb36, service: beacon`
`Aug 18 12:16:17.034 DEBG Batch processing failed                 error: Block has an unknown parent: 0x09d5…eb36, id: 1, service: sync`

**Comment by paulhauner** [comment]
Closing this in favor of #1692, so this lingering PR doesn't clutter @adaszko's Github. I hope you're enjoying the new job! :)

**Pull request closed without merging**
