### PR TITLE
Remove unused js file in Lighthouse book

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

Remove unused js file in Lighthouse book.

The usage of this deposit file was removed in #1742, and is no longer used anywhere in the Lighthouse book.

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Wowee, that's an old one!

**Comment by michaelsproul** [comment]
@mergifyio queue

**Comment by michaelsproul** [comment]
@mergifyio dequeue

**Comment by realbigsean** [comment]
@Mergifyio requeue

**Comment by realbigsean** [comment]
@mergifyio requeue

**Pull request merged**
