### PR TITLE
[Merged by Bors] - Fix Block Cache Range Math for Faster Syncing

### PR DESCRIPTION
**Pull request by ethDreamer**
## Issue Addressed

While messing with the deposit snapshot stuff, I had my proxy running and noticed the beacon node wasn't syncing the block cache continuously. There were long periods where it did nothing. I believe this was caused by a logical error introduced in #3234 that dealt with an issue that arose while syncing the block cache on Ropsten.

The problem is that when the block cache is initially syncing, it will trigger the logic that detects the cache is far behind the execution chain in time. This will trigger a batch syncing mechanism which is intended to sync further ahead than the chain would normally. But the batch syncing is actually slower than the range this function usually estimates (in this scenario).

## Proposed Changes

I believe I've fixed this function by taking the end of the range to be the maximum of (batch syncing range, usual range).
I've also renamed and restructured some things a bit. It's equivalent logic but I think it's more clear what's going on.

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
It took me a moment to remember how this works, but I think your fix is correct!

LGTM

**Comment by michaelsproul** [comment]
I've tagged this v2.5.0 so we can test and review it a bit more before shipping it

**Comment by paulhauner** [comment]
Is this one waiting for more review or good to merge?

**Comment by michaelsproul** [comment]
Let's merge it. It can run on our infra as part of the v2.5.0 release cycle

**Pull request closed without merging**
