### PR TITLE
[Merged by Bors] - Fix some dead links in markdown files

### PR DESCRIPTION
**Pull request by aliask**
## Issue Addressed

No issue has been raised for these broken links.

## Proposed Changes

Update links with the new URLs for the same document.

## Additional Info

~The link for the [Lighthouse Development Updates](https://eepurl.com/dh9Lvb/) mailing list is also broken, but I can't find the correct link.~

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Very nice, thank you! I've checked all the links and previous links were dead and the new ones work 🚀

**Comment by paulhauner** [comment]
I just added a new-line and then removed it so that Github CI will realise that the target branch has been changed from `stable` to `unstable` :)

**Comment by michaelsproul** [comment]
@gitpoap-bot @aliask :tada:

**Pull request closed without merging**
