### PR TITLE
[Merged by Bors] - v2.1.3

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions

## Additional Info

NA

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
LGTM, let's ship this

**Comment by paulhauner** [comment]
bors retry

**Review by rsalvo77 — COMMENTED** [review]
`

**Review by rsalvo77 — COMMENTED** [review]
>

**Review by rsalvo77 — COMMENTED** [review]
:)

**Pull request closed without merging**
