### PR TITLE
Pin rust_eth_kzg to 0.5.1

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Temporarily pin `rust_eth_kzg` to 0.5.1 as 0.5.2 seems to have regressed some loading performance enough for our CI to start timing out in the simulator tests (32s timeout). See:

- https://github.com/sigp/lighthouse/pull/6607

### CODE REVIEW

**Comment by michaelsproul** [comment]
Benchmarks for `kzg` crate for 0.5.2:

```
Initialize context rust_eth_kzg
                        time:   [3.8753 s 3.8973 s 3.9200 s]

Benchmarking Initialize context c-kzg (4844): Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.3s, or reduce sample count to 90.
Initialize context c-kzg (4844)
                        time:   [53.268 ms 53.289 ms 53.310 ms]
Found 11 outliers among 100 measurements (11.00%)
  6 (6.00%) high mild
  5 (5.00%) high severe
```

**Comment by michaelsproul** [comment]
Context initialisation is 33% faster with 0.5.1:

```
Initialize context rust_eth_kzg
                        time:   [2.6043 s 2.6138 s 2.6226 s]
                        change: [-33.399% -32.932% -32.494%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 30 outliers among 100 measurements (30.00%)
  21 (21.00%) low severe
  1 (1.00%) low mild
  7 (7.00%) high mild
  1 (1.00%) high severe

Benchmarking Initialize context c-kzg (4844): Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.4s, or reduce sample count to 90.
Initialize context c-kzg (4844)
                        time:   [55.333 ms 55.380 ms 55.429 ms]
                        change: [+3.8292% +3.9248% +4.0237%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
```

**Review by jxs — APPROVED** [review]
LGTM

**Comment by michaelsproul** [comment]
@mergify queue

**Comment by michaelsproul** [comment]
@mergify requeue

**Comment by michaelsproul** [comment]
@mergify requeue

**Pull request merged**
