### PR TITLE
Explicit peers

### LINKED ISSUE #5268: Explicit Peering Agreement implementation
### Context

Lighthouse implements the concept of a “trusted”/”static” peer, which guarantees the ability to always remain connected to a peer ignoring defensive measures such as peer scoring, however it provides no guarantees of being part of their mesh or to send/receive full messages from them unconditionally.

### Why explicit peering agreement

[Gossipsub v1.1 introduces the concept of "Explicit Peering Agreement"](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#explicit-peering-agreements), which is an agreement that must be reached from a pair of nodes in order to *“remain connected to and unconditionally forward messages to each other outside of the vagaries of the peer scoring system and other defensive measures”.*

This feature if enabled in Lighthouse could allow nodes to explicitly connect to some relays networks such as Fiber or Bloxroute to boost the propagation of their blocks.

### Possible implementation

In order to do that, we could simply mimic what has been done for trusted/static peers. In particular:

- set them from the command line
- allow them to be added and removed dynamically
- exclude them from peer scoring or other defensive measures

Lastly this list of nodes needs to be passed to the libp2p implementation.

If there is interest, we can open a PR that implements this functionality.

### PR DESCRIPTION
**Pull request by mempirate**
## Issue Addressed

Closes #5268

## Proposed Changes

This PR implements explicit peering agreements (https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#explicit-peering-agreements). It was decided not to add a separate `--explicit-peers` flag, but instead instantiate trusted peers as explicit. This means that when a trusted peer is defined, it will have the following properties:
- exempt from peer scoring
- automatic reconnects
- unconditional forwarding of all messages

### CODE REVIEW

**Comment by AgeManning** [comment]
@mempirate - Thanks for the PR. 

You've caught us at a time where we are actively going through and removing old/deprecated and non-critical CLI flags, as we've had a few complaints of there being too many. 

How do you feel about just using the trusted-peers CLI flag. i.e all trusted peers become explicit peers on the gossipsub level. I think this what should have been implemented when we added the trusted-peers flag.

**Comment by mempirate** [comment]
@AgeManning I think that also makes sense as an approach! Agreed that there's a lot of overlapping functionality.

Done in following commit.

**Review by AgeManning — APPROVED** [review]
Nice thanks for the addition!

Also, in the future, we can always change the base of the PR, no need to make a new one :) 

(I know this, because I accidentally do it all the time :sweat_smile: )

**Review by pawanjay176 — APPROVED** [review]

**Comment by pawanjay176** [comment]
@Mergifyio queue

**Comment by pawanjay176** [comment]
@Mergifyio queue

**Comment by paulhauner** [comment]
@mergifyio queue

**Pull request merged**
