### PR TITLE
Rename `Merge` to `Bellatrix`

### PR DESCRIPTION
**Pull request by macladson**
## Proposed Changes

Rename various references to "The Merge" to reference the Bellatrix hard fork instead.
This mainly covers enum/superstruct variants such as `ForkName::Merge` and `BeaconBlockMerge` which are now `ForkName::Bellatrix` and `BeaconBlockBellatrix` respectively.
Other changes include updates to functions, variable names and comments. 

## Additional Info

Not all references to "Merge" have been changed, but the codebase now skews towards referencing "Bellatrix".

Certain references to "The Merge" have been kept, such as any references to `merge_transition` or `merge_block` as these are [present and distinct in the spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/bellatrix/fork-choice.md#validate_merge_block). Related functions and variable names have also been kept.

This also doesn't update the `lighthouse/merge_readiness` endpoint as this would be a breaking change. I'd also be in favour of removing this endpoint entirely.

### CODE REVIEW

**Review by dapplion — APPROVED** [review]
No xz backdoor either! LGTM

**Review by pawanjay176 — APPROVED** [review]

**Comment by pawanjay176** [comment]
This would be a big conflict in existing feature PRs, so we should either rip of the bandaid and merge this asap or do it after we get all feature PRs in to unstable.
I vote for merging this ASAP

**Comment by macladson** [comment]
Yeah this is one of those things where there is never a "good" time to do it. It'll conflict with a lot of stuff now, but if we choose to wait, then it'll conflict even more with PeerDAS, Verkle and whatever else is coming in the future.

Also, I'm happy to assist in fixing conflicts on your/anyone's PRs, just ping me :grin:

**Comment by realbigsean** [comment]
@mergify queue

**Comment by realbigsean** [comment]
@mergify requeue

**Comment by realbigsean** [comment]
@mergify requeue

**Pull request merged**
