### PR TITLE
simplify rpc codec logic

### PR DESCRIPTION
**Pull request by jxs**
## Issue Addressed

Simplifies Rpc's codec logic by removing `BaseInboundCodec`, `InboundCodec`, `BaseOutboundCodec` and `Outbound` codec.

### CODE REVIEW

**Review by ackintosh — APPROVED** [review]
Looks good to me!

**Review by AgeManning — APPROVED** [review]
Yep, this looks like a good merge to me, I doub't we're adding any more kinds of encodings in the near future. 

We should run this on a testnet to make sure everything works. If there is a mistake here, it should be easily found.

**Review by pawanjay176 — APPROVED** [review]
LGTM. +1 on running this on mainnet to double check everything is working as expected

**Comment by jxs** [comment]
@mergifyio queue

**Comment by jxs** [comment]
@mergifyio queue

**Pull request merged**
