### PR TITLE
Altair devnets

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Replaces #2434 and provides the following `--network` flags:

- `altair-devnet-0`
- `altair-devnet-1`

## Additional Info

Not intended to be merged.

### CODE REVIEW

**Comment by michaelsproul** [comment]
I'm going to try cherry-picking the tree hash changes (#2459) to this branch, and if all goes well will push them here.

**Comment by michaelsproul** [comment]
I've rebased this PR on `altair-vc`, which is now built on `network-altair` and incorporates the latest changes from `unstable` :sweat_smile:

**Comment by michaelsproul** [comment]
This branch is now running (smoothly) on the devnet-0 nodes. I also synced a new devnet-0 node from scratch without issue.

**Comment by michaelsproul** [comment]
Rebased on `altair-vc` and the latest `unstable`, commit  56a5e04 is running well on the devnet:

https://altair-devnet-1-explorer.ethdevops.io/blocks?q=Lighthouse

**Comment by michaelsproul** [comment]
Updated for latest `altair-vc`: https://github.com/sigp/lighthouse/pull/2404#issuecomment-886495858

**Comment by michaelsproul** [comment]
Updated for latest `unstable`. This PR now contains mostly `devnet`-related changes (plus the discv5 bump). It's running on altair-devnet-1 now (40e5b23579b596c56a9f82240ef73d1f773a63b7)

**Comment by paulhauner** [comment]
I've just force-pushed to achieve:

- Rebase onto latest `unstable` (https://github.com/sigp/lighthouse/commit/6a620a31dacb8e4b907ac16568dd9bb234223671)
- Include #2489 (to give it some testing with altair devents)
- Include #2404 (it was already included in this branch)
- Include #2493 to help troubleshoot a rare panic from a bug in upstream libp2p.

If you're starting a new testnet, make sure to use the latest version of this branch. If you're already running a testnet, upgrading to this branch is not mandatory (but worthwhile if you want to help us test #2493).

**Comment by paulhauner** [comment]
I've just force-pushed to achieve:

- Rebase onto latest `unstable` (https://github.com/sigp/lighthouse/commit/6a620a31dacb8e4b907ac16568dd9bb234223671)
- Include #2489 (to give it some testing with altair devents)
- Include #2404 (it was already included in this branch)
- Include #2493 to help troubleshoot a rare panic from a bug in upstream libp2p.

If you're starting a new testnet, make sure to use the latest version of this branch. If you're already running a testnet, upgrading to this branch is not mandatory (but worthwhile if you want to help us test #2493).

**Comment by paulhauner** [comment]
I just force-pushed because a few PRs have been merged into unstable. This is now rebased on unstable @ ff85b052496860dede3d99b483533f0b4a963ef4.

Advice for upgrading remains the same:

> If you're starting a new testnet, make sure to use the latest version of this branch. If you're already running a testnet, upgrading to this branch is not mandatory (but worthwhile if you want to help us test #2493).

**Comment by paulhauner** [comment]
I've just rebased this onto https://github.com/sigp/lighthouse/pull/2506 (09a33f875b9956b6a38c799f0bec21468a44f2b9). It will now have the `v1.5.0-rc.0` version tag.

Advice for upgrading remains the same:

> If you're starting a new testnet, make sure to use the latest version of this branch. If you're already running a testnet, upgrading to this branch is not mandatory.

**Comment by paulhauner** [comment]
I'm closing this since all these networks have been deprecated.

**Pull request closed without merging**
