### PR TITLE
Remaining helper bouquet

### PR DESCRIPTION
**Pull request by ralexstokes**
## Issue Addressed

Addresses #147.

## Proposed Changes

Remainder of the helpers listed in that issue.

### CODE REVIEW

**Comment by ralexstokes** [comment]
i'll add some tests and then can un-WIP it

**Comment by ralexstokes** [comment]
ready for review!

**Comment by paulhauner** [comment]
This is great, thank you!

I have actually been stealing this code over on #163 to push through some bench-marking. I've implemented all of these functions and used them in successful slot/epoch transitions. During the process I've learned some lessons about ergonomics and developed an error-handling structure which would be modifications to this. However, your tests are valuable and some implementations are cleaner that what I have.

 As I know your time is limited here @ralexstokes, instead of requesting changes here I'm going to merge them onto my branch (#163) and deal with it there. Your commits will end up in master, just via another branch.

I hope this is ok with you, please let me know if you have any questions/concerns/input :)

**Comment by ralexstokes** [comment]
@paulhauner yeah, whatever you think is best works for me :) sorry if i duplicated some work somehow!

feel free to grab what is helpful to you and chunk the rest -- you can even just go ahead and close these PRs (referring to this #178 and #148) as you see fit

**Comment by ralexstokes** [comment]
> Oh also, you updated all the "epoch as first class citizen" stuff too :)

i did what i needed to so that the helpers tracked `The January ReleaseTM` (i think.... they were a few commits behind that tag but they seem in sync) so be on the look out for other places in the codebase where we move slot -> epoch and i didn't touch them across these helpers

**Comment by paulhauner** [comment]
I'm going to close this, there's a spec v0.2.0 so I'm implementing that now.

**Pull request closed without merging**
