### PR TITLE
chore: add `recover_cells_and_compute_proofs` method

### PR DESCRIPTION
**Pull request by kevaundray**
## Issue Addressed

This PR makes the KZG API stricter. Instead of exposing recover_cells, and cells_to_blob, we have a method which recovers the cells and computes the proofs.

## Proposed Changes

Please list or describe the changes introduced by this PR.

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

### CODE REVIEW

**Comment by kevaundray** [comment]
Note: this change is also reflected in the consensus-specs: https://github.com/ethereum/consensus-specs/blob/dev/specs/_features/eip7594/polynomial-commitments-sampling.md#recover_cells_and_kzg_proofs

**Review by jimmygchen — APPROVED** [review]
Looks good, thanks @kevaundray!
I've merged latest `das` into your branch and re-triggered CI.

**Review by dapplion — APPROVED** [review]
@kevaundray swap it sir

**Comment by jimmygchen** [comment]
I snuck in a little change in https://github.com/sigp/lighthouse/pull/5938/commits/d857d739536623825f171c1f7cdfd014e9c69af4 to address lint issue (type complexity) and merged latest `das` branch in to fix CI.

**Pull request merged**
