### PR TITLE
Faster BLS Verification

### PR DESCRIPTION
**Pull request by kirk-baird**
## Issue Addressed

N/a this is a general optimisation.

## Proposed Changes

Switch the branch of [sigp/milagro_bls](https://github.com/sigp/milagro_bls/pull/13) to one with new optimisations.

## Additional Info

This should be updated in the future to refer to point to a specific tag rather than to a branch when the above PR is merged.

### CODE REVIEW

**Comment by paulhauner** [comment]
I've added a couple of minor comments the `milagro_bls` PR.

**Comment by paulhauner** [comment]
Hey, would you mind resolving the conflict please?

Also, does this branch enforce 32-byte private keys? Or is that a later one?

**Comment by paulhauner** [comment]
Hey, would you mind resolving the conflict please?

Also, does this branch enforce 32-byte private keys? Or is that a later one?

**Comment by kirk-baird** [comment]
I've updated the Cargo.toml such that we just needed version bum. The work was done in [sigp/milagro_bls](https://github.com/sigp/milagro_bls/pull/13).

**Pull request merged**
