### PR TITLE
[Merged by Bors] - Update dependencies

### PR DESCRIPTION
**Pull request by blacktemplar**
## Issue Addressed

Partially addresses dependencies mentioned in issue #1712.

## Proposed Changes

Updates dependencies (including an update avoiding a vulnerability) + add tokio compatibility to `remote_signer_test`

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]
We don't need our hyper here because 13.8 has done the necessary updates for us right?

**Comment by michaelsproul** [comment]
This closes https://github.com/sigp/lighthouse/issues/2086, so I'm going to merge it as highest prio.

bors r+

**Comment by michaelsproul** [comment]
DHT test failed

bors retry

**Comment by blacktemplar** [comment]
> We don't need our hyper here because 13.8 has done the necessary updates for us right?

I don't think it was needed at all. The remote signer was the only crate using the fork and all the others already use upstream. At least it compiles and all tests run through, but this is the reason why I requested a review from @hermanjunge. Maybe he knows more why the fork dependency was needed.

**Pull request closed without merging**
