### PR TITLE
[Merged by Bors] - Bump version to v0.3.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

- Bump version to v0.3.0
- Run `cargo update`

## Additional Info

NA

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]
LGTM

**Comment by paulhauner** [comment]
bors r-

Going to batch with #1743

**Comment by michaelsproul** [comment]
Batching with #1750

bors r+

**Pull request closed without merging**
