### PR TITLE
Release v5.0.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions

## Additional Info

NA

### CODE REVIEW

**Comment by paulhauner** [comment]
Rebased to recognise #4832 being merged into `unstable`.

**Comment by paulhauner** [comment]
Rebased to remove #5082, it has been bumped to a future version.

**Comment by paulhauner** [comment]
Rebased onto latest `unstable`.

**Review by michaelsproul — APPROVED** [review]
LFG!

**Comment by paulhauner** [comment]
@mergifyio queue

**Review by DyroxOne — COMMENTED** [review]
pk

**Pull request merged**
