### PR TITLE
[Merged by Bors] - Update direct libsecp256k1 dependencies

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

* Remove direct dependencies on vulnerable `libsecp256k1 0.3.5`
* Ignore the RUSTSEC issue until it is resolved in #2389

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Looks good to me! We've looked into the secp256k1 and it's not a problem for us.

**Comment by michaelsproul** [comment]
bots r+

**Comment by michaelsproul** [comment]
oops

bors r+

**Pull request closed without merging**
