### PR TITLE
[Merged by Bors] - upgrade libp2p

### PR DESCRIPTION
**Pull request by divagant-martian**
## Issue Addressed

Upgrades libp2p to v.0.42.0 pre release (https://github.com/libp2p/rust-libp2p/pull/2440)

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]
LGTM

**Comment by mxinden** [comment]
> Build failed:
> 
>     * [cargo-audit](https://github.com/sigp/lighthouse/runs/5087099752?check_suite_focus=true)

Unless you are using `PeerRecord`s, the libp2p failure is not relevant for you.

https://rustsec.org/advisories/RUSTSEC-2022-0009

**Pull request closed without merging**
