### PR TITLE
[Merged by Bors] - Change type of extra fields in ConfigAndPreset

### PR DESCRIPTION
**Pull request by eklm**
## Issue Addressed

#2900

## Proposed Changes

Change type of extra_fields in ConfigAndPreset so it can contain non string values (inside serde_json::Value)

### CODE REVIEW

**Comment by eklm** [comment]
> Some investigation to ensure that we only ever use the ConfigAndPreset with JSON decoders would also be prudent (I think we do).

I think it should work even if it's used with non-json decoder. There is a unit test with yaml serialization and deserialization of ConfigAndPreset which works fine.

**Review by michaelsproul — CHANGES_REQUESTED** [review]
Awesome, thanks!

Do you mind adding an extra test in `config_and_preset`, or modifying `extra_fields_round_trip` to showcase the behaviour? A `null` value and a `Value::Number` would be great

**Comment by eklm** [comment]
Added. Also would it be maybe more appropriate to use json serialization in unit test instead of yaml as it is how it's serialized in real life?

**Review by michaelsproul — APPROVED** [review]
Looks good! Thank you!

I don't mind leaving the test as `serde_yaml` for now. Happy to merge as-is

**Comment by michaelsproul** [comment]
Will merge this PR after the v2.1.0 release.

**Pull request closed without merging**
