### PR TITLE
[Merged by Bors] - v2.1.4

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

- Bump version to `v2.1.4`
- Run `cargo update`

## Additional Info

I think this release should be published around the 15th of March.

Presently `blocked` for testing on our infrastructure.

### CODE REVIEW

**Comment by paulhauner** [comment]
I've just squash-merged #3081 into this PR so we get the new Kiln terminal difficulty.

**Comment by paulhauner** [comment]
> I've just squash-merged #3081 into this PR so we get the new Kiln terminal difficulty.

This has merged into `unstable`, so I've rebased and removed the squash-merge mentioned here.

**Review by michaelsproul — APPROVED** [review]

**Comment by paulhauner** [comment]
I've just rebased on `unstable` to include #3080 and #3074.

**Comment by paulhauner** [comment]
I've just rebased onto `unstable` since #3086 has been merged.

**Comment by paulhauner** [comment]
Testing is complete, let's release!

bors r+

**Pull request closed without merging**
