### PR TITLE
Make validator-dir global

### PR DESCRIPTION
**Pull request by 0xbentang**
## Issue Addressed

https://github.com/sigp/lighthouse/issues/3768

## Proposed Changes

Make certain flags as global

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

### CODE REVIEW

**Comment by macladson** [comment]
Thanks for writing this up!
It looks like there are some linting errors, you can see these if you run `make lint` on your code.
Would you be able to fix these up?
Thanks!

**Comment by 0xbentang** [comment]
> Thanks for writing this up! It looks like there are some linting errors, you can see these if you run `make lint` on your code. Would you be able to fix these up? Thanks!

I just pulled the latest `unstabled` branch. `make lint` locally works for me now

**Comment by paulhauner** [comment]
It looks like a test has failed with:

```
---- account_manager::validator_create stdout ----
thread 'account_manager::validator_create' panicked at 'should open validator dir: DirectoryDoesNotExist("/tmp/.tmpLaolyo/0x8011779dc88d3aa4365eef25943c56bd5e152f5ed70bbd5341936b5645665466c6bd8a3d3073a7e39cf94f19a9877634")', lighthouse/tests/account_manager.rs:314:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 0xbentang** [comment]
> It looks like a test has failed with:
> 
> ```
> ---- account_manager::validator_create stdout ----
> thread 'account_manager::validator_create' panicked at 'should open validator dir: DirectoryDoesNotExist("/tmp/.tmpLaolyo/0x8011779dc88d3aa4365eef25943c56bd5e152f5ed70bbd5341936b5645665466c6bd8a3d3073a7e39cf94f19a9877634")', lighthouse/tests/account_manager.rs:314:22
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

The root cause is that clap global flag can only be defined in the very top level (i.e. `lighthouse/src/main.rs`)
It has been improved and allowed to be defined in subcommands in v3 (https://github.com/clap-rs/clap/issues/2053)
But this will require a wider refactor

**Comment by 0xbentang** [comment]
> > It looks like a test has failed with:
> > ```
> > ---- account_manager::validator_create stdout ----
> > thread 'account_manager::validator_create' panicked at 'should open validator dir: DirectoryDoesNotExist("/tmp/.tmpLaolyo/0x8011779dc88d3aa4365eef25943c56bd5e152f5ed70bbd5341936b5645665466c6bd8a3d3073a7e39cf94f19a9877634")', lighthouse/tests/account_manager.rs:314:22
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > ```
> 
> The root cause is that clap global flag can only be defined in the very top level (i.e. `lighthouse/src/main.rs`) It has been improved and allowed to be defined in subcommands in v3 ([clap-rs/clap#2053](https://github.com/clap-rs/clap/issues/2053)) But this will require a wider refactor

Should I open another PR to upgrade `clap` to version >3,<4? In version 3 there are breaking changes that require code changes irrelevant to this PR. Version 4 has even more breaking changes which I think would be too out of scope.

**Comment by dapplion** [comment]
> Should I open another PR to upgrade clap to version >3,<4? In version 3 there are breaking changes that require code changes irrelevant to this PR. Version 4 has even more breaking changes which I think would be too out of scope.

Best would be to open an issue to gather consensus on wether to bump clap or not, and close this PR until then. Trying to reduce the queue of blocked open PRs :)

**Comment by dapplion** [comment]
Closing for now after a year of inactivity. There's an ongoing effort right now to upgrade to a recent version of clap. We can revisit this issue after then

**Pull request closed without merging**
