### PR TITLE
[Merged by Bors] - Fix Rayon deadlock in test utils

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Fix a deadlock in the tests that was causing tests on tree-states to run for hours without finishing: https://github.com/sigp/lighthouse/actions/runs/6491194654/job/17628138360.

## Proposed Changes

Avoid using a Mutex under the Rayon `par_iter`. Instead, use an `AtomicUsize`. I've run the new version several times in a loop and it hasn't deadlocked (it was deadlocking consistently on tree-states).

## Additional Info

The same bug exists in unstable and tree-states, but I'm not sure why it was triggering so consistently on the tree-states branch.

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Nice!

**Comment by jimmygchen** [comment]
bors cancel

**Pull request closed without merging**
