### PR TITLE
Fix broken links in book

### LINKED ISSUE #2563: Beacon Node API link moved [Book]
## Description

On the book on https://lighthouse-book.sigmaprime.io/api-bn.html , the link to the Beacon Node API moved from https://ethereum.github.io/eth2.0-APIs/ to https://ethereum.github.io/beacon-APIs/

## Expected Behaviour

Links on the book should work and point to the proper pages.

## Steps to resolve

Update the book to use the new links.

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

Resolves #2563 

## Proposed Changes

Fixes the links to the eth2 beacon api url.

### CODE REVIEW

**Comment by michaelsproul** [comment]
This has been partly implemented previously, and Paul found some missed links. I think a few might be missing here too https://github.com/sigp/lighthouse/pull/2590#issuecomment-917735829

**Comment by pawanjay176** [comment]
Oops didn't see that we already got an external contribution for that. I'll close this one then :)

**Comment by michaelsproul** [comment]
That PR hasn't been active for 18 days so I reckon you'd be OK to hijack it (either here or by pushing to it)

**Comment by pawanjay176** [comment]
Picked @mstallmo 's commit here

**Pull request closed without merging**
