### PR TITLE
Stores test improvements

### PR DESCRIPTION
**Pull request by g-r-a-n-t**
Addresses #23

### CODE REVIEW

**Comment by paulhauner** [comment]
Are you blocking on me for a review for this @g-r-a-n-t? :)

**Comment by g-r-a-n-t** [comment]
@paulhauner No, just had a busy thanksgiving week and haven't been able to do anything with this. I plan on adding some more tests around the block_at_slot function, then it should be good. Does this sound alright?

**Comment by paulhauner** [comment]
All good @g-r-a-n-t, take your time! I just wanted to make sure I wasn't standing in your way :)

**Comment by paulhauner** [comment]
Thanks @g-r-a-n-t! I'll review this today :)

**Comment by paulhauner** [comment]
These look great, thanks @g-r-a-n-t!

I haven't checked these for completeness (i.e., all functionality is tested) as I assume we'll be expanding the functionality over the next couple of weeks and we can do so at that point.

This is a definite improvement and I'm glad to see you didn't find any bugs during testing!

Merging!

**Pull request merged**
