### PR TITLE
Add Trin Execution ClientCode

### PR DESCRIPTION
**Pull request by KolbyML**
## Issue Addressed
fixes https://github.com/sigp/lighthouse/issues/6501

I am adding the client code for Trin Execution. It was added to the `ethereum/execution-api` engine API specification in this PR https://github.com/ethereum/execution-apis/pull/590

## Proposed Changes

Added the client code `TE` for Trin Execution

### CODE REVIEW

**Comment by michaelsproul** [comment]
sorry, killed CI on this PR to debug some other issues

will re-run it in a bit

**Comment by KolbyML** [comment]
> sorry, killed CI on this PR to debug some other issues
> 
> will re-run it in a bit

Sounds good

**Review by michaelsproul — APPROVED** [review]
LGTM

Thanks!

**Comment by michaelsproul** [comment]
@mergify queue

**Pull request merged**
