### PR TITLE
Drop null_logger

### PR DESCRIPTION
**Pull request by dapplion**
## Issue Addressed

Closes https://github.com/sigp/lighthouse/issues/4499

It's best to allow test runners to turn on logs for better debugging

## Proposed Changes

Use test_logger instead of null_logger

### CODE REVIEW

**Review by pawanjay176 — APPROVED** [review]
Nice, need to import logging in web3 signer tests though

**Comment by michaelsproul** [comment]
CI still broken

**Comment by dapplion** [comment]
CI gud

**Review by michaelsproul — APPROVED** [review]
LGTM

**Comment by michaelsproul** [comment]
@mergify queue

**Pull request merged**
