### PR TITLE
chore: change `impl Into<T> for U` to `impl From<U> for T`

### PR DESCRIPTION
**Pull request by kevaundray**
## Issue Addressed

Following https://doc.rust-lang.org/std/convert/trait.From.html it is preferred to impl From over Into. There might be specific reasons to using Into in this repository, if so feel free to close the PR. 

## Proposed Changes

Please list or describe the changes introduced by this PR.

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Nice, thanks! This was just a matter of tech debt, so the cleanup is much appreciated

We can also remove the clippy exception for this:

https://github.com/sigp/lighthouse/blob/f1d88ba4b1256e084d3a2a547e0ce574b896246c/Makefile#L232

**Review by dapplion — APPROVED** [review]

**Comment by jimmygchen** [comment]
@mergify queue

**Comment by jimmygchen** [comment]
@mergify requeue

**Comment by jimmygchen** [comment]
@mergify requeue

**Comment by jimmygchen** [comment]
@mergify unqueue

**Comment by jimmygchen** [comment]
@mergify requeue

**Pull request merged**
