### PR TITLE
[Merged by Bors] - Clippy 1.67

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Clippy 1.67.0 put us on blast for the size of some of our errors, most of them written by me ( :eyes: ). This PR shrinks the size of `BeaconChainError` by dropping some extraneous info and boxing an inner error which should only occur infrequently anyway.

For the `AttestationSlashInfo` and `BlockSlashInfo` I opted to ignore the lint as they are always used in a `Result<A, Info>` where `A` is a similar size. This means they don't bloat the size of the `Result`, so it's a bit annoying for Clippy to report this as an issue.

I also chose to ignore `clippy::uninlined-format-args` because I think the benefit-to-churn ratio is too low. E.g. sometimes we have long identifiers in `format!` args and IMO the non-inlined form is easier to read:

```rust
// I prefer this...
format!(
    "{} did {} to {}",
    REALLY_LONG_CONSTANT_NAME,
    ANOTHER_REALLY_LONG_CONSTANT_NAME,
    regular_long_identifier_name
);
  
// To this
format!("{REALLY_LONG_CONSTANT_NAME} did {ANOTHER_REALLY_LONG_CONSTANT_NAME} to {regular_long_identifier_name}");
```

I tried generating an automatic diff with `cargo clippy --fix` but it came out at:

```
250 files changed, 1209 insertions(+), 1469 deletions(-)
```

Which seems like a bad idea when we'd have to back-merge it to `capella` and `eip4844` :scream:

### CODE REVIEW

**Comment by emhane** [comment]
What is your opinion on `clippy::needless-lifetimes`?

**Review by paulhauner — APPROVED** [review]
Nice, thanks! I just ran into this.

I might trigger CI now so that we can get CI passing again for Capella stuff. @emhane, perhaps we can do `needless-lifetimes` stuff in a new PR?

**Comment by paulhauner** [comment]
> For the AttestationSlashInfo and BlockSlashInfo I opted to ignore the lint as they are always used in a Result<A, Info> where A is a similar size. 

Agreed, seems sensible!

> I also chose to ignore clippy::uninlined-format-args because I think the benefit-to-churn ratio is too low.

I agree, I agree with you preference for `"{} did {} to {}"`. I think clippy is over-reaching with some of those `clippy::uninlined-format-args` lints.

**Comment by emhane** [comment]
> Nice, thanks! I just ran into this.
> 
> 
> 
> I might trigger CI now so that we can get CI passing again for Capella stuff. @emhane, perhaps we can do `needless-lifetimes` stuff in a new PR?

Or in this PR https://github.com/sigp/lighthouse/pull/3905#issue-1551954697?

**Pull request closed without merging**
