### PR TITLE
Reduce load on validator subscription channels

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

N/A

## Proposed Changes

Since we now only subscribe to a fixed number of long lived subnets per node, the `validator_index` field in `ValidatorSubscription` type is entirely inconsequential to the beacon node. 

This PR does 2 things:
1. Removes the `validator_index` field from the `ValidatorSubscription` type. This allows us to filter duplicates which can be quite a lot in high validator count setups.
2. Instead of sending each subscription from the http api to the network service in a separate message, we send it in one single message. 
I'm not completely sure at what size of the vector we'll start seeing slowness in the channel, but by filtering duplicates, we shouldn't be sending too many. 
Max length of the vector would be `max_committees_per_slot * slots_per_epoch * 2(aggregator bit) = 4096` .
Not super attached to this change, but if we send one by one, then we should probably change the `ValidatorSubscriptionMessage` to take just a single message instead of a vector for consistency.

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]
Yeah nice. Reducing messages ftw

**Review by dapplion — APPROVED** [review]
LGTM

**Comment by pawanjay176** [comment]
@michaelsproul Can we roll this in with #5305 ?

**Review by michaelsproul — APPROVED** [review]
Looks good with the `BTreeSet` tweak!

Happy to merge and continue testing on infra over the weekend

**Comment by pawanjay176** [comment]
@Mergifyio queue

**Pull request merged**
