### PR TITLE
v4.6.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions

## Additional Info

Blocked on:
- [ ] Further testing
- [ ] #5086

### CODE REVIEW

**Comment by paulhauner** [comment]
I've just pushed #5076

**Comment by paulhauner** [comment]
Rebased to reflect that #5084 and #5089 have been merged.

**Comment by michaelsproul** [comment]
@ethDreamer also just merged https://github.com/sigp/lighthouse/pull/5096

**Comment by paulhauner** [comment]
Rebased on include #5096 and to remove #5076 (it was not successful in testing).

**Comment by paulhauner** [comment]
Rebased on latest `unstable`.

**Comment by paulhauner** [comment]
Closed in favour of https://github.com/sigp/lighthouse/pull/5091 because this branch is named v4.6.0 which will conflict with the release tag.

**Pull request closed without merging**
