### PR TITLE
[Merged by Bors] - Set mmap threshold to 128KB in malloc utils

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Closes https://github.com/sigp/lighthouse/issues/2857

## Proposed Changes

Explicitly set GNU malloc's MMAP_THRESHOLD to 128KB, disabling dynamic adjustments. For rationale see the linked issue.

### CODE REVIEW

**Comment by michaelsproul** [comment]
I've tested this on a single Prater node and so far memory usage looks the same :ok_hand:

I'll roll it out to the rest of the Prater nodes tomorrow

**Comment by michaelsproul** [comment]
Memory usage on Prater seems to be the same as with v2.1.0.

Most nodes are well-behaved and unfragmented like _Sydney_ (running this PR since 01/19):
sydney

One node (_Frankfurt_) has fragmented its heap, but it was also struggling with v2.1.0. It's been running this PR since 01/21, but you can see a steady rise before that.

fra

**Review by paulhauner — APPROVED** [review]
LGTM!

**Pull request closed without merging**
