### PR TITLE
Add bors configuration

### PR DESCRIPTION
**Pull request by adaszko**

### CODE REVIEW

**Comment by michaelsproul** [comment]
bors r-

Kill it! This is a nice test run

**Comment by adaszko** [comment]
Nice throughout review!

> I agree we should use squash merges, and I have a few more items on my wish-list:
> 
> 1. It would be great if we could avoid manually naming each CI target with `name:`, and listing all of them in the `bors.toml` file. Could we try using a wildcard match like `status = ['%']`?

Done.

> 2. Given that we want to squash merge, I would also be in favour of turning off batch mode... although I can't find a configuration option to do so at the repo level (`bors single on` seems to apply per-PR)

You seem be implying there's a risk bors produces a single commit for the entire batch if we use `use_squash_merge = true`. 
 According to [the feature spec](https://bors.tech/rfcs/0349-use-a-squash-merge-in-bors.html#guide-level-explanation), this isn't so:

> All changes in each PR will be squashed together, so there is one commit **per PR**.

> 3. If we use squash commits, and particularly batched squash commits, bors will use `Co-authored-by` on all its merge commits, which seems to prevent authorship metrics being tracked fully by github (I like those green dots!). Bors commits won't show up in our totals on the [contributors graphs](https://github.com/sigp/lighthouse/graphs/contributors), and searching commits by an author like [this](https://github.com/sigp/lighthouse/commits/master?author=paulhauner) will omit their commits where they aren't the first author (all of them). See also: https://github.community/t/co-author-not-showing-up-in-contributors/2164
> 
> Point (1) should be an easy fix, I wouldn't definitely block on (2) & (3), but it would be good to see if we could do something better there

(3) is a bigger problem.  Since the underlying problem we're trying to solve is to be able to use trigger GitHub actions on a push to *any* branch in a fork, perhaps it's time to abandon bors and look for other solutions.  Accurate attribution and metrics are important.

**Comment by michaelsproul** [comment]
Oh right! I'd misunderstood how Bors' squash merges worked! It seems like we should get correct attribution on each of the squash commits, and Bors will just claim the merge commit (if necessary). Like, when we merge this PR, I think we should get:

* HEAD: Commit authored by Bors merging this PR into `master` (optional if there are no conflicts)
* HEAD~1: Commit authored by Adam that squashes #1326 and looks just like a regular squerged PR

**Comment by michaelsproul** [comment]
@adaszko Do you want to chuck `use_squash_merges = true` in the config and I'll `bors try` this PR?

**Comment by michaelsproul** [comment]
bors try

**Comment by michaelsproul** [comment]
Silly bot! We want you to squash the PRs!

bors try-

Let's see if it works on r+ (I'm ready to cancel)

bors r+

**Comment by michaelsproul** [comment]
TASTY, IT WORKED

**Comment by michaelsproul** [comment]
Let's increase the timeout from the default one hour. Our tests take about an hour to run, and with build queueing it could be longer. The bors timeout is relative to when the commit is created, so I think we could even allow 2.5-3hrs? From the docs the units seem to be seconds:

```
# Uncomment this to use a two hour timeout.
# The default is one hour.
#timeout_sec = 7200
```

**Comment by adaszko** [comment]
bors retry

**Comment by adaszko** [comment]
bors retry

**Comment by michaelsproul** [comment]
The 2hr timeout elapsed yesterday because CI was trying to test this PR at the same time as testing the squash commit. Which is annoying, but I think we can work around it by:

* Increasing the timeout to 3-4hrs, or
* Devising a mechanism to elide the regular branch testing when bors is triggered (harder)

The timeout could even go higher if we wanted? Bors is going to do "the right thing" eventually, so it taking its time isn't so bad. We could also manually cancel PR builds to expediate the process.

**Comment by michaelsproul** [comment]
@adaszko Can you revert the revert? I don't think it was related to the failure (there are no other jobs AFAIK -- all the bors tasks show the same jobs).

**Comment by michaelsproul** [comment]
Crap, I accidentally force-pushed a stale version of `master` over your PR, and now I can't update it (permission denied). I'll open a new PR just to test it, but you can resurrect this from your local/my PR and get the green dots :smile:

**Comment by michaelsproul** [comment]
Looks like #1337 is working as intended, so you should grab those changes and push them here

**Pull request closed without merging**
