### PR TITLE
[Merged by Bors] - Pass failed gossip blocks to the slasher

### LINKED ISSUE #2042: Pass GossipVerifiedBlocks to slasher
## Description

I'm not sure how I missed this, but the `GossipVerifiedBlock::new` function doesn't pass its blocks to the slasher, meaning we failed to detect the first slashing that occurred on mainnet :( Will fix ASAP.

## Version

Lighthouse v1.0.3

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Closes #2042

## Proposed Changes

Pass blocks that fail gossip verification to the slasher. Blocks that are successfully verified are not passed immediately, but will be passed as part of full block verification.

### CODE REVIEW

**Comment by michaelsproul** [comment]
Here's a sketch of how with this change, all entrypoints to block verification pass their blocks to the slasher regardless of error.

## Entrypoint `verify_block_for_gossip`

On success: goes to `process_block` flow, see below.

On failure: passed to slasher via `GossipVerifiedBlock::new`

## Entrypoint `process_block`

Could be called with any type implementing `IntoFullyVerifiedBlock`.

Each type implementing this calls `into_fully_verified_block`, which has a default implementation in terms of `into_fully_verified_block_slashable`. The default impl handles pushing blocks to the slasher, and `into_fully_verified_block_slashable` does different checks based on the receiver type, while producing slash info:

If `GossipVerifiedBlock`, gets transformed into `SignatureVerifiedBlock` via `from_gossip_verified_block_check_slashable`, which produces slash info.

If `SignedBeaconBlock`, gets transformed into `SignatureVerifiedBlock` via `SignatureVerifiedBlock::check_slashable`, which produces slash info.

If `SignatureVerifiedBlock`, does some more verification and then wraps any errors in `BlockSlashInfo::SignatureValid`.

**Review by paulhauner — APPROVED** [review]
Nice! Merge at will!

**Comment by michaelsproul** [comment]
Hmm that ENR test failed again

**Pull request closed without merging**
