### PR TITLE
Fix mdlint on dev docs

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

CI is failing on markdown linting: https://github.com/sigp/lighthouse/actions/runs/11007452166/job/30564327274

## Proposed Changes

Address the lint.

### CODE REVIEW

**Comment by michaelsproul** [comment]
Ayy looks like there's also an ICE on the Nightly compiler: https://github.com/sigp/lighthouse/actions/runs/11007990457/job/30564824955?pr=6429

We could maybe pin to an older version if it doesn't get resolved in the next Nightly.

**Comment by chong-he** [comment]
This is the new rule added that caused the CI to fail: https://github.com/DavidAnson/markdownlint/blob/main/doc/md058.md

Adding a black line fixes it, nice!

**Review by AgeManning — APPROVED** [review]

**Comment by michaelsproul** [comment]
@mergify queue

**Comment by michaelsproul** [comment]
@mergify dequeue

**Comment by michaelsproul** [comment]
Obsoleted by:

- https://github.com/sigp/lighthouse/commit/50d8375d4666e6deb9bee9cfab396ce767ef15ff

**Pull request closed without merging**
