### PR TITLE
Remove the `is_syncing` flag from `node/syncing` endpoint.

### LINKED ISSUE #2133: Extra field in the `node/syncing` endpoint
## Description

NessDan in discord pointed out that or VC doesn't work with with Teku's BN. It's because we have an additional `is_syncing` field in the `/node/syncing` endpoint response.

## Version

v1.0.6

## Present Behaviour

```
Connected to beacon node endpoint: http://localhost:5051/, version: teku/v20.12.1/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
Unable connect to beacon node error: Reqwest(reqwest::Error { kind: Decode, source: Error("missing field `is_syncing`", line: 1, column: 50) })
Connected to beacon node endpoint: http://localhost:5051/, version: teku/v20.12.1/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
Unable connect to beacon node error: Reqwest(reqwest::Error { kind: Decode, source: Error("missing field `is_syncing`", line: 1, column: 50) })
```

## Expected Behaviour

VC compatible with teku.

## Steps to resolve

Because the `/node/syncing` endpoint returns with a sync distance of 1 when we receive a block and are processing it, it might be better to use the `/node/health` endpoint and base this check on the 200 status code. I'll look into what other clients are doing.

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

Resolves  #2133 

## Proposed Changes

- Remove the `is_syncing` field
- The sync simulator and voluntary exit mechanimsm now both use a 200 status code from the `node/health` endpoint
- The VC still uses the `node/syncing` endpoint

## Additional Info

Open question: The VC uses a margin of 4 slots to determine whether a BN is synced, but the BN API server uses a margin of 8 epochs to determine if it'll serve validator endpoints. Which one should we use?

### CODE REVIEW

**Review by paulhauner — CHANGES_REQUESTED** [review]
I know we've discussed this change before @realbigsean but I've only just managed to get my head across it. I'd like to suggest a change to how we determine `sync_distance`, please let me know what you think :)

As you know, the new data structure is:

```json
{
  "data": {
    "head_slot": "1",
    "sync_distance": "1"
  }
}
```

And the previous data structure was:

```json
{
  "data": {
    "is_syncing": true,
    "head_slot": "1",
    "sync_distance": "1"
  }
}
```

In this PR, the concept of `is_syncing` is lost. It's not immediately obvious, but @AgeManning has put some effort into the `network_globals.sync_state.read().is_syncing()` value: it's designed to avoid scenarios where peers might try to convince us that we're syncing when we're not. Whilst this is not *necessarily* useful immediately, but I think it's nice to keep this information around.

As such, I propose we calculate `sync_distance` as:

```rust
let sync_distance = if network_globals.sync_state.read().is_syncing() {
  current_slot - head_slot
} else {
  0
};
```

This allows us to say `is_syncing = sync_distance > 0` and avoid changing any of the fundamental logic in our validator client (but it will require some shimming code).

My proposal would lose the ability to determine `current_slot - head_slot` when we're not syncing, but we can generally compute that on the client-side since it can read `current_slot` from its own slot clock and `head_slot` in the response. I don't think we need to be concerned about this.

I have one more question for @AgeManning, please:

In my example, should we replace the `current_slot` value on the 2nd line with the `target_slot` from [`SyncingFinalized`/`SyncingHead`](https://github.com/sigp/lighthouse/blob/f183af20e3fb44773397c9e26540703ee94ec366/beacon_node/eth2_libp2p/src/types/sync_state.rs#L9-L12)? In other words, can we use `target_slot` to determine the greatest, "trusted" head we have from our peers?

**Comment by realbigsean** [comment]
Would it be worth re-opening this issue: https://github.com/ethereum/eth2.0-APIs/issues/77 ?

> My proposal would lose the ability to determine current_slot - head_slot when we're not syncing, but we can generally compute that on the client-side since it can read current_slot from its own slot clock and head_slot in the response. I don't think we need to be concerned about this.

We would lose the ability to reliably get the "current_slot" from the beacon node though, which we use to check clock discrepancies between the BN and VC. I'm sure this is useful for other apps too.  

I would support adding the `is_syncing` flag to the spec and having it represent when the beacon node considers itself "synced" and this could be up to client team implementations, not necessarily head_slot = current_slot.  Or we could specify according to Age's implementation of `sync_state` because I'd think the scenarios it prevents aren't unique to Lighthouse.

I'm happy to implement your suggestion now though for the sake of interoperability and we can revert this PR later if there is a spec change.

**Comment by paulhauner** [comment]
As discussed, I've made a PR over at https://github.com/ethereum/eth2.0-APIs/pull/121, lets see how that goes!

**Comment by paulhauner** [comment]
FYI it looks like https://github.com/ethereum/eth2.0-APIs/pull/121 is going to go ahead :tada: 

IMO, if that PR gets merged then we should close this PR and not worry about being spec-incompatible in the meantime. I think we're yet to declare ourselves "fully compatible" with the standard API, so we have some wiggle room for the time being.

**Comment by realbigsean** [comment]
Awesome! happy to close this

**Pull request closed without merging**
