### PR TITLE
[Merged by Bors] - Disconnect from peers quicker on internet issues

### LINKED ISSUE #2146: Improve lighthouse's disconnect responsiveness
## Description

Users are reporting Lighthouse taking 5 to 15mins for Lighthouse to drop their peers once a connection drops/changes (https://github.com/sigp/lighthouse/issues/2123). 

It is known that discv5 will take at least 5m to update the ENR, but that is unrelated and addressed in a separate issue (#2131)

In current stable we ping every 30 seconds. It should take 2 failed pings to disconnect a peer and therefore I'd expect all peers to be dropped in under a minute. In #2132 I reduced the ping interval to 15 seconds so in the unstable branch I'd expect all peers to be dropped in under 30 seconds. 

This doesn't seem to be the case and should be investigated as to why peers are taking longer to drop and reconnect when connectivity drops.

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

Fixes #2146 

## Proposed Changes

Change ping timeout errors to return `LowToleranceErrors` so that we disconnect faster on internet failures/changes.

### CODE REVIEW

**Review by AgeManning — COMMENTED** [review]
Yep, nice. Pings should be low tolerance. 

I think we should make all negotiation timeouts low tolerance however

**Review by AgeManning — APPROVED** [review]

**Comment by AgeManning** [comment]
Cargo audit is now failing. We may need to update some deps.

**Comment by pawanjay176** [comment]
The issue is with the `term` crate which is [unmaintained](https://rustsec.org/advisories/RUSTSEC-2018-0015).  We don't use `term` directly but it's a requirement for `slog_term`. 

As the current maintainer of the `term` crate [noted](https://github.com/Stebalien/term/issues/93#issuecomment-631224393),
> it's "maintained" in that I'll take a look at bug reports and merge patches. But, other than that, it's mostly frozen (I won't be implementing features). 

Since it's not a vulnerability, I think we ignore the advisory for now.
cc @michaelsproul

**Comment by realbigsean** [comment]
@pawanjay176  i think unmaintained packages just result in warnings, but the failure is due to a vuln in `smallvec`, but that was fixed with an update here: https://github.com/sigp/lighthouse/pull/2152
So if you pull `unstable` and push it should pass now

**Comment by pawanjay176** [comment]
Thanks sean! @AgeManning can you try bors again?

**Pull request closed without merging**
