### PR TITLE
[Merged by Bors] - Updates to make crates publishable

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

Related to: #2259

Made an attempt at all the necessary updates here to publish the crates to crates.io. I incremented the minor versions on all the crates that have been previously published. We still might run into some issues as we try to publish because I'm not able to test this out but I think it's a good starting point.

## Proposed Changes

- Add description and license to `ssz_types` and `serde_util`
- rename `serde_util` to `eth2_serde_util`
- increment minor versions
- remove path dependencies
- remove patch dependencies 

## Additional Info
Crates published: 

- [x] `tree_hash` -- need to publish `tree_hash_derive` and `eth2_hashing` first
- [x] `eth2_ssz_types` -- need to publish `eth2_serde_util` first
- [x] `tree_hash_derive`
- [x] `eth2_ssz`
- [x] `eth2_ssz_derive`
- [x] `eth2_serde_util`
- [x] `eth2_hashing`

### CODE REVIEW

**Comment by realbigsean** [comment]
I pulled in #2465 to include the release script here in case we want to use it during the manual publishes.

After figuring out this: https://github.com/sigp/lighthouse/pull/2465#discussion_r674198513

**Comment by realbigsean** [comment]
Crate publishing went pretty smoothly!

**Comment by realbigsean** [comment]
Wow, rust 1.54.0 just dropped and requires a change in `eth2_ssz_derive` for a new lint. Some timing.

Good chance to test out this in CI!

I added the sigp github group for crates.io to the new crates (`eth2_serde_util`,`eth2_ssz_types`) by the way.

**Comment by realbigsean** [comment]
I incremented the versions on these crates because they've all had lint-related updates since I published them:
`tree_hash`
`eth2_ssz_types`
`tree_hash_derive`
`eth2_ssz`
`eth2_ssz_derive`

So if we want to merge this to `unstable`, we can test the auto-publish workflow by pushing these tags:

`tree-hash-v0.2.1`
`eth2-ssz-types-v0.1.1`
`tree-hash-derive-v0.3.1`
`eth2-ssz-v0.2.1`
`eth2-ssz-derive-v0.2.1`

**Comment by realbigsean** [comment]
Since last merging with `unstable` there have been some breaking changes in newly published dependencies so I've manually published the following versions:

`tree_hash` -> `v0.3.0`
`eth2_ssz`-> `v0.3.0`
`eth2_ssz_types` -> `v0.2.0`

I manually published these as well because there were small changes but there were no breaking changes associated with them:
`tree_hash_derive` -> `v0.3.1`
`eth2_ssz_derive` -> `v0.2.1`

General question: should these all be 1.x.x? Because lighthouse is now running in production

**Review by paulhauner — CHANGES_REQUESTED** [review]
Awesome, this will be a great contribution to Rust/Eth2 community!

I've added the `CARGO_API_TOKEN` token to the secrets, hopefully it works :crossed_fingers: 

Only one change requested from me: `common/rest_types/Cargo.toml` (empty file) has been raised from the dead and should be deleted again :pray: 

Happy to merge once that file is deleted!

**Comment by paulhauner** [comment]
I think this will also resolve #1690, since we're removing the patches!

**Review by paulhauner — APPROVED** [review]
Nice one! bors r+

**Comment by paulhauner** [comment]
Oops, forgot to newline the bors command!

bors r+

**Pull request closed without merging**
