### PR TITLE
Release v5.1.0

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

N/A

## Proposed Changes

Bump versions

### CODE REVIEW

**Comment by paulhauner** [comment]
Rebased to include https://github.com/sigp/lighthouse/pull/5333

**Comment by paulhauner** [comment]
Rebased to include #5266 and #5368.

**Comment by paulhauner** [comment]
Rebased to include #5381

**Review by michaelsproul — APPROVED** [review]
Let's goooooo

**Comment by paulhauner** [comment]
@mergifyio queue

**Pull request merged**
