### PR TITLE
Replace `lazy_static!` with `LazyLock`

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

Replace `lazy_static!` with `LazyLock`, stable from Rust 1.80.

This removes the usage of `lazy_static` crate and we no longer have to worry about macro recursion limit of `lazy_static!`.

### CODE REVIEW

**Comment by jimmygchen** [comment]
Marking this as `backward-incompat` due to updating `rust-version`.

**Comment by jimmygchen** [comment]
Moving to v5.3.1 as it requires Rust 1.80

**Review by jxs — APPROVED** [review]
LGTM Jimmy, great work! did you do all this manually? :sweat_smile:

**Comment by jimmygchen** [comment]
😅 don't ask. Would love to know if there's tools to automate this.
I did bulk regex replacement so it's not _toooo_ bad.

**Comment by jxs** [comment]
@mergifyio queue

**Pull request merged**
