### PR TITLE
[Merged by Bors] - Code quality improvents to the network service

### PR DESCRIPTION
**Pull request by divagant-martian**
Checking how to priorize the polling of the network I moved most of the service code to functions. This change I think it's worth on it's own for code quality since inside the `tokio::select` many tools don't work (cargo fmt, sometimes clippy, and sometimes even the compiler's errors get wack). This is functionally equivalent to the previous code, just better organized

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]
Yeah this looks like just code-quality improvement. We should run on our nodes to test as we're touching some core logic code here.

**Comment by divagant-martian** [comment]
running on lon

**Pull request closed without merging**
