### PR TITLE
Update deterministic subnets upgrade to allow prefix computation

### PR DESCRIPTION
**Pull request by divagant-martian**
## Issue Addressed

Implements https://github.com/ethereum/consensus-specs/pull/3545 in preparation for turning on deterministic subnet peers discovery

## Proposed Changes
Add the spec values necessary to implement the change so that peer discovery can be tackled afterwards

## Additional Info

found the :bug: and now all the test values are verified with pyspec so I'm certain calculations are correct

The `compute_subscribed_subnet` function required two changes to work: 
1. proper types for `subnet_prefix` and `shuffling_bits`
2. using parenthesis to specify the correct order of operations in python for the later (otherwise the result might not even fit in a `uint64`). 

For the record this is the code:

```python
def compute_subscribed_subnet(node_id: NodeID, epoch: Epoch, index: int) -> SubnetID:
    subnet_prefix = uint64(node_id >> (NODE_ID_BITS - config.ATTESTATION_SUBNET_PREFIX_BITS))
    shuffling_bits = uint64(node_id >> (NODE_ID_BITS - config.ATTESTATION_SUBNET_PREFIX_BITS - ATTESTATION_SUBNET_SHUFFLING_PREFIX_BITS) )% (1 << ATTESTATION_SUBNET_SHUFFLING_PREFIX_BITS)
    epoch_transition = (subnet_prefix +  (shuffling_bits * (config.EPOCHS_PER_SUBNET_SUBSCRIPTION >> ATTESTATION_SUBNET_SHUFFLING_PREFIX_BITS))) % config.EPOCHS_PER_SUBNET_SUBSCRIPTION
    permutation_seed = hash(uint_to_bytes(uint64((epoch + epoch_transition) // config.EPOCHS_PER_SUBNET_SUBSCRIPTION)))
    permutated_prefix = compute_shuffled_index(
        subnet_prefix,
        1 << config.ATTESTATION_SUBNET_PREFIX_BITS,
        permutation_seed,
    )
    return SubnetID((permutated_prefix + index) % config.ATTESTATION_SUBNET_COUNT)

```

### CODE REVIEW

**Comment by divagant-martian** [comment]
Tagging @michaelsproul since you have good eye for these things

**Review by AgeManning — APPROVED** [review]
These changes look fine to me. 

The conversion to u64's I think are fine, but if someone wants to double check it can't hurt us that might be one area to look at. 

There is edge cases for panics, but only on wild configuration settings, so i'm cool with that.

**Comment by divagant-martian** [comment]
Yes, I am assuming that the number of bits we take for subnet prefix + shuffling will never reach 64, since this would require us to store a mapping for 1.8×10¹⁹ (2^64) node id prefixes -> subnet, _per epoch of interest_ (probably at least the current and next one). 

Note that the previous code has similar assumptions, since `node_id_prefix` had to fit in a `usize` so we assume that the prefix bits are also less than 64.

I don't think these assumptions are outrageous, since they are controlled by the spec and anyone changing them to crazy values can't cause harm to other nodes but their own. 

But ofc happy to take suggestions from @michaelsproul when he gets the time

**Review by dapplion — APPROVED** [review]
Merged unstable to fix some conflicts with Dencun variables.

Logic looks good and matches https://github.com/ethereum/consensus-specs/pull/3545

Should add a check at the start `compute_subnets_for_epoch` to check that `prefix_bits + shuffling_prefix_bits < 64`?

**Comment by AgeManning** [comment]
I think we get this one in. @ackintosh has another that is dependent on this one also.

**Comment by michaelsproul** [comment]
@AgeManning gentle reminder to use mergify next time :pray:

`@Mergifyio queue` is the new `bors r+`

**Pull request merged**
