### PR TITLE
Show validator balances in prometheus metrics [Issue #2064]

### PR DESCRIPTION
**Pull request by isoosiss7**
## Issue Addressed

#2064 Add validator balance Prometheus metric

## Proposed Changes

Query the standard API for balances on startup and then once per epoch for all enabled validators. And only do this if the VC has the --metrics flag.

## Additional Info

Screen Shot 2020-12-13 at 1 50 52 PM

### CODE REVIEW

**Review by realbigsean — CHANGES_REQUESTED** [review]
Really good job, and thanks for the contribution!

There's a couple things we could do to make this a bit simpler, mostly revolving around moving this logic to the `duties_service`. It's still a bit of an awkward fit there, but from there we have access to the task executor, the beacon node client, and the `validator_store`.  In the `validator_store` the local validator's indices are available, and if we know these, we're able to batch the balance requests. Some suggestions for how it could be done:

- add a bool to the `Inner` struct of the `DutiesService`, something like `track_balances` that's only true if metrics are enabled
- add a new optional field to `ValidatorStore` to track balances, similar to what you have for `SAVED_BALANCES`, but we could get away with only tracking indices, not pubkeys.
- query the balances endpoint to the end of `do_update`: https://github.com/sigp/lighthouse/blob/stable/validator_client/src/duties_service.rs#L584 and only run it when we are on a new epoch or are just starting (and `track_balances` is true)

**Comment by isoosiss7** [comment]
@realbigsean,

Thanks for your review. I've made corrections per your instructions. Pls help take another look when convenient.

**Comment by realbigsean** [comment]
Hey @isoosiss7, there is a PR [here](https://github.com/sigp/lighthouse/pull/2151) which would be a very good fit for this functionality, so we are going to add it there. I'm sorry we won't be able to get this branch in, but really do appreciate your work on it! We would also be very grateful if you would like to contribute on other issues :pray:

**Comment by realbigsean** [comment]
Closing because this will be added in #2151

**Pull request closed without merging**
