### PR TITLE
upgrade to Libp2pv0.49.0

### PR DESCRIPTION
**Pull request by divagant-martian**

### CODE REVIEW

**Comment by mxinden** [comment]
Let me know in case you need any help here @divagant-martian. Also, feel free to ping me when updating to v0.50.0 adding QUIC.

**Comment by divagant-martian** [comment]
Ty @mxinden the issue here is related to some custom clippy lints we use, so no need to worry. Thanks for offering to help. If the next one needs a hand I'll let you know

**Comment by divagant-martian** [comment]
moving this to upgrade to libp2p0.50.0 while we decide how to handle the failing lint. @michaelsproul if you find a way to keep it let me know. Also relevant: the lint already is using `continue_on_error` but, this is not enough for github to give a pr the green check (see https://github.com/actions/runner/issues/2347 )

**Comment by divagant-martian** [comment]
close in favor of #3764

**Pull request closed without merging**
