### PR TITLE
Ensure passwords are UTF-8 encoded

### PR DESCRIPTION
**Pull request by film42**
## Issue Addressed

Issue #1205 
Feedback from PR #1217 

## Proposed Changes

1. This uses `fs::read_to_string` to enforce utf8 when dealing with passwords.
2. This changes `PlainText(Vec<u8>)` to be a `PlainText(String)` to make it impossible (I think?) to carry an invalid utf8 password.
3. Updates a few methods that were going `PlainText -> &[u8] -> PlainText`. 
4. There is a new `unsafe` and a few comments around methods that can be removed.

## Additional Info

I'm relatively new to rust so please let me know if something here isn't a best practice. I'm also not super familiar with lighthouse but wanted to contributes to some new rust projects as practice. Thanks!

### CODE REVIEW

**Comment by film42** [comment]
Looks like I have some minor linting failures. I’ll fix those up tomorrow.

**Comment by film42** [comment]
I made a few style changes and fixed one of the failing tests. There's now a test that's failing due to an invalid UTF-8 password. Should the existing test be considered expected and correct behavior, or should the test change?

**Comment by divagant-martian** [comment]
hey @film42 this PR has not been updated in some time, we would love your contribution so if you need some help lets us know

**Comment by film42** [comment]
Thanks @divagant-martian ! Just looking for feedback since one of the tests seems to be using invalid utf8 but I'm not sure if that's something I can change, or if non-utf8 password should be allowed.

**Comment by divagant-martian** [comment]
hey @film42 just checked the failing checks. Those look like simple utf-8 passwords to me

**Comment by film42** [comment]
@divagant-martian you are correct. I didn't look deep enough into the error before. The password is valid utf8 but the `PlainText` result from `decrypt` is not valid utf8. Essentially, `PlainText` probably needs to continue wrapping `Vec<u8>` instead of `String`. Here's why: 

On master branch if I try to convert the result of the decrypt method to a ut8 string it fails. Start with this code section:

https://github.com/sigp/lighthouse/blob/467de4c8d0bab31bcbbe2d830af31fd3ecedda75/crypto/eth2_keystore/src/keystore.rs#L369-L384

And run a utf8 conversion after line 383

```
std::str::from_utf8(plain_text.as_bytes()).unwrap();
```

And we see it's invalid:
```
$ RUST_BACKTRACE=1 rustup run nightly cargo test -p eth2_wallet --test eip2386_vectors
    Finished test [unoptimized + debuginfo] target(s) in 0.22s
     Running target/debug/deps/eip2386_vectors-13ccbe4948483dd2

running 1 test
test eip2386_test_vector_scrypt ... FAILED

failures:

---- eip2386_test_vector_scrypt stdout ----
thread 'eip2386_test_vector_scrypt' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 2, error_len: Some(1) }', crypto/eth2_keystore/src/keystore.rs:385:48
stack backtrace:
...
```

From the linked issue:

> Making the PlainText type contain an actual String would make the newline stripping a lot cleaner too.

This is true, but not all plain text is uf8. This comment is probably more for my understanding. I'll need to re-work this PR a bit. Depending on how much changes, I might close this one and open a new one.

**Comment by film42** [comment]
Closing in favor of #2070 .

**Pull request closed without merging**
