### PR TITLE
[Merged by Bors] - Fix head tracker concurrency bugs

### LINKED ISSUE #1557: Head tracker has unsafe API wrt concurrency
## Description

Functions like `head`:
https://github.com/sigp/lighthouse/blob/3cfd70d7fd290a9f293d6d869bade90aba6c95ae/beacon_node/beacon_chain/src/beacon_chain.rs#L475-L485

or `heads`: https://github.com/sigp/lighthouse/blob/3cfd70d7fd290a9f293d6d869bade90aba6c95ae/beacon_node/beacon_chain/src/beacon_chain.rs#L509-L513

or `head_info`: https://github.com/sigp/lighthouse/blob/3cfd70d7fd290a9f293d6d869bade90aba6c95ae/beacon_node/beacon_chain/src/beacon_chain.rs#L488-L506

expose an API that is unsafe wrt to concurrent modifications of the head tracker.
## Version

3cfd70d7fd290a9f293d6d869bade90aba6c95ae

## Present Behaviour

Forks pruning deletes entries from the head tracker in a separate thread.  It may happen that a head gets removed from the head tracker while it is being used in a different thread.  That's a race condition.

## Expected Behaviour

Functions like `head()`, `heads()`, `head_info()` should hold a read lock on the head tracker while its contents are being used, by returning lock guards instead of simply copying `Hash256`.

## Steps to resolve

Return lock guards from the mentioned functions and fix all the resulting compilation errors.

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Closes #1557

## Proposed Changes

Modify the pruning algorithm so that it mutates the head-tracker _before_ committing the database transaction to disk, and _only if_ all the heads to be removed are still present in the head-tracker (i.e. no concurrent mutations).

In the process of writing and testing this I also had to make a few other changes:

* Use internal mutability for all `BeaconChainHarness` functions (namely the RNG and the graffiti), in order to enable parallel calls (see testing section below).
* Disable logging in harness tests unless the `test_logger` feature is turned on

And chose to make some clean-ups:

* Delete the `NullMigrator`
* Remove type-based configuration for the migrator in favour of runtime config (simpler, less duplicated code)
* Use the non-blocking migrator unless the blocking migrator is required. In the store tests we need the blocking migrator because some tests make asserts about the state of the DB after the migration has run.
* Rename `validators_keypairs` -> `validator_keypairs` in the `BeaconChainHarness`

## Testing

To confirm that the fix worked, I wrote a test using [Hiatus](https://crates.io/crates/hiatus), which can be found here:

https://github.com/michaelsproul/lighthouse/tree/hiatus-issue-1557

That test can't be merged because it inserts random breakpoints everywhere, but if you check out that branch you can run the test with:

```
$ cd beacon_node/beacon_chain
$ cargo test --release --test parallel_tests --features test_logger
```

It should pass, and the log output should show:

```
WARN Pruning deferred because of a concurrent mutation, message: this is expected only very rarely!
```

## Additional Info

This is a backwards-compatible change with no impact on consensus.

### CODE REVIEW

**Comment by michaelsproul** [comment]
This is WIP because I still need to decide whether I want to make the beacon chain head persist atomically when the pruning transaction commits. This would be safest. Right now it's possible for the pruning transaction to commit, and then fail to update the head tracker on disk if the node crashes or is killed. This could manifest in problems the next time it tries to prune, as the old heads will all still be lying around.

**Comment by michaelsproul** [comment]
Ok, I implemented the atomic update of the head, as I figured it was worth doing (https://github.com/sigp/lighthouse/pull/1771/commits/cc9f3812d5fd3b648c3961607ebe5efb6e23a8ba). There are some trade-offs documented in that commit.

This brings us to 0 known bugs in pruning... :thinking:

**Comment by michaelsproul** [comment]
@paulhauner I ended up _not_ persisting fork choice, because I think there's no invariant violated if the head tracker and fork choice have different sets of blocks. The main reason we were careful about persisting the head and fork choice was related to the head block root, which I (re)discovered is completely unused (I've opened #1784 to track this). This lead to several simplifications -- no more locking the head in `persisted_head_and_fork_choice` :open_mouth:, and no more threading `PersistedBeaconChain` through to migration, only to overwrite the head tracker field.

Let me know if you think differently, but I couldn't find any places where we assume `block in head_tracker --> block in fork_choice` or vice versa.

As it stands I think the main invariants we uphold are:

```
block in head_tracker --> block in database

block in fork_choice --> block in database
```

and we used to try to maintain:

```
persisted_beacon_chain in database --> persisted_beacon_chain.canonical_head_block_root in fork_choice
```

although we don't any longer.

**Review by paulhauner — APPROVED** [review]
> I ended up not persisting fork choice, because I think there's no invariant violated if the head tracker and fork choice have different sets of blocks.

Good point, I agree that we're not going to have an internal error if these two get out of sync.

As discussed, it would be nice to get rid of the head tracker all together but we can cover that in another PR.

I couldn't find any other issues, GGWP!

**Comment by michaelsproul** [comment]
Oh yeah, I'll create the issue for deleting the head track now

bors r+

**Pull request closed without merging**
