### PR TITLE
Delete macros.rs

### PR DESCRIPTION
**Pull request by JustinDrake**
The `macros.rs` file under `eth2/utils/ssz/src/` is (almost) empty. Can it be deleted?

### CODE REVIEW

**Comment by paulhauner** [comment]
As yes, I don't think that's a structural line-feed :laughing: 

Seeing as you're making a few contributions now, would you be able to enable Github Actions in `justindrakelighthouse` -> Settings -> Actions? Then our CI flow will run under your github account and I can quickly check it to ensure that CI passes.

I'll trigger it on our side this time :)

**Comment by paulhauner** [comment]
CI passes. Although this touches SSZ encoding, it is a non-substantive change so I'm happy to merge.

**Comment by JustinDrake** [comment]
Screenshot 2020-05-04 at 07 11 51

Is that what you mean? If so, it was already enabled.

**Comment by paulhauner** [comment]
> Is that what you mean? If so, it was already enabled.

Oh sorry, you're totally right. I swear I checked and I couldn't see your CI passing, but I must have done something wrong.

**Pull request merged**
