### PR TITLE
Merge `unstable` into `deneb-free-blobs`

### PR DESCRIPTION
**Pull request by jimmygchen**
There hasn't been much change since the last merge, but the self hosted runner PR has been merged to `unstable`, so it would be good to use the sigp self-hosted runners for much faster CI on deneb branch too. It should also unblock 
- #3929

### CODE REVIEW

**Comment by jimmygchen** [comment]
Marking this as WIP as there are a few failing jobs that needs investigation

**Comment by jimmygchen** [comment]
The `release-tests-windows` are failing to execute the fork choice tests
> error: test failed, to rerun pass `-p fork_choice --test tests`

@pawanjay176 mentioned that this was already failing and is related to the same kzg library issue in windows we've been experiencing lately, so it's not related to the self hosted runner.

**Comment by jimmygchen** [comment]
@realbigsean @pawanjay176 all tests are passing (except for `release-tests-windows` due to the kzg issue), so I think this is ready for review / merge.

**Review by realbigsean — APPROVED** [review]
Nice, thanks Jimmy!

**Pull request merged**
