### PR TITLE
[Merged by Bors] - Prune slashing protection DB

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Prune the slashing protection database so that it doesn't exhibit unbounded growth. Prune by dropping attestations and blocks from more than 512 epochs ago, relying on the guards that prevent signing messages with slots or epochs less than the minimum recorded in the DB.

The pruning process is potentially time consuming, so it's scheduled to run only every 512 epochs, in the last 2/3rds of a slot. This gives it at least 4 seconds to run without impacting other signing, which I think should be sufficient. I've seen it run for several minutes (yikes!) on our Pyrmont nodes, but I suspect that 1) this will only occur on the first run when the database is still huge 2) no other production users will be impacted because they don't have enough validators per node.

Pruning also happens at start-up, as I figured this is a fairly infrequent event, and if a user is experiencing problems with the VC related to pruning, it's nice to be able to trigger it with a quick restart. Users are also conditioned to not mind missing a few attestations during a restart.

We need to include a note in the release notes that users may see the message `timed out waiting for connection` the first time they prune a huge database, but that this is totally fine and to be expected (the VC will miss those attestations in the meantime).

I'm also open to making this opt-in for now, although the sooner we get users doing it, the less painful it will be: prune early, prune often!

### CODE REVIEW

**Comment by michaelsproul** [comment]
It was little bumpy, but I just successfully applied this on all the Pyrmont nodes. Interestingly, it tripped over itself a little bit, with regular attestation tasks vying for the SQLite DB lock and interrupting the pruning a few times before it could succeed:

```
Feb 12 14:25:14 le-hostname lighthouse-vc[3720]: Feb 12 14:25:14.010 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:19 le-hostname lighthouse-vc[3720]: Feb 12 14:25:19.015 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:25:19 le-hostname lighthouse-vc[3720]: Feb 12 14:25:19.019 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:24 le-hostname lighthouse-vc[3720]: Feb 12 14:25:24.019 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:25:27 le-hostname lighthouse-vc[3720]: Feb 12 14:25:27.000 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:32 le-hostname lighthouse-vc[3720]: Feb 12 14:25:32.001 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:25:39 le-hostname lighthouse-vc[3720]: Feb 12 14:25:39.000 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:44 le-hostname lighthouse-vc[3720]: Feb 12 14:25:44.001 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:25:51 le-hostname lighthouse-vc[3720]: Feb 12 14:25:51.001 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:56 le-hostname lighthouse-vc[3720]: Feb 12 14:25:56.001 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:26:16 le-hostname lighthouse-vc[3720]: Feb 12 14:26:16.501 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:26:21 le-hostname lighthouse-vc[3720]: Feb 12 14:26:21.501 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:28:28 le-hostname lighthouse-vc[3720]: Feb 12 14:28:27.279 INFO Pruning slashing protection DB          epoch: 19270
Feb 12 14:28:32 le-hostname lighthouse-vc[3720]: Feb 12 14:28:32.288 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:28:32 le-hostname lighthouse-vc[3720]: Feb 12 14:28:32.288 INFO Pruning slashing protection DB          epoch: 19270
Feb 12 14:28:37 le-hostname lighthouse-vc[3720]: Feb 12 14:28:37.288 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:28:37 le-hostname lighthouse-vc[3720]: Feb 12 14:28:37.288 INFO Pruning slashing protection DB          epoch: 19270
Feb 12 14:28:42 le-hostname lighthouse-vc[3720]: Feb 12 14:28:42.288 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:28:42 le-hostname lighthouse-vc[3720]: Feb 12 14:28:42.288 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:38:28 le-hostname lighthouse-vc[3720]: Feb 12 14:38:28.765 INFO Completed pruning of slashing protection DB
```

It also took more like 10 minutes on that node, and 20 minutes on this one:

```
Feb 12 14:25:12 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:12.006 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:17 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:17.006 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:25:17 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:17.019 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:22 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:22.019 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:25:22 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:22.019 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:27 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:27.019 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:25:27 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:27.019 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:32 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:32.019 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:25:39 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:39.001 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:25:44 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:25:44.001 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:27:22 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:27:22.013 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:27:27 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:27:27.014 ERRO Error during pruning of signed attestations, error: SQLPoolError("timed out waiting for connection")
Feb 12 14:27:38 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:27:38.519 INFO Pruning slashing protection DB          epoch: 19269
Feb 12 14:47:58 le-hostname-deux lighthouse-vc[4472]: Feb 12 14:47:58.330 INFO Completed pruning of slashing protection DB
```

Given that this is a one-off pain (which I think we've just paid), I'm inclined not to write more sophisticated code for dealing with this case. Will see how the nodes perform over the next few days.

**Comment by michaelsproul** [comment]
This PR has been running smoothly on Pyrmont all weekend, and pruning has occurred once more already (with another prune due in ~6 hours).

As you can see in this graph, the attestation times were cut from 5 seconds with spikes to 2 minutes, to consistently less than 1 second.

attestation_times

A close-up of the latter part of that graph:

attestation_times_closeup

The slight drop around 10am Feb 13 corresponds to the second pruning. The creep after that concerns me a little, so I'll be interested to see what happens at the next prune.

**Comment by michaelsproul** [comment]
Looks good after the 3rd prune. If we can tolerate the spikes to 2s I think this is ready to ship.

attestation_times_closeup2

**Comment by paulhauner** [comment]
This looks good to me, but I'll wait for the prune-on-startup change we discussed before approving (assuming we still take that route) :)

**Comment by michaelsproul** [comment]
Done! Tested only on my mainnet node so far (it worked fine). We can merge and see how it fares on the canaries before shipping a release?

**Review by paulhauner — APPROVED** [review]
LGTM!

**Pull request closed without merging**
