### PR TITLE
remove remaining uses of serde_derive

### PR DESCRIPTION
**Pull request by jxs**
## Issue Addressed

While reviewing #4054 found remaining `serde-derive` usages.

### CODE REVIEW

**Review by michaelsproul — COMMENTED** [review]
I'm on board with this as a way of removing duplication, but the impact is quite small, unless there's something I'm missing?

It feels like the number of merge conflicts this generates with Deneb and tree-states may be quite significant? Could we hold this until after Deneb? Or target this change at the `deneb-free-blobs` branch?

**Comment by jxs** [comment]
> I'm on board with this as a way of removing duplication, but the impact is quite small, unless there's something I'm missing?
> 
> It feels like the number of merge conflicts this generates with Deneb and tree-states may be quite significant? Could we hold this until after Deneb? Or target this change at the `deneb-free-blobs` branch?

yup makes sense, thanks Michael. Updated the PR to target `deneb-free-blobs`

**Review by realbigsean — APPROVED** [review]
nice thanks @jxs !

**Comment by realbigsean** [comment]
ah I tried to manually resolve the lockfile conflict but messed it up, so I'm raising a new pr for this here: https://github.com/sigp/lighthouse/pull/4830

**Pull request closed without merging**
