### PR TITLE
Verify-slashable-attestation

### PR DESCRIPTION
**Pull request by kirk-baird**
## Issue Addressed

#149 

## Proposed Changes

This will implement the helper method `verify_slashable_vote_data`

Which also requires 'get_domain' and 'get_fork_version'

## Additional Info

Currently a WIP as it requires PR https://github.com/sigp/signature-schemes/pull/3

### CODE REVIEW

**Comment by kirk-baird** [comment]
They have just changed the specs for this method so the current functionality is now out of date.

**Comment by paulhauner** [comment]
Closing this as works should continue at https://github.com/sigp/lighthouse-common :)

**Comment by paulhauner** [comment]
Hey @kirk-baird, let me know tomorrow if we should keep this open :)

**Comment by kirk-baird** [comment]
Yep, keep it open it's just needs #211 then I'll finish it off

**Comment by kirk-baird** [comment]
This is now written according to the specs but fails a test case due to bug in specs.

**Comment by kirk-baird** [comment]
Requires #240

**Comment by paulhauner** [comment]
I picked this up in #264. Thanks!

**Pull request closed without merging**
