### PR TITLE
[Merged by Bors] - Removed old Teku mainnet bootnode ENRs

### PR DESCRIPTION
**Pull request by lucassaldanha**
## Issue Addressed

N/A

## Proposed Changes

Removing the two Teku mainnet bootnodes that are being sunset.

## Additional Info

We are leaving only these two bootnodes: https://github.com/eth-clients/eth2-networks/blob/master/shared/mainnet/bootstrap_nodes.txt#L10-L11

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Thanks @lucassaldanha 🙏

**Comment by lucassaldanha** [comment]
I noticed that I ended up opening the PR against `stable`. I have changed it now but it might require running one of the actions again to validate it.

**Review by paulhauner — APPROVED** [review]
Thanks!

**Pull request closed without merging**
