### PR TITLE
Improved message validation

### PR DESCRIPTION
**Pull request by g-r-a-n-t**
## Issue Addressed

#583 

## Proposed Changes

Doing a shallow validation of block proposals and attestations before passing along to peers.

### CODE REVIEW

**Comment by paulhauner** [comment]
Confirming that this is ready for review? :)

**Comment by g-r-a-n-t** [comment]
@paulhauner confirmed

**Comment by paulhauner** [comment]
Hi Grant, thanks for this!

Can you please merge in master? We've updated our Ci and it will be triggered once you merge master in :)

**Comment by g-r-a-n-t** [comment]
@paulhauner merged and built

**Comment by g-r-a-n-t** [comment]
Or not... I guess there is a formatting issue -- I received an email.

**Comment by g-r-a-n-t** [comment]
It looks like I need to make some minor changes. I'll comment again when those are fixed up.

**Comment by g-r-a-n-t** [comment]
This is good now @paulhauner and @AgeManning

**Comment by AgeManning** [comment]
Awesome. We've got to get a few more things in before this. Will review and merge when ready. 

Thanks @g-r-a-n-t

**Comment by AgeManning** [comment]
The network upgrade PR #811 modifies a lot of the network code. I've merged these commits into that PR and will track and test that PR. 

Closing this PR in favour of #811

**Pull request closed without merging**
