### PR TITLE
[Merged by Bors] - Various CI fixes

### LINKED ISSUE #3705: CI warns about deprecated Node.js v12 in `setup-protoc`
## Description

There are warnings on CI about Node.js v12 being used in the `setup-protoc` action. We are waiting on a fix for https://github.com/arduino/setup-protoc/issues/45.

### LINKED ISSUE #3750: Fix multiline output for release notes on CI
## Description

The release CI crashes when outputting the multiline string for the release notes. We should use a "here document" like `<<<EOF` to escape the mulitline string.

CI crashing: https://github.com/sigp/lighthouse/actions/runs/3537291461

Fix (option 2): https://trstringer.com/github-actions-multiline-strings/

Testing will require running the release flow on a dummy release on someone's fork.

## Version

Should be fixed before v3.4.0

### LINKED ISSUE #3812: Rate limit for web3signer_tests on CI
## Description

We're occasionally getting rate-limited calling the Github API to download the `web3signer_tests`. E.g. https://github.com/sigp/lighthouse/actions/runs/3708544134/jobs/6286220721

The code triggering the rate limit is:

https://github.com/sigp/lighthouse/blob/bf533c8e42cc73c35730e285c21df8add0195369/testing/web3signer_tests/build.rs#L35-L45

Running that API call in a loop in my terminal I can trigger a 403 response by making more than 60 requests/second:

```json
{"message":"API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

## Steps to resolve

I think the best option would be to plumb the `GITHUB_TOKEN` into that build script so that it can use it to bypass the rate limit. The build script could read an _optional_ secret from its env when it runs and add this to the request headers (when running locally the header would not be added).

I think if we do something like `echo ${{ secrets.GITHUB_TOKEN }} >> $GITHUB_ENV` that _might_ be OK, as long as Github scrubs the token from the logs. Tokens are unique to each CI run and have very limited `read` permissions on pull requests. See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Closes #3812
Closes #3750
Closes #3705

### CODE REVIEW

**Comment by divagant-martian** [comment]
Why this specific commit hash for the actions? just curious

**Comment by michaelsproul** [comment]
> Why this specific commit hash for the actions?

The `setup-protoc` action hasn't tagged any new version since upgrading to Node.js 16, and I'm trying to avoid the deprecation notice for Node.js 12. That  commit is just the latest one as of a few days ago. If/when they make a release we could upgrade to it

**Review by divagant-martian — APPROVED** [review]

**Comment by michaelsproul** [comment]
Ok yay, after tweaking the GITHUB_TOKEN permissions on my fork I was able to get the release flow to push a draft release: https://github.com/michaelsproul/lighthouse/actions/runs/3736310168.

The only issue was that `download-artifact` wasn't upgraded, so I've bumped it in this commit: 46ccb1335e888f9caec3932563fd6fba1497feb4

Lets merge

bors r+

**Comment by michaelsproul** [comment]
gonna batch

bors r-

**Pull request closed without merging**
