### PR TITLE
Persist seen caches

### PR DESCRIPTION
**Pull request by danielschonfeld**
## Issue Addressed

#1055 

## Proposed Changes

Storing and restoring from disk the seen/observed caches

## Additional Info

Sketching out if this is the right way to go about persisting the seen caches.  Let me know what you think, and i'll be happy to implement the rest of the caches if you think this is the correct way to implement this issue.

### CODE REVIEW

**Comment by paulhauner** [comment]
Looks like you're on the right path, but CI is failing. I would suggest running:

- `cargo clippy --all`
- `make test-release`

Let me know if you have issues reproducing the failures on your end :)

**Comment by danielschonfeld** [comment]
should i first resolve these problems with CI or continue making all the seen caches persistent?

**Comment by paulhauner** [comment]
> should i first resolve these problems with CI or continue making all the seen caches persistent?

It's up to you. Perhaps fixing the CI errors now will save some time by learning about potential issues sooner rather than later?

**Comment by danielschonfeld** [comment]
Looks like all checks are good now, so i'll continue implementing the rest of the caches.  

One question tho, I do seem to have a problem with ganache-cli.  Whenever the eth1 tests run (and I realize they don't really pertain to this PR, but i'd like to get it to work).  It fails trying to connect to the ganache instance with the following error:

```
---- eth1_cache::simple_scenario stdout ----
thread 'eth1_cache::simple_scenario' panicked at 'should start eth1 environment: "Failed to start HTTP transport connected to ganache: Io(Os { code: 24, kind: Other, message: \"Too many open files\" })"', beacon_node/eth1/tests/test.rs:111:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It also leaves the instance of ganache running.  

How do I go about fixing this? (running latest ganache-cli on node ```v12.18.4```

**Comment by paulhauner** [comment]
>  It fails trying to connect to the ganache instance with the following error:

I assume you're on macos, since we see this issue most there.

Running all the tests concurrently is probably hitting the "open file descriptor limits". You can increase it: https://becomethesolution.com/blogs/mac/increase-open-file-descriptor-limits-fix-too-many-open-files-errors-mac-os-x-10-14

**Comment by danielschonfeld** [comment]
@paulhauner I am taking the approach of implementing my own HashMap and HashSet encoder/decoder for SSZ.  It works, but i'd like your opinion if this is the best way to take here.

I figured it would make the boiler plate less repetitive as most of the seen caches are HashMaps (with one being a HashSet).

If you have some time, i'd appreciate if you can take a look at what i've done there and tell me what you think about where i'm headed with this.  If you agree with the direction, i can now easily persist the rest of the observed caches as well as adding appropriate tests to reflect that.

**Comment by paulhauner** [comment]
> I am taking the approach of implementing my own HashMap and HashSet encoder/decoder for SSZ. It works, but i'd like your opinion if this is the best way to take here.

I can see why this is appealing, but the trouble here is that SSZ is an implementation of [this specification](https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/simple-serialize.md), which does not include definitions for maps/sets. As such, we can't really go and make an implementation for these objects then call it SSZ.

Additionally,  it's very important that SSZ is panic-free since it's our first point of call for (potentially malicious) packets from the internet. It's currently panic-free (as far as we know) and has undergone significant review and fuzzing. Having a look at your implementation, I think I can see some potentially out-of-bounds array access in decoding.

So, for those reasons I'm against adding these impls to the `eth2_ssz` crate. I wouldn't be opposed to some helper functions being placed in some other crate, though :)

**Comment by danielschonfeld** [comment]
Fair enough and understandable. Glad I asked :)
I’ll redo it with helper functions and intermediate Ssz containers.

Thanks for taking the time to look! Much appreciated

**Comment by danielschonfeld** [comment]
@paulhauner alright this PR is ready for review.  Please pay particular attention to my PartialEq.  I implemented it in a way that made sense to me as far as checking sanity for the tests I wrote.  I hope it also makes sense in 'real life' too what I put in there.

Otherwise I think this is ready.  I'm also open to criticism especially around my usage of the trait type system, as you'll see in both ```ObservedAttesters``` and ```ObservedAggregators``` in the ```observed_attesters.rs``` file.  Please be gentle :)

**Comment by danielschonfeld** [comment]
As an aside, i tried raising the maximum open files limit to this 
```
	maxfiles    65536          524288
```
and I still get the same problem with ganache

**Comment by paulhauner** [comment]
Just letting you know we haven't forgotten about this @danielschonfeld. Apologies for the delay.

**Comment by danielschonfeld** [comment]
Let me know when i should resolve the conflicts with master.  Preferably when it's closer to getting merged, so as to not have to resolve the conflicts many times. 

Take your time, I know you guys are busy these days.  Just offering to fix this to become mergeable anytime you're ready.

**Comment by sweetslr** [comment]
Sounds like a good Idea
________________________________

**Comment by paulhauner** [comment]
Hey @danielschonfeld, I've picked this up in #1912, resolved the merge conflicts and got it working.

I'm still finishing it off, but perhaps you could give me a review on #1912? No pressure, of course!

Thanks again for contributing to this one! I'll close this in favor of the other PR :)

**Pull request closed without merging**
