### PR TITLE
[Merged by Bors] - Add check for head/target consistency

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Addresses an interesting DoS vector raised by @protolambda by verifying that the head and target are consistent when processing aggregate attestations. This check prevents us from loading very old target blocks and doing lots of work to skip them to the current slot.

## Additional Info

NA

### CODE REVIEW

**Comment by paulhauner** [comment]
I would like to do one more review before merging, so please leave bors to me :)

**Review by michaelsproul — APPROVED** [review]
This looks good to me :+1:

**Comment by paulhauner** [comment]
I just added a test :) I'll bors r+ after it merges.

**Pull request closed without merging**
