### PR TITLE
[Merged by Bors] - Release v2.5.1

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Patch release to address fork choice issues in the presence of clock drift: https://github.com/sigp/lighthouse/pull/3402

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
LGTM!

**Comment by michaelsproul** [comment]
[Hack my CLA Bors](https://cla-assistant.io/check/sigp/lighthouse?pullRequest=3406)

**Comment by paulhauner** [comment]
Nethermind EE tests failed because there was an unexpected number of transactions in a block. Since there hasn't been a commit to https://github.com/NethermindEth/nethermind `master` in the last 12hrs then I think this must be a spurious failure. Let's test that hypothesis.

bors retry

**Comment by paulhauner** [comment]
This has been put on hold so #3408 can be included.

**Comment by paulhauner** [comment]
#3408 is merged 🎉

bors r+

**Comment by michaelsproul** [comment]
Nooo Windows!!

bors retry

**Pull request closed without merging**
