### PR TITLE
Small update to lighthouse book

### PR DESCRIPTION
**Pull request by dpdanpittman**
## Issue Addressed
a couple of questions from users in discord

Which issue # does this PR address?
none

## Proposed Changes

Please list or describe the changes introduced by this PR.

adding a couple of instructions for adding the graffiti and making sure users are running a beacon before importing validator keys

## Additional Info

I know this isn't important but wanted to help users as I see questions arise on discord

Please provide any additional information. For example, future considerations
or information useful for reviewers.

-qwoyn | etherchest

### CODE REVIEW

**Review by paulhauner — CHANGES_REQUESTED** [review]
Thanks for your contribution!

Seeing as POAPs are a fairly temporary and non-mission-critical, perhaps we could just add a section to the FAQ that covers POAP, instead of instructing all users to use them?

**Comment by dpdanpittman** [comment]
Good Idea, will make changes

**Comment by sigma67** [comment]
I was also looking for info on this when setting up the client and it was hard to find (esp. compared to prysm docs)

**Comment by paulhauner** [comment]
Hi @dpdanpittman, wondering if you're still interested in finishing this one up? No worries if not :)

**Comment by dpdanpittman** [comment]
Yes, let me make some changes now with some small examples.

**Comment by paulhauner** [comment]
Closing this since we've refactored the documentation for the v0.3.0 release. My apologies @dpdanpittman.

**Comment by dpdanpittman** [comment]
No worries!!! Keep up the good work.  Looking forward to launch!

**Pull request closed without merging**
