### PR TITLE
[Merged by Bors] - 404's on API requests for slots that have been skipped or orphaned

### LINKED ISSUE #2186: bn /eth/v1/beacon/blocks/{block_id} return wrong information on skipped block
## Description

Making get request on skipped block return earliest not skipped block

## Version

**docker** sigp/lighthouse:v1.1.0

## Present Behaviour

GET /eth/v1/beacon/blocks/554465
https://pyrmont.beaconcha.in/block/554465

return information of block 554464
https://pyrmont.beaconcha.in/block/554464

## Expected Behaviour

GET /eth/v1/beacon/blocks/{block_id} (on skipped block)
should return 404

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

Resolves #2186

## Proposed Changes

404 for any block-related information on a slot that was skipped or orphaned

Affected endpoints:
- `/eth/v1/beacon/blocks/{block_id}`
- `/eth/v1/beacon/blocks/{block_id}/root`
- `/eth/v1/beacon/blocks/{block_id}/attestations`
- `/eth/v1/beacon/headers/{block_id}`

### CODE REVIEW

**Comment by paulhauner** [comment]
I'm thinking we *don't* include this PR in this weeks release, since it'll require a minor version bump and this release contains a bug fix that we want users on ASAP (#2283)

**Review by paulhauner — COMMENTED** [review]
Looks good to me, but I think a regression test could potentially save our ass down the line.

**Comment by michaelsproul** [comment]
Tagging this as `backwards-incompat`, a new label I made to help us track breaking changes between releases

**Comment by realbigsean** [comment]
> Looks good to me, but I think a regression test could potentially save our ass down the line.

Updated!

**Review by paulhauner — APPROVED** [review]
Nice one!

bors r+

**Comment by paulhauner** [comment]
bors retry+

**Pull request closed without merging**
