### PR TITLE
[Merged by Bors] - v3.1.1

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions

## Additional Info

- ~~Requires additional testing~~
- ~~Blocked on:~~
    - ~~#3589~~
    - ~~#3540~~
    - ~~#3587~~

### CODE REVIEW

**Comment by michaelsproul** [comment]
lets bump `cpufeatures` as well seeing as it's currently yanked

**Comment by paulhauner** [comment]
I just rebased this on `staging` to to include #3540 and #3587.

**Comment by paulhauner** [comment]
Rebased onto `unstable`

**Comment by paulhauner** [comment]
Rebased onto `staging` to include #3595

**Comment by paulhauner** [comment]
Rebased onto `staging` to include #3596.

**Comment by paulhauner** [comment]
I'm happy with the amount of testing this has had and would be happy to release. However, we need to find an opportune time with respect to public holidays and weekends.

**Comment by michaelsproul** [comment]
I would be OK with releasing this afternoon, and then we can do support tomorrow before the weekend.

There's also going to be a Rust compiler release in the next 24h that will break Clippy on CI, so if we want to ship this without further changes we should merge sooner rather than later (https://www.whatrustisit.com/)

**Comment by paulhauner** [comment]
bors retry

**Comment by paulhauner** [comment]
This will likely merge into `unstable` in the coming hours, but we won't merge it into `stable` until "tomorrow" (roughly 12-18hrs).

**Pull request closed without merging**
