### PR TITLE
[Merged by Bors] - remove commas from comma-separated kv pairs

### PR DESCRIPTION
**Pull request by antondlr**
## Issue Addressed

Logs are in comma separated kv list, but the values sometimes contain commas, which breaks parsing

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]

**Comment by divagant-martian** [comment]
sometimes we log lists, and these will contain comma separated values. Will those be ok?
It's probably worth doing some change in the  [logging crate](https://github.com/sigp/lighthouse/blob/b477c4274880de1e39b074b6e51c95dacee5d03f/common/logging/src/lib.rs) to make this more future resilient

**Comment by antondlr** [comment]
good point! 
it depends... simple lists are fine
ex:  `fork_digest: [74, 38, 197, 139]`
others (nested kv pairs) are more problematic but not impossible to work with
ex: `error: An error occurred while negotiating the transport protocol(s) on a connection: [("/ip4/1.2.3.4/tcp/13000/p2p/16Uiu2HAmKfPCYPSNi6EEpAyCcDxc9Dk6zthU8wYuMwvz01234567", Other(Custom { kind: Other, error: Other(A(B(Select(ProtocolError(IoError(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })))))) }))].`

as long as it's syntactically correct (for the nested ones), and encapsulated, it's ok I guess?

**Review by nitindudeja2107 — APPROVED** [review]

**Review by nitindudeja2107 — APPROVED** [review]

**Comment by michaelsproul** [comment]
Sorry, everything conflicts with https://github.com/sigp/lighthouse/pull/3711, and seeing as that's biggger and older I'm gonna prioritise getting it in

**Pull request closed without merging**
