### PR TITLE
Fix for blank line in graffiti file

### PR DESCRIPTION
**Pull request by shayanb**
## Issue Addressed

Which issue # does this PR address?
https://github.com/sigp/lighthouse/issues/5880

## Proposed Changes

Please list or describe the changes introduced by this PR.
Skip empty line as described in the issue 5880

## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

### CODE REVIEW

**Comment by michaelsproul** [comment]
Hi @shayanb, do you think you could try to add a test too? You can extend or copy the existing test in that file

**Comment by shayanb** [comment]
> Hi @shayanb, do you think you could try to add a test too? You can extend or copy the existing test in that file

Hi @michaelsproul , yes for sure. There are many places I could implement the test, my guess is that it fits in `lighthouse/tests/validator_client.rs`, I'll push the change shortly but please do let me know if the test should be implemented somewhere else.

**Comment by shayanb** [comment]
@michaelsproul here you go, added tests for different new line scenarios. Let me know if anything else is needed here.

**Comment by shayanb** [comment]
I'd like to add printing the graffiti in the logs for validator initialization, would it fit in this PR or I can create a new PR for that.

Basically this line in `validator_client/initialized_validators/src/lib.rs` (although not sure how to test it yet):

```
                                self.validators
                                    .insert(init.voting_public_key().compress(), init);
                                info!(
                                    self.log,
                                    "Enabled validator";
                                    "signing_method" => "local_keystore",
                                    "voting_pubkey" => format!("{:?}", def.voting_public_key),
                                    **"graffiti" => format!("{:?}", def.graffiti)**
                                );
```

**Comment by michaelsproul** [comment]
@shayanb Thanks for the test, looks good!

I think we could add the graffiti logging in a separate PR. There's some subtlety there because the graffiti can change at runtime, so whatever we log on startup won't necessarily stay. It could still be nice to log it though

**Comment by michaelsproul** [comment]
Cargo fmt is failing, but you can fix it with `cargo fmt --all` (you can probably also configure your editor to run `cargo fmt` on save).

**Comment by shayanb** [comment]
@michaelsproul thanks for the tip, pushed the fmt commit.

I'll submit graffiti logging PR soon.

**Review by michaelsproul — APPROVED** [review]
Looks great, thanks

The CI failure is unrelated, will be fixed by:

- https://github.com/sigp/lighthouse/pull/6646

**Comment by michaelsproul** [comment]
@mergify queue

**Comment by michaelsproul** [comment]
@mergify requeue

**Pull request merged**
