### PR TITLE
[lcli] the fork version is now inferred from the spec and can also be…

### PR DESCRIPTION
**Pull request by onqtam**
## Proposed Changes

The fork version is now inferred from the spec and can also be overridden for the interop-genesis subcommand with a command line flag just like for the new-testnet subcommand - no more hardcoded `1337` value. This helps with interop scripts with other clients - to easily generate the same genesis ssz files.

### CODE REVIEW

**Comment by paulhauner** [comment]
Thank you @onqtam!

This hardcoding is an artifact of when the spec didn't allow varying the genesis fork, it's been quite an annoying legacy! I believe this is the last one!

I'm going to trigger CI, happy to merge after that.

**Comment by paulhauner** [comment]
Looks like we're failing on rust-fmt, this is quite common.

If you run `cargo fmt --all` in the root of the repo and commit the results we should be good to go :)

**Comment by onqtam** [comment]
done :)

**Comment by paulhauner** [comment]
Thank you! Triggering PR again!

**Comment by paulhauner** [comment]
Thank you!

**Pull request merged**
