### PR TITLE
[Merged by Bors] - Add Ropsten configuration

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Adds the configuration for the upcoming merge of the Ropsten network, as per:

https://github.com/eth-clients/merge-testnets/pull/9

Use the Ropsten network with: `lighthouse --network ropsten`

## Additional Info

This is still a work-in-progress. We should wait for the eth-clients/merge-testnets PR to be approved before merging this into our `unstable`.

### CODE REVIEW

**Comment by paulhauner** [comment]
~~Currently blocked on https://github.com/eth-clients/merge-testnets/pull/9#discussion_r874429208~~

**Comment by pawanjay176** [comment]
Looks like the config was updated here https://github.com/eth-clients/merge-testnets/commit/5b1b44aa912dd3433ba30d381345659c53918955

**Comment by paulhauner** [comment]
> Looks like the config was updated here https://github.com/eth-clients/merge-testnets/commit/5b1b44aa912dd3433ba30d381345659c53918955

That commit modifies shadow-fork-5, without touching ropsten. Thanks for point it out though!

This PR is up-to-date with https://github.com/eth-clients/merge-testnets/commit/5cbccd4449b5cbfcd677d1ee13515671e0f03928

**Comment by michaelsproul** [comment]
TTD is still subject to change, perhaps we should hold off merging until then?

https://github.com/ethereum/pm/issues/527#issuecomment-1130287515

Or should we merge so we can roll out infra, and then ship an update as necessary?

**Comment by paulhauner** [comment]
> Or should we merge so we can roll out infra, and then ship an update as necessary?

I think this is my preference, but not a strong one.

**Review by michaelsproul — APPROVED** [review]
LGTM! Exciting to have a new network supported!

**Pull request closed without merging**
