### PR TITLE
Block Verification Optimization

### PR DESCRIPTION
**Pull request by Gua00va**
## Issue Addressed

Solves #4973 

## Proposed Changes

Added `fork_choice_read_lock`  as parameter to avoid lock bouncing here: https://github.com/sigp/lighthouse/blob/441fc1691b69f9edc4bbdc6665f3efab16265c9b/beacon_node/beacon_chain/src/block_verification.rs#L765-L769

### CODE REVIEW

**Comment by Gua00va** [comment]
@michaelsproul, Some tests are failing due to timeout after 60 seconds. Is it because of the changes?

**Comment by michaelsproul** [comment]
> Some tests are failing due to timeout after 60 seconds. Is it because of the changes?

Hmm, the change looks OK to me. Lets see how it does on CI.

Which tests were timing out? Cargo sometimes just warns if a test runs longer than 60s, but that's OK. Some of our tests do just take a long time.

**Comment by Gua00va** [comment]
> > Some tests are failing due to timeout after 60 seconds. Is it because of the changes?
> 
> Hmm, the change looks OK to me. Lets see how it does on CI.
> 
> Which tests were timing out? Cargo sometimes just warns if a test runs longer than 60s, but that's OK. Some of our tests do just take a long time.

Mostly Block verification tests. If it is just a warning then I think there is no problem.

**Review by michaelsproul — APPROVED** [review]
This LGTM, but it was also my idea so I'll get 1 more person to check it :grin:

**Review by jimmygchen — APPROVED** [review]
Looks good to me! Seems like a pretty low risk change and tests are passing!

**Pull request merged**
