### PR TITLE
First change to validate

### LINKED ISSUE #4499: Prefer `test_logger` over `null_logger`
## Description

There's likely no case where `null_logger` is preferable over `test_logger` as the latter allows runtime configuration of logging output whereas the former hardcodes us into discarding logging output no matter what.

## Version

0c7eed5

## Present Behaviour

```
$ grep -rin "null_logger" --exclude-dir=target | wc -l
37
```

## Expected Behaviour

```
$ grep -rin "null_logger" --exclude-dir=target | wc -l
0
```

## Steps to resolve

Probably just a `sed` job realistically, although some areas may be slightly more involved to patch (I haven't checked very thoroughly at this stage).

### PR DESCRIPTION
**Pull request by postmeback**
## Issue Addressed
Fixes #4499 

## Proposed Changes

Remove the implementation of null_logger, else implement test_logger.

`null_logger` can be found **common/task_executor/src/test_utils.rs**

`test_logger` can be found **common/logging/src**

## Additional Info

I have done only one change as of now. Please review and let me know, whether I am on a right path. Then, I will do changes in other places.

### CODE REVIEW

**Comment by ackintosh** [comment]
Could you please change the target branch from `stable` to `unstable`?

**Comment by postmeback** [comment]
Target branch changed from `stable` to `unstable`.

Can you review my changes, and let me know whether I am on the right path or not?

**Comment by paulhauner** [comment]
> Can you review my changes, and let me know whether I am on the right path or not?

Yep you're on the right path, feel free to proceed!

**Comment by postmeback** [comment]
Changes done, Requesting for review. 

Open for suggestions.

**Comment by postmeback** [comment]
Requesting for review

**Comment by paulhauner** [comment]
Heyo, I tried to fix the merge conflicts but I ran afoul of the formatter sorry. Could you please do `git pull && cargo fmt` and the commit+push the result?

**Comment by postmeback** [comment]
> Heyo, I tried to fix the merge conflicts but I ran afoul of the formatter sorry. Could you please do `git pull && cargo fmt` and the commit+push the result?

Sure, let me try.

**Comment by postmeback** [comment]
image


I did `git pull` and `cargo fmt`.

Two files got changed in my branch. Shall I commit the `cargo.lock` ?

**Comment by paulhauner** [comment]
> Two files got changed in my branch. Shall I commit the cargo.lock ?

I'm not sure, but let's give it a go. Try committing both files and we can see what happens :)

**Comment by postmeback** [comment]
Okay.

**Comment by postmeback** [comment]
Done.

**Comment by paulhauner** [comment]
Sorry @postmeback, it looks like committing the `Cargo.lock` wasn't the right thing to do. To fix it, I'd run:

```
git checkout unstable Cargo.lock
cargo check
git add Cargo.lock
git commit -m "Refresh Cargo.lock"
git push
```

**Comment by postmeback** [comment]
So, now it is ok to go forward ?

**Comment by postmeback** [comment]
The `work-in-progress` tab can be removed.

**Comment by paulhauner** [comment]
I pushed a fix to the `Cargo.lock` myself, so that's resolved now. However I can see that [tests are failing](https://github.com/sigp/lighthouse/actions/runs/5790874547/job/15694697929?pr=4527) and there are also instances of `null_logger` still remaining:

```bash
grep -rnw '.' -e 'null_logger' --exclude-dir 'target'
./common/task_executor/src/test_utils.rs:29:        let log = null_logger().unwrap();
./common/task_executor/src/test_utils.rs:70:pub fn null_logger() -> Result<Logger, String> {
./common/logging/src/lib.rs:236:            .expect("Should build null_logger")
./beacon_node/network/src/network_beacon_processor/mod.rs:14:use environment::null_logger;
./beacon_node/network/src/network_beacon_processor/mod.rs:553:        let log = null_logger().unwrap();
```

**Comment by paulhauner** [comment]
My advice would be to delete the `null_logger()` definition in `./common/task_executor/src/test_utils.rs:70:` and then go about making sure that you can get both of these commands to run without error:

1. `make lint`
1. `make udeps`

That should be a surefire way of ensuring there are no more uses of `null_logger` and it would be a good start to producing something that will pass CI ☺️

**Comment by postmeback** [comment]
Okay, will sure try.  Thanks for the suggestion. ☺️

**Comment by dapplion** [comment]
Pinging author @postmeback

**Comment by dapplion** [comment]
Closing for inactivity. Thank you @postmeback for the contribution! Please feel free to pick other good first issues if you want to contribute again

**Comment by postmeback** [comment]
Sorry was busy IRL. 😞

**Pull request closed without merging**
