### PR TITLE
Use Hashtree macro for most struct types

### PR DESCRIPTION
**Pull request by mjkeating**
## Issue Addressed

#245 

## Proposed Changes

- Add Hashtree macro to ssz_derive.
- Replace TreeHash trait implementation with macro on eligible struct types

### CODE REVIEW

**Comment by paulhauner** [comment]
Looks great, thanks!

Please see my [comments here](https://github.com/sigp/lighthouse/pull/250#issuecomment-466809366) about the merge conflict. :)

**Comment by paulhauner** [comment]
So it turns out we can use `TreeHash` as a derive macro _without_ conflicting with the `TreeHash` trait!

I think it would be best to rename `Hashtree` to `TreeHash`, what do you think?

Here's a [branch](https://github.com/sigp/lighthouse/tree/treehash-rename) that I tested it in, if you want to save the effort. (It was only a single find/replace, which is potentially easier than pulling and merging a remote branch...)

**Comment by mjkeating** [comment]
That's great to know and makes sense. Thanks for testing it out. I went ahead and updated the PR if that works.

**Comment by paulhauner** [comment]
Awesome!

**Pull request merged**
