### PR TITLE
[Merged by Bors] - Correct a race condition when dialing peers

### PR DESCRIPTION
**Pull request by AgeManning**
There is a race condition which occurs when multiple discovery queries return at almost the exact same time and they independently contain a useful peer we would like to connect to.

The condition can occur that we can add the same peer to the dial queue, before we get a chance to process the queue. 
This ends up displaying an error to the user: 
```
ERRO Dialing an already dialing peer
```
Although this error is harmless it's not ideal. 

There are two solutions to resolving this:
1. As we decide to dial the peer, we change the state in the peer-db to dialing (before we add it to the queue) which would prevent other requests from adding to the queue. 
2. We prevent duplicates in the dial queue

This PR has opted for 2. because 1. will complicate the code in that we are changing states in non-intuitive places. Although this technically adds a very slight performance cost, its probably a cleaner solution as we can keep the state-changing logic in one place.

### CODE REVIEW

**Comment by divagant-martian** [comment]
if looks like you need to bump our msrv, also if you think it's fine, could we bump the `delay_map` version of `deposit_contract` to avoid having two versions?

**Comment by AgeManning** [comment]
Updated the MSRV, I dont think `deposit` contract uses `delay_map`. There is an older version used in discv5, but we will update that dep with a new release which we need soon anyway.

**Comment by divagant-martian** [comment]
oh yeah that was a gross misreading on my part, it's the discv5 one

**Review by divagant-martian — APPROVED** [review]

**Pull request closed without merging**
