### PR TITLE
Deprecate `eth1` and `dummy-eth1` flags

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Deprecate the following beacon node flags:

- `--eth1`: No longer required because it is enabled by default. The deposit contract sync can be disabled via a separate flag `--disable-deposit-contract-sync`, which has existed since the merge.
- `--dummy-eth1`: Very rarely used and of limited utility.

### CODE REVIEW

**Review by eserilev — COMMENTED** [review]
nit 

https://github.com/sigp/lighthouse/blob/d10e81afda2ddea80b19daf9b996d78451186a9b/beacon_node/src/config.rs#L285-L294

since `sync_eth1_chain` is now `true` by default, I think this line is redundant. Also the comments about the deprecated `--eth-1` flag might no longer be relevant. 

EDIT:

also this line here may be redundant

https://github.com/sigp/lighthouse/blob/d10e81afda2ddea80b19daf9b996d78451186a9b/beacon_node/src/config.rs#L124

**Comment by michaelsproul** [comment]
Nice catch, thanks @eserilev. I've removed that redundant code and also added a `conflicts_with` for `--staking` and `--disable-deposit-contract-sync`. Other than the `conflicts_with` clause, `staking` is basically identical to `http` now, but this may not remain the case forever, and I think our users appreciate this flag.

**Review by eserilev — APPROVED** [review]
LGTM!

**Comment by michaelsproul** [comment]
@mergify queue

**Pull request merged**
