### PR TITLE
[Merged by Bors] - Release v3.4.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions

## Additional Info

- [x] ~~Blocked on #3728, #3801~~
- [x] ~~Blocked on #3866~~
- [x] Requires additional testing

### CODE REVIEW

**Comment by paulhauner** [comment]
Force pushed to include #3866

**Review by michaelsproul — APPROVED** [review]
Lets do it!

**Comment by paulhauner** [comment]
🎉  I'll merge this now and push the `v3.4.0` flag so CI can start running. It's most likely that we'll merge to `stable` and publish the release in ~24hrs. This will give CI some time to run and for us to troubleshoot any issues.

Users should wait until `stable` is updated and the release has been published before updating, just in case we find anything during the release process.

**Comment by michaelsproul** [comment]
grr Github API failure

bors retry

**Comment by paulhauner** [comment]
Windows test failed due to the non-deterministic `test_same_subnet_unsubscription` test.

bors retry

**Comment by michaelsproul** [comment]
Cargo OOMed

bors retry

**Pull request closed without merging**
