### PR TITLE
Fix boolean bitfield serde bug

### LINKED ISSUE #86: BooleanBitfield test failing
## Description

I have created a test for BooleanBitfield that I think should pass, but fails.

https://github.com/sigp/lighthouse/commit/bedc1abec00ef72f57b447c0136937cc39bf5232

## Present Behaviour

Test fails

## Expected Behaviour

I think this test should pass

## Steps to resolve

I haven't looked into how to resolve it.

### PR DESCRIPTION
**Pull request by ralexstokes**
## Issue Addressed

Fixes #86 .

## Proposed Changes

Updates implementation to follow the Python reference implementation.

### CODE REVIEW

**Comment by ralexstokes** [comment]
i actually have some failing tests -- need to fix them before this can be merged.

also -- any reason they didn't show up in the CI?

**Comment by ralexstokes** [comment]
referring to this comment and the following check: https://github.com/sigp/lighthouse/blob/master/beacon_chain/validation/src/attestation_validation.rs#L130

i don't see how this won't almost always fail... it is causing some tests to fail now because we take a bitfield with 5 validators and serialize to a full byte. when we deserialize, we get a differing length for the bitfield vs. the attestation indices ( `.len() == 8` vs `.len() == 5`).

this test was passing before because we only increased the length of the bitfield to the "high water mark", i.e. the highest set bit in the serialized bytes. but the original test case for this PR has us extend to the full bit count.

without some way to discriminate in the serialization, this kind of ambiguity will continue to exist. thoughts @paulhauner ?

given my read on the existing code, perhaps we want to check a round-trip serde where the highest bit is set, rather than the original example in #86?

**Comment by paulhauner** [comment]
I can see why this happens now, thanks for the explainer.

A potential solution would do our own impl of `PartialEq` which puts both bitfields into their canonical serialized format for comparison. Off the top of my head, equality comparisons are only used in tests so I don't think this would be a significant slow down.

I am leaning towards the custom `PartialEq` implementation. What are your thoughts @ralexstokes?

**Comment by ralexstokes** [comment]
I'm a little confused by the comment:

```
/*
* If there are excess bits in the bitfield because the number of a validators in not a
* multiple of 8, reject this attestation record.
*
* Allow extra set bits would permit mutliple different byte layouts (and therefore hashes) to
* refer to the same AttesationRecord.
*/
```

Is it referring to excess _set_ bits? Unless number of validators mod 8 == 0, then we will always have "excess" bits. And in this case it could just be an error in translation -- using what I'm inferring to be the correct method `num_set_bits`, all the previously failing tests pass... @paulhauner can you confirm this is what you were going for w/ the attestation validation here?

**Comment by paulhauner** [comment]
Yep, sorry this is a typo. It should be:

>  If there are excess _set_ bits in the bitfield...

Excess bits are indeed inescapable if `len(validators) % 8 > 0`. Excess _set_ bits are the bad guys.

**Comment by ralexstokes** [comment]
gotcha -- ok that was one bug then!

and now looking at what you were talking about above -- yeah, I like `std::cmp::PartialEq` override for this.

if it becomes a bottleneck we can find a better way to handle this...

**Comment by paulhauner** [comment]
My bad!

Awesome, lets roll with the `PartialEq` for now!

**Comment by ralexstokes** [comment]
@paulhauner this should be ready to merge (and unblock all the other stuff!!)

**Pull request merged**
