### PR TITLE
[Merged by Bors] - Release v2.0.0-rc.0

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Cut the first release candidate for v2.0.0, in preparation for testing and release this week

## Additional Info

Builds on #2632, which should either be merged first or in the same batch

### CODE REVIEW

**Comment by michaelsproul** [comment]
Blocked on some compatibility-preserving changes in https://github.com/sigp/lighthouse/pull/2636

**Comment by michaelsproul** [comment]
Going to run this overnight on our fleet and release tomorrow

**Review by paulhauner — APPROVED** [review]
LGTM!

**Comment by michaelsproul** [comment]
After running smoothly over night, and earlier in the week, it's time to merge!

bors r+

**Pull request closed without merging**
