### PR TITLE
Spellcheck FAQ

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

A few small typo fixes in `faq.md`.

### CODE REVIEW

**Comment by chong-he** [comment]
Looks good! 

I was planning to add a spell-check on the Lighthouse book like we did for the Anchor book: https://github.com/sigp/anchor. Got a branch on this and hopefully to get it done at some point

**Comment by michaelsproul** [comment]
That sounds great!

**Review by dapplion — APPROVED** [review]

**Comment by michaelsproul** [comment]
@mergify queue

**Comment by michaelsproul** [comment]
@mergify dequeue

**Comment by michaelsproul** [comment]
Closing in favour of:

- https://github.com/sigp/lighthouse/pull/6627

**Pull request closed without merging**
