### PR TITLE
[Merged by Bors] - Creates a new lighthouse user and makes it the default user to be use…

### PR DESCRIPTION
**Pull request by b-m-f**
…d in the Docker image

## Issue Addressed
https://github.com/sigp/lighthouse/issues/1459

## Proposed Changes

- Create new `lighthouse` user and group in Docker container
- Set user as the default user

### CODE REVIEW

**Comment by acequicksilver** [comment]
Do the startup scripts in lighthouse-docker need to change to reflect the new lighthouse user?

**Comment by b-m-f** [comment]
@acequicksilver they should not need any changes as far as I can see. 

I ran `docker exec -ti lighthouse /bin/bash` and was logged in as the **lighthouse** user, confirmed with running `id`.
This should be the case for the scripts as well.

**Comment by acequicksilver** [comment]
start-beacon-node.sh references the root home directory --network-dir /root/network and there will be some references in the docker compose-compose.yml

**Comment by b-m-f** [comment]
@acequicksilver Good catch. Could simply change it to the environment variabale `$HOME`. Will update later today.

**Comment by b-m-f** [comment]
@acequicksilver I cant find the reference you mention.

Updated the relevant part in the book though. 

If this PR lands I will be happy to update `lighthouse-docker`

**Comment by acequicksilver** [comment]
I should have included a link. See below

https://github.com/sigp/lighthouse-docker/blob/master/docker-compose.yml

https://github.com/sigp/lighthouse-docker/blob/master/scripts/start-beacon-node.sh

Thanks

**Comment by b-m-f** [comment]
@acequicksilver Okay, but this is unrelated to this repository. That shoudnt be touched before this change is actually included here I believe.

**Review by AgeManning — APPROVED** [review]
This seems good to me. 

Better practice to use non-root users in docker imo.

**Comment by AgeManning** [comment]
I'll update the docker-compose scripts once this gets merged in also and the image gets uploaded.

Thanks guys!

**Comment by b-m-f** [comment]
@AgeManning is the bors failure related to changes in here?

**Comment by michaelsproul** [comment]
@b-m-f Nah, unfortunately the macOS VMs are a bit flaky and occasionally seem to timeout

bors retry

**Pull request closed without merging**
