### PR TITLE
Built-in documentation text width in Lighthouse book

### PR DESCRIPTION
**Pull request by chong-he**
## Proposed Changes

The current width for this section in Lighthouse book has a horizontal scroll at the bottom of the page, which is not very user friendly:
 
current

This PR proposes to adjust the width only for this chapter, by modifying the files. After tested, it fits nicely on a 20-inch monitor:

20inch

If the monitor is larger, e.g., 24-inch, have some white space in the code block:

24inch

Thanks to @macladson @rickimoore and @jimmygchen for the help.

### CODE REVIEW

**Review by jimmygchen — APPROVED** [review]
LGTM!

**Review by dapplion — APPROVED** [review]

**Comment by realbigsean** [comment]
@Mergifyio queue

**Comment by realbigsean** [comment]
@Mergifyio requeue

**Comment by realbigsean** [comment]
@Mergifyio refresh

**Comment by realbigsean** [comment]
@Mergifyio requeue

**Comment by realbigsean** [comment]
@Mergifyio dequeue

**Comment by realbigsean** [comment]
@Mergifyio queue

**Pull request merged**
