### PR TITLE
[Merged by Bors] - Test failing CI tests due to port conflicts

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

#4127. PR to test port conflicts in CI tests . 

## Proposed Changes

See issue for more details, potential solution could be adding a cache bound by time to the `unused_port` function.

### CODE REVIEW

**Comment by jimmygchen** [comment]
@antondlr this seems to fix the "Address in use" issue on CI - I've ran it 6 times on the self hosted large runner without errors.

**Comment by michaelsproul** [comment]
This looks good to me, but did I see somewhere that there were issues with socket reuse?

**Comment by jimmygchen** [comment]
> This looks good to me, but did I see somewhere that there were issues with socket reuse?

That was probably from me a few days ago, was having issue running it locally, but it seems to work well on CI. I'll need to figure out what's the issue.. could be a MacOS thing

**Review by divagant-martian — APPROVED** [review]
LGTM!

**Pull request closed without merging**
