### PR TITLE
Remove `bors.yaml`

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

#4251

Removing `bors.yaml` as we're moving to `mergify` merge queue.

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Thanks Bors, you were a good bot :v: 

Let's try mergify on this PR :eyes:

**Comment by jimmygchen** [comment]
oh yeah good idea, we keep this PR until mergify is on stable?

**Comment by michaelsproul** [comment]
oh damn aha I forgot about the stable thing :(

**Comment by michaelsproul** [comment]
lets just merge as-is

**Pull request merged**
