### PR TITLE
Prevent reprocessing of expired attestations

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Drop attestations that expire in the work reprocessing queue, rather than attempting to reprocess them. We still reprocess attestations from the queue on-demand when their head block becomes known.

This addresses a problem that I've personally observed at least once with the attestation reprocessing algorithm whereby it re-queues attestations in a loop before eventually dropping them. This can be particularly bad if the block that the attestation is waiting for never shows up, as can happen on low spec hardware once it gets overwhelmed. Dropping the attestations seems like it should give such nodes a better chance of catching up rather than death spiralling.

## Additional Info

We could raise the timeout slightly from 12s, seeing as attestations now only get one (extra) chance to be processed. Perhaps 3 or 4 slots worth of runway would be enough. If messages are delayed much more than that then the node/network likely has other issues and we should prioritise not getting swamped.

### CODE REVIEW

**Comment by michaelsproul** [comment]
Marked WIP because I would like to add some metrics for the lengths of `unknown_block_aggregate_queue` and `unknown_block_attestation_queue`

**Comment by divagant-martian** [comment]
Small note: Unless something has changed and this logic is not used, attestations should be retried only once https://github.com/sigp/lighthouse/blob/28b79084cd75d46df95f1d58af2434c8a42de6b4/beacon_node/network/src/beacon_processor/worker/gossip_methods.rs#L216-L225 
Note the sender channel as an option, so it's probably not being re-queued in a loop but received as duplicate.
On another note, we do some down-scoring of peers based on re-processing failing that we would lose here.
Not against the change, just pointing info that might be relevant :)

**Comment by michaelsproul** [comment]
> Small note: Unless something has changed and this logic is not used, attestations should be retried only once

Oh I hadn't noticed this! Thanks!

Perhaps reprocessing them on timeout isn't so bad then, or we could drop them but try to keep the peer down-scoring 🤔

**Comment by michaelsproul** [comment]
I'm going to close this for now, but may revisit it if we find issues on low-spec hardware.

**Pull request closed without merging**
