### PR TITLE
Uncomment self_hosted_runner after PR Merge #5137

### PR DESCRIPTION
**Pull request by Arvmor**
## Issue Addressed
as PR #5157 is merged, uncommented since the version of lcli is installed on the runners
Which issue # does this PR address?
#4847 & PR #5137
## Proposed Changes

Please list or describe the changes introduced by this PR.
uncommented SELF_HOSTED_RUNNERS
in test-suite.yml
## Additional Info

Please provide any additional information. For example, future considerations
or information useful for reviewers.

### CODE REVIEW

**Comment by antondlr** [comment]
this is not yet ready to be merged, lcli on our runners does not auto-update
I'll put it on the todo and merge this when ready

**Comment by Arvmor** [comment]
@antondlr sure thank you!

**Review by antondlr — APPROVED** [review]
lgtm!

**Comment by Arvmor** [comment]
do i have to change the branch to stable?

**Comment by antondlr** [comment]
> do i have to change the branch to stable?

no, targeting unstable is fine. we're prepping a release now, this will be merged for the next one.

**Comment by michaelsproul** [comment]
@mergifyio queue

**Comment by jimmygchen** [comment]
We need a newer version of `lcli` installed on the runner (electra support) before re-queuing this.

**Comment by realbigsean** [comment]
@mergify queue

**Pull request merged**
