### PR TITLE
[Merged by Bors] - v2.3.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Please list or describe the changes introduced by this PR.

## Additional Info

NA

### CODE REVIEW

**Comment by paulhauner** [comment]
Rebased on `staging` to include #3223 and #3225.

**Comment by paulhauner** [comment]
I rebased earlier to remove #3221 which didn't quite make it into `unstable` on time.

**Review by michaelsproul — APPROVED** [review]
Let's go!

bors r+

**Comment by paulhauner** [comment]
bors retry

**Pull request closed without merging**
