### PR TITLE
[Merged by Bors] - add automated release workflow

### LINKED ISSUE #1674: MacOS binary
I'm trying to run the [Running Bird](https://github.com/sigp/lighthouse/releases/tag/v0.2.12) release for Spadina. It is the first time I try the precompiled binaries.

I tried to execute the binary "x86_64-unknown-linux-gnu: AMD/Intel 64-bit processors (most desktops, laptops, servers)" (both the portable and non-portable versions) and get a "cannot execute binary file" error:

```
Justins-MBP:Downloads justin$ ./lighthouse --help
-bash: ./lighthouse: cannot execute binary file
```

Screenshot 2020-09-27 at 18 14 08

Are the precompiled binaries meant to work for MacOS?

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

Resolves #1674 

## Proposed Changes

- Whenever a tag is pushed with the prefix `v` this workflow is triggered
- creates portable and non-portable binaries for linux x86_64, linux aarch64, macOS
  - an attempt at using github actions caching
- signs each binary using GPG
- auto-generates full changelog based on commit messages since the last release
- creates a **draft** release
- hot new formatting (preview [here](https://github.com/realbigsean/lighthouse/releases/tag/v0.9.23))
- has been taking around 35 minutes

## Additional Info

TODOs:
- Figure out how we should automate dockerhub's version tag. 
  - It'd be quickest just to tag `latest`, but we'd need to make sure the docker workflow completes before this starts
- we do the same cross-compile in the `docker` workflow, we could try to use the same binary
- integrate a similar flow for unstable binaries (`-rc` tag?)
- improve caching, potentially use sccache
- if we start using a self-hosted runner this'll require some re-working

Need to add the following secrets to Github: 

- `GPG_PASSPHRASE`
- ~~`GPG_PUBLIC_KEY`~~ hard-coded this, because it was tough manage as a secret
- `GPG_SIGNING_KEY`

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]
Wow. This is really cool!

Should speed some things up. Will be good to test out next release. I'll look into adding the secrets.

**Comment by michaelsproul** [comment]
I'd like to review this before merging, I'll try to get to it soon

**Comment by realbigsean** [comment]
I think it'd be a good idea to set up environment secrets: https://docs.github.com/en/free-pro-team@latest/actions/reference/environments

If someone tries to access a secret in a new workflow, we could require review before it's run

**Comment by paulhauner** [comment]
> I'd like to review this before merging, I'll try to get to it soon

Since @michaelsproul is on leave, I'll make the call to move forward without his review :)

**Review by paulhauner — APPROVED** [review]
Looks good! I've added the secrets to the `protected` environment. Can't wait to try this out!

bors r+

**Comment by paulhauner** [comment]
bors r-

I'm going to try and batch this

**Pull request closed without merging**
