### PR TITLE
[Merged by Bors] - Cleanup unreachable code in `lcli::generate_bootnode_enr` and some tests

### PR DESCRIPTION
**Pull request by divagant-martian**
## Issue Addressed
n/a Noticed this while working on something else

## Proposed Changes
- leverage the appropriate types to avoid a bunch of `unwrap` and errors

## Additional Info
n/a

### CODE REVIEW

**Comment by divagant-martian** [comment]
@michaelsproul / @pawanjay176 :pray: can I have your review? fairly low hanging :cherries: since age is away

**Review by AgeManning — APPROVED** [review]

**Comment by divagant-martian** [comment]
I'll merge unstable once #4503 gets in

**Pull request closed without merging**
