### PR TITLE
Persist data columns to store

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

This small PR contains some remaining changes from #5196 to persist data columns for blocks that have been made available

Built on top of #6237.

### CODE REVIEW

**Review by realbigsean — APPROVED** [review]
looks pretty straightforward

**Comment by jimmygchen** [comment]
I've rebased this back to `unstable` now the conga line's rebased and all targeting `unstable`.

**Comment by jimmygchen** [comment]
Thanks for the quick review @realbigsean ! 🙏

**Comment by michaelsproul** [comment]
@mergify queue

**Pull request merged**
