### PR TITLE
Fix web3signer test fails on macOS

### PR DESCRIPTION
**Pull request by ackintosh**
## Issue Addressed

https://github.com/sigp/lighthouse/issues/6442

## Proposed Changes

- Created `lighthouse/key_legacy.p12` and using it only for macOS testing. (See https://github.com/sigp/lighthouse/issues/6442#issuecomment-2469252651)
- Changed the validity period of certificates from 36500 to 825. (See https://github.com/sigp/lighthouse/issues/6442#issuecomment-2474979183)
- Removed `-aes256` as it's ignored on exporting. (https://github.com/sigp/lighthouse/commit/3c8258f966548217050712873002b1140c90c1cf)

## Additional Info

The validity period of certificates has changed to 825 days, so it's worth considering how to update the certificates automatically:

- Create a GitHub Actions job to update the certificates periodically, for example, every year.
- Generate the certificates for each test run.

### CODE REVIEW

**Review by dapplion — APPROVED** [review]
nice find!

**Comment by jimmygchen** [comment]
@mergify queue

**Comment by jimmygchen** [comment]
@mergify dequeue

**Comment by jimmygchen** [comment]
@mergify requeue

**Pull request merged**
