### PR TITLE
Remove req_id from CustodyId

### PR DESCRIPTION
**Pull request by ackintosh**
## Issue Addressed

N/A

## Proposed Changes

Removed req_id from CustodyId because it's not used.

### CODE REVIEW

**Review by jxs — APPROVED** [review]
LGTM!

**Review by dapplion — APPROVED** [review]

**Comment by jimmygchen** [comment]
@mergify queue

**Comment by jimmygchen** [comment]
@mergify dequeue

**Comment by jimmygchen** [comment]
@mergify requeue

**Pull request merged**
