### PR TITLE
Brought algorithm in TreeHash macro up to spec

### LINKED ISSUE #272: Fix TreeHash algorithm for containers
## Description

The current TreeHash implementation for structs (containers) does not use merkle_hash as per the [spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md#container-2).

## Present Behaviour

Fields within a container are TreeHashed, concatenated, and hashed.

## Expected Behaviour

Fields within a container should be TreeHashed, added to a list which is then merklized.

## Steps to resolve

Correct the algorithm which is implemented in the TreeHash macro.

### PR DESCRIPTION
**Pull request by mjkeating**
## Issue Addressed

Resolves #272 

## Proposed Changes

Fix algorithm to use merkle_hash for containers

### CODE REVIEW

**Comment by mjkeating** [comment]
Hmm. Perhaps I acted on this to quickly. I just noticed this [SZZ Spec rewrite PR](https://github.com/ethereum/eth2.0-specs/pull/696) from Justin Drake. Looks like things might be changing soon.

**Comment by paulhauner** [comment]
Great, thanks @mjkeating!

Do you think I should still review and merge this one?

**Comment by mjkeating** [comment]
@paulhauner - Yes, although there were will some other changes, this logic doesn't seem to change in the new spec from what I can see.

**Comment by paulhauner** [comment]
LGTM! Thank you!

**Pull request merged**
