### PR TITLE
Delete ancient, unused HTTP docs

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Delete an old `http.md` file from the book which isn't referenced from anywhere.

### CODE REVIEW

**Review by dapplion — APPROVED** [review]

**Comment by chong-he** [comment]
LGTM. 

The content of the file is already covered in: https://lighthouse-book.sigmaprime.io/api-bn.html so it is good to remove this file

**Comment by michaelsproul** [comment]
@mergifyio queue

**Comment by michaelsproul** [comment]
@mergifyio dequeue

**Comment by michaelsproul** [comment]
@mergifyio requeue

**Pull request merged**
