### PR TITLE
Metadata request ordering

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

N/A

## Proposed Changes

Send metadata request only after we establish that we aren't disconnecting a peer for crossing the peer limit. We disconenct a lot of peers for reaching the peer limit and this would save a metadata stream which would probably add up over time.

Not sure if there was a specific reason why we would send the metadata request first.

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]
Yeah. Dont think this was intentional. This code had moved around a bit, this ordering looks right to me

**Review by dapplion — APPROVED** [review]
Seems reasonable to me

**Comment by jimmygchen** [comment]
@mergify queue

**Comment by michaelsproul** [comment]
@mergify queue

**Comment by michaelsproul** [comment]
@mergify queue

**Pull request merged**
