### PR TITLE
[Merged by Bors] - Add Eth Version Header

### LINKED ISSUE #4525: Lighthouse `v4.3.0` doesn't send `Eth-Consensus-Version` header
## Description

The `/eth/v1/validator/blinded_blocks` [endpoint](https://ethereum.github.io/beacon-APIs/#/Validator/produceBlindedBlock) doesn't send the `Eth-Consensus-Version` header in the latest lighthouse release `v4.3.0`.

This breaks compatibility with [clients](https://github.com/attestantio/go-eth2-client/blob/master/http/http.go#L271-L275) that consume this API which errors when it can't find the `Eth-Consensus-Version` header in the response.

## Version

Lighthouse/v4.3.0-dfcb336/x86_64-linux

## Present Behaviour

Lighthouse BN **doesn't** return the `Eth-Consensus-Version` header in the response to API call to `/eth/v1/validator/blinded_blocks` endpoint.

See this screenshot:
Screenshot 2023-07-20 at 20 58 44

```
curl --location 'http://lighthouse-bn-v4.3.0/eth/v1/validator/blinded_blocks/{slot}?randao_reveal=0xc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&skip_randao_verification='
```

## Expected Behaviour

Lighthouse BN should return the `Eth-Consensus-Version` header in the response to API call to `/eth/v1/validator/blinded_blocks` endpoint.

## Steps to resolve

None.

### PR DESCRIPTION
**Pull request by Gua00va**
## Issue Addressed
Closes #4525 

## Proposed Changes
`GET /eth/v1/validator/blinded_blocks` endpoint and `GET /eth/v1/validator/blocks`  now send `Eth-Version` header.

### CODE REVIEW

**Review by jimmygchen — CHANGES_REQUESTED** [review]
Nice and simple! Would you mind merging latest `unstable` into your branch please?

**Review by jimmygchen — APPROVED** [review]

**Comment by jimmygchen** [comment]
Approved, thanks @Gua00va!

**Comment by Romansharar** [comment]
Nice i need eth

**Pull request closed without merging**
