### PR TITLE
remove exit-future

### PR DESCRIPTION
**Pull request by jxs**
## Issue Addressed

the last release [was 4 years ago](https://crates.io/crates/exit-future) and its repo [has been archived](https://github.com/paritytech/exit-future). We already have `async-channel` in the repo, so use it instead

### CODE REVIEW

**Review by AgeManning — APPROVED** [review]

**Comment by AgeManning** [comment]
The tests need to be fixed. Seems the update has removed a field.

**Review by AgeManning — CHANGES_REQUESTED** [review]
The tests need to be corrected for the new version

**Review by AgeManning — APPROVED** [review]

**Comment by AgeManning** [comment]
@mergifyio queue

**Comment by jxs** [comment]
@mergifyio queue

**Pull request merged**
