### PR TITLE
Correct flakey CI tests

### PR DESCRIPTION
**Pull request by AgeManning**
## Issue Addressed

Some subnet service tests were failing occasionally. There were two bugs that I found. 

I've run these tests repeatedly without fail, so at the very least, should make these more stable.

### CODE REVIEW

**Comment by michaelsproul** [comment]
Clippy is failing

**Comment by michaelsproul** [comment]
Does the `test_subscribe_same_subnet_several_slots_apart` test need the same fix as the same_slot test? It is still failing on this branch: https://github.com/sigp/lighthouse/actions/runs/12114467475/job/33771078350?pr=6646

**Review by jimmygchen — APPROVED** [review]
Looks good to me. This should also fix the test @michaelsproul mentioned above.

**Comment by michaelsproul** [comment]
Rebased on `release-v6.0.1` so we can merge there and then back-merge to unstable

**Comment by michaelsproul** [comment]
@mergify queue

**Pull request merged**
