### PR TITLE
Release v6.0.0

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

New MAJOR release v6.0.0 for on-disk tree-states and many more improvements :tada: 

## Additional Info

This is the RC testing branch. It is blocked on:

- #6146
- #6604
- #6600
- https://github.com/sigp/lighthouse/pull/6608
- https://github.com/sigp/lighthouse/pull/6626
- https://github.com/sigp/lighthouse/pull/6628

### CODE REVIEW

**Comment by michaelsproul** [comment]
CI failure is due to `cargo update`:

- https://github.com/sigp/lighthouse/pull/6554

Investigating which dependency is responsible now.

**Comment by michaelsproul** [comment]
Cargo update mystery is resolved. Holding back rust_eth_kzg for now. Doesn't seem to be a major issue.

**Comment by michaelsproul** [comment]
Force pushed from https://github.com/sigp/lighthouse/commit/56fe5aa0eb5b98a614350f7c902ad89cd6147f0a to https://github.com/sigp/lighthouse/commit/4ed13a9a2908ad0f7d5570a0224a44c60b378024 in order to include Pawan's latest blob limits from:

- https://github.com/sigp/lighthouse/pull/6626

I.e. up to commit de4ab550284abafe06579a7ae788e32bca311d1e on that branch.

**Review by AgeManning — APPROVED** [review]
:sunglasses:

**Comment by michaelsproul** [comment]
@mergify queue

**Pull request merged**
