### PR TITLE
Typo in chain_collection.rs inline comments

### PR DESCRIPTION
**Pull request by dapplion**
## Issue Addressed

Typo in chain_collection.rs inline comments

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Thank you!

bors r+

**Comment by michaelsproul** [comment]
Uhh, this PR got merged to `master`, which is no longer in use (or is meant to track `stable`).

I'll try reopening it against `unstable`...

**Comment by michaelsproul** [comment]
bors retry

**Comment by michaelsproul** [comment]
Looks like Bors won't let us merge this, so I'm going to close it. We can revive it in a new PR sometime. Sorry @dapplion

**Comment by dapplion** [comment]
> Looks like Bors won't let us merge this, so I'm going to close it. We can revive it in a new PR sometime. Sorry @dapplion

Should I do PRs against stable or unstable then?

**Comment by michaelsproul** [comment]
> Should I do PRs against stable or unstable then?

@dapplion `unstable` please! :pray: We've updated our CI to enforce this now

**Pull request closed without merging**
