### PR TITLE
[Merged by Bors] - Add warnings for deposits

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Add some warnings to discourage users to user Lighthouse for mainnet.

## Additional Info

NA

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Looks good to me

**Comment by paulhauner** [comment]
Thanks! bors r+

**Comment by paulhauner** [comment]
Sorry @michaelsproul I added an extra `println` to validator creation.

**Pull request closed without merging**
