### PR TITLE
[Merged by Bors] - fix a couple typos in comments in merkle_hasher

### PR DESCRIPTION
**Pull request by gballet**
Found what I believe to be a couple typos in the comments as I was going through the merkleization code.

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Nice one, thank you @gballet

bors r+

**Comment by paulhauner** [comment]
bors retry

**Review by paulhauner — APPROVED** [review]
Bors seems to think that I haven't approved this... I'll try again.

bors r+

**Comment by paulhauner** [comment]
Wow, bors really has it in for this PR. It's failed on a non-deterministic CI failure we're working on fixing at the moment.

Fourth time's the charm :D

bors r+

**Comment by gballet** [comment]
fifth time's the charm maybe?

**Comment by michaelsproul** [comment]
bors retry

**Comment by paulhauner** [comment]
Bors had an error. This is madness!!

bors r+

**Pull request closed without merging**
