### PR TITLE
Lighthouse 246 - Create derive macro for TestRandom

### PR DESCRIPTION
**Pull request by thojest**
## Issue Addressed

#246 - Create derive macro for TestRandom

## Proposed Changes

This pull request replaces manual TestRandom trait implementations on most structs following the same pattern by a procedural macro implementation

## Additional Info

1) I did not replace the TestRandom implementation in all cases, because sometimes the implementation follows a different logic, e.g. `status_flags: Some(<_>::random_for_test(rng))` in
```rust
impl<T: RngCore> TestRandom<T> for Validator {
    fn random_for_test(rng: &mut T) -> Self {
        Self {
            pubkey: <_>::random_for_test(rng),
            withdrawal_credentials: <_>::random_for_test(rng),
            activation_epoch: <_>::random_for_test(rng),
            exit_epoch: <_>::random_for_test(rng),
            withdrawal_epoch: <_>::random_for_test(rng),
            penalized_epoch: <_>::random_for_test(rng),
            status_flags: Some(<_>::random_for_test(rng)),
        }
    }
}
```
However, in most cases the manual implementation was replaced by the macro

2) ssz_derive and test_random_derive now use the same, duplicated function for iterating over struct field names, namely  `get_named_field_idents`. Is this level of code duplication ok, or should we change this?

### CODE REVIEW

**Comment by paulhauner** [comment]
Hey, this looks great!

Unfortunately there is a merge conflict in `beacon_state.rs` -- I added some fields to `BeaconState` which should not be randomly generated so we can't use the macro for `BeaconState` anymore. This is a shame as it's the struct with the most fields. We'll figure out a solution eventually, but for now please leave the manual derive there :)

**Comment by thojest** [comment]
alright, beacon_state.rs should be correct now.

**Comment by paulhauner** [comment]
Sorry! #251 conflicted with this.

Will merge it in after the conflicts are fixed :)

**Comment by thojest** [comment]
fixed :)

**Pull request merged**
