### PR TITLE
[Merged by Bors] - fix typos

### PR DESCRIPTION
**Pull request by GoodDaisy**

### CODE REVIEW

**Review by realbigsean — APPROVED** [review]
Thank you!

**Comment by jimmygchen** [comment]
I've changed the target branch to `unstable`.

**Comment by jimmygchen** [comment]
ah looks like this was built on top of `stable` rather than `unstable`.

@GoodDaisy would you mind making the change from `unstable` instead please?

**Comment by GoodDaisy** [comment]
@jimmygchen I want to change to unstable branch, but I don't know how to change it in this PR. So I have push my unstable branch to my stable branch, that's to say, both the stable and unstable branches are the same in my repo.
Please help me to review again, thank you very much.

**Pull request closed without merging**
