### PR TITLE
[Merged by Bors] - Do not log slot clock error prior to genesis

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

#4654 

## Proposed Changes

Only log error if we're unable to read slot clock after genesis. 

I thought about simply down grading the `error` to a `warn`, but feel like it's still unnecessary noise before genesis, and it would be good to retain error log if we're pass genesis. But I'd be ok with just downgrading the log level, too.

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Looks good to me. Maybe @AgeManning or @paulhauner could double-check

**Review by paulhauner — APPROVED** [review]
LGTM!

**Comment by michaelsproul** [comment]
bors retry

**Comment by michaelsproul** [comment]
bors r-

until we fix the web3signer issue this isn't going to work

**Pull request closed without merging**
