### PR TITLE
Add electra presets to beacon API

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

an extension of https://github.com/sigp/lighthouse/pull/5606

### CODE REVIEW

**Comment by realbigsean** [comment]
`get_extra_fields` needs to be updated with constants (looks like deneb constants are actually missing there)

**Comment by realbigsean** [comment]
> `get_extra_fields` needs to be updated with constants (looks like deneb constants are actually missing there)

Looks like there are a bunch of phase0 and altair constants missing.. not sure if there's a pattern? or these are just spec refactors we've missed?

**Review by pawanjay176 — CHANGES_REQUESTED** [review]
Gnosis and minimal preset chainspec defaults seem to be wrong

**Comment by realbigsean** [comment]
There's no gnosis preset in the spec so I wasn't sure what to add. Forgot it wouldn't have been able to read from the file. I guess I'll drop mainnet preset in there for now? https://github.com/gnosischain/specs

**Comment by realbigsean** [comment]
I raised an issue to track gnosis presets https://github.com/sigp/lighthouse/issues/5638

**Review by pawanjay176 — APPROVED** [review]

**Comment by realbigsean** [comment]
@mergify queue

**Comment by realbigsean** [comment]
@mergify requeue

**Pull request merged**
