### PR TITLE
fetch genesis from remote url

### PR DESCRIPTION
**Pull request by eserilev**
## Issue Addressed

#4564

## Proposed Changes

fetch genesis file from remote url

### CODE REVIEW

**Comment by eserilev** [comment]
@paulhauner i have started working on fetching compressed genesis state files from a remote url. the basic building blocks are here, so if anything looks way off just let me know

still need to add the flag that allows users to provide their own remote url. we also probably want to allow for users to provide remote urls to non snappy compressed genesis files as well

**Comment by eserilev** [comment]
well now that I'm realizing i need to move this completely out of the build and into a section of the code that gets executed at start up. Will make those changes and push it up asap

EDIT:
ive moved the genesis fetching code to a place that probably makes more sense. now I just need to make sure I call it in the right place

next steps:

 - [x]  use clap to add an optional cli command which provides a remote url to download snappy compressed genesis
 - [x]  call `uncompress_state` in a relevant location in the code base. if optional cli command is provided use that remote url instead of the default
 - [ ]  write some useful tests

**Comment by paulhauner** [comment]
Great, thanks! We could actually keep the existing `.zip` files in the repo and then zip-decompress and snappy-compress in the `build.rs`. It's a little ugly but it might make things simpler here and it would also avoid adding the snappy-compressed files to the Git history. I don't have a strong preference either way.

**Comment by eserilev** [comment]
Correct me if i'm wrong, I _think_ we can get away with removing everything from `build.rs`

Heres a quick summary of my changes:

The downloading and decompressing of the genesis state happens in `get_eth2_network_config`. We have an optional flag `genesis-remote-url`. If this flag is included, we'll use the provided remote url to download the genesis file. If the flag is excluded, we'll download from a hardcoded url.

We assume the downloaded file is snappy compressed. We probably dont want to make that assumption if the `genesis-remote-url` flag is provided?

If the `testnet-dir` flag is provided, we will not attempt to download the genesis file, as providing that flag means the user already provided a directory with the relevant files. 

I'm now trying to figure the best way to test these changes. I'll go ahead and manually build the project and run through a few scenarios, but it would also be nice to set up some unit/integration tests. Open to any suggestions regarding testing you might have.

Theres also probably some documentation I need to add in the Lighthouse book for the new flag.

I think these changes will allow us to remove the genesis (zipped + uncompressed) files from the git repo, remove the genesis file related code from `build.rs`, reduce Lighthouse binary size and give users the flexibility to download genesis files from a different url if needed.

**Comment by paulhauner** [comment]
> Correct me if i'm wrong, I think we can get away with removing everything from build.rs

In theory we could definitely do this, however after some thought and discussion internally I think it would be good if we can keep the Mainnet genesis state in the binary. I worry that some high-security setups will need to go to some trouble to whitelist the Github download. The cost of the Mainnet state in the binary seems worth it, IMO. I think we might as well keep Gnosis in there too, that's still considered not a testate.

However, I'd be open moving all other genesis states (Prater, Sepolia, etc) to a URL download!

So:

  - Mainnet and Gnosis get included in the binary.
  - All other networks get downloaded via URL.

Sorry about the additional refactoring here 🙏

**Comment by paulhauner** [comment]
Oh, also @michaelsproul pointed out that it might be "more standard" if we download uncompressed bytes rather than snappy compressed bytes. We'd like to try and get checkpointz to support genesis state downloads; it's more likely to serve uncompressed bytes and it would be cool if we didn't need to refactor to support it if/when it's added.

**Comment by paulhauner** [comment]
Ok, @michaelsproul just had a lengthy discussion about what we're doing here and it's rather complicated.

I need another couple of hours to figure some things out and then I'll come back here with an update. Sorry for the run around.

**Comment by paulhauner** [comment]
It turns out that it was rather complicated to figure out how this would work, so I started roughly implementing it and I think I've ended up with a working version. Sorry to commandeer part of the issue, I just couldn't figure it out without digging into the code myself 🙏 

Over in #4653 I have added the Holesky configs such that we download the genesis state at runtime.

I think there's still room for improvement, specifically in:

- Removing some more genesis states (Prater, Chiado, Sepolia are good candidates).
- Compressing whatever genesis states remain.

#4564 kinda scope-creeped from compressing genesis states to downloading them from URLs and adding the Holesky network. So perhaps we can now consider it scope-uncreeped 😅

**Comment by eserilev** [comment]
@paulhauner yeah that totally makes sense. i was sort of stabbing in the dark a bit with this PR so I'm glad you commandeered. your changes look really nice and id be happy to make some of the additional improvements you mentioned once #4653 is merged. closing this PR

**Pull request closed without merging**
