### PR TITLE
Fix to validator create and restore functions being not complete

### PR DESCRIPTION
**Pull request by louqash**
## Issue Addressed
[validator_definitions.yml is not created when creating validator](https://github.com/sigp/lighthouse/issues/2053)

## Proposed Changes

Now both in `create.rs` and `restore.rs` lighthouse automaticly creates and updates validator definitions file.
Also I've added initialization and updating of slashing protection to validator restoration process.

## Additional Info

To simplify code I've changed `random_password()` function to return just String. Before this function generated random password of type `String` and then parsed it into `PlainText` type. After that the only ways the password was used was to either convert it back to `String` or get bytes. `String` type has `get_bytes()` function and you don't need to convert `String` to `String` therefore `PlainText` was unnecessary.

### CODE REVIEW

**Comment by paulhauner** [comment]
> To simplify code I've changed random_password() function to return just String. Before this function generated random password of type String and then parsed it into PlainText type. After that the only ways the password was used was to either convert it back to String or get bytes. String type has get_bytes() function and you don't need to convert String to String therefore PlainText was unnecessary.

The purpose of the `PlainText` struct is to utilize the [`zeroize`](https://docs.rs/zeroize/1.1.1/zeroize/) crate to ensure that the value of the `String` is zeroed-out on drop, rather than just left in memory and marked as free memory. This defends against memory analysis attacks which attempt to recover secrets from memory that is freed but still set to the old value.

As such, I think we should maintain `random_password` returning a `PlainText`.

**Comment by paulhauner** [comment]
Thanks for the contribution :) It looks like `clippy` is failing, once clippy and the `random_password` comment is addressed I'll come back for a full review.

**Comment by pixsll** [comment]
Regarding `PlainText` you're right, but for those purposes there's `ZeroizeString` struct or [Zeroizing\<Z\>](https://docs.rs/zeroize/1.1.1/zeroize/#zeroizingz-wrapper-for-zeroizing-arbitrary-values-on-drop) wrapper. Using PlainText adds complexity and from what I see, almost every use of `PlainText` is using `as_bytes()` function. This maybe opportuninty to refactor. What do you think?

As for clippy, I'll merge unstable branch, because here I don't have this MR https://github.com/sigp/lighthouse/pull/2036

**Comment by pixsll** [comment]
@paulhauner Can you check it again? :slightly_smiling_face:

**Comment by paulhauner** [comment]
Hi @srokadev, sorry this has lingered for so long. I think it's definitely worth doing, but there are some conflicts now.

If you're still interested in following this up, I'm happy to do another review once those conflicts are resolved. If not, perhaps @pawanjay176 would be interested in taking over? :pray:

**Comment by louqash** [comment]
I'll look into it later today :wink:

**Comment by paulhauner** [comment]
I'm going to close this due to lack of inactivity and failing tests. Feel free to reopen if you'd like!

**Pull request closed without merging**
