### PR TITLE
[Merged by Bors] - Clean capella

### PR DESCRIPTION
**Pull request by divagant-martian**
## Issue Addressed

Cleans up all the remnants of 4844 in capella. This makes sure when 4844 is reviewed there is nothing we are missing because it got included here 

## Proposed Changes

drop a bomb on every 4844 thing 

## Additional Info

Merge process I did (locally) is as follows:
- squash merge to produce one commit
- in new branch off unstable with the squashed commit create a `git revert HEAD` commit
- ~~merge that new branch onto 4844 with `--strategy ours`~~
- compare local 4844 to remote 4844 and make sure the diff is empty
- enjoy

### CODE REVIEW

**Comment by michaelsproul** [comment]
Accidentally closed by deletion of `capella`. Re-opening.

This should re-target unstable though now that capella is merged :tada:

**Comment by pawanjay176** [comment]
The merge strategy for the eip4844 branch is really smart. I learned a thing, thank you!

**Review by paulhauner — APPROVED** [review]
Looks good! This was really easy to review since it's just code removals.

I removed some more *blob stuff* in https://github.com/paulhauner/lighthouse/commit/866314ebfcaff9ed6b0bfc76388a1d33e81b4f2f. Feel free to cherry-pick that or leave it out at your will.

I'm happy for this go into bors whenever. Merging it sooner rather than later is probably going to help avoid conflicts.

I think this is a great improvement to code-quality and it'll help us do a better review on 4844/deneb 🎉

**Pull request closed without merging**
