### PR TITLE
Fix zero port error

### PR DESCRIPTION
**Pull request by ackintosh**
## Issue Addressed

Fixes https://github.com/sigp/lighthouse/issues/5004

## Proposed Changes

Changed the code to assign 0 to `quic_port` if `tcp_port == 0`.

### CODE REVIEW

**Comment by jmcph4** [comment]
Does this regress #4745?

**Comment by michaelsproul** [comment]
@jmcph4 I don't think we ever fully solved port-reuse, but I think this PR might make it slightly worse. We were already using `unused_port::unused_udp4_port` in `beacon_node/src/config.rs` when `use_zero_ports=true`.

**Comment by michaelsproul** [comment]
We also still routinely get crashes on CI due to port reuse

**Comment by jmcph4** [comment]
> We also still routinely get crashes on CI due to port reuse

I was under the impression this had become a primarily Windows issue now though?

> I think this PR might make it slightly worse

I agree -- more `unused_*_port` use will increase the rate of collisions compared to deferring to the kernel.

**Comment by ackintosh** [comment]
@jmcph4 @michaelsproul Thanks for your comments! I understand that we should use `unused_*_port` less to avoid the collisions on CI. I will update to assign 0 to quic_port if `tcp_port == 0`.

**Comment by ackintosh** [comment]
📝 I've filed https://github.com/sigp/lighthouse/pull/5024 to fix the `check-code` failure.

**Review by AgeManning — APPROVED** [review]
Looks good to me. Thanks

**Pull request merged**
