### PR TITLE
[Merged by Bors] - Release v4.5.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions from v4.4.1 to v4.5.0.

## Additional Info

NA

### CODE REVIEW

**Comment by paulhauner** [comment]
I've just force-pushed to include a test fix for #4770.

**Review by jimmygchen — APPROVED** [review]
LGTM! 🚀

**Comment by paulhauner** [comment]
bors retry

**Comment by paulhauner** [comment]
bors retry

**Pull request closed without merging**
