### PR TITLE
Avoid computing rpc_blob_limits multiple times

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

N/A

## Proposed Changes

rpc_blob_limits was being computed repeatedly even though its a constant value. Move it to a LazyLock block to avoid repeated computation.
Found this taking ~10% of cpu when I was playing around with flamegraph

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Nice find!

**Comment by michaelsproul** [comment]
The test failure looks related. It might be because `E: EthSpec` has been fixed to `MainnetEthSpec`? We could one lazy lock per spec if necessary

**Review by dapplion — APPROVED** [review]
nice find! what else showed up in the flamegraph?

**Comment by pawanjay176** [comment]
Moved rpc_tests to run over MainnetEthSpec. I think it made a difference when minimal blob sizes were small. Don't think it makes much of a difference in terms of test speeds now. Not sure if there's any reason to run them over minimal cc @AgeManning for when you are back

**Comment by pawanjay176** [comment]
> Not sure if there's any reason to run them over minimal 
We need it for the simulator tests. Running sim tests over MainnetEthSpec will take 8x longer. Can revisit this if we manage to replace sim tests with assertoor tests. Reverted back to minimal in rpc_tests

**Comment by pawanjay176** [comment]
> what else showed up in the flamegraph?

Mostly signature verification and decompression taking up cpu time. Milhouse uses a lot of stack depth. Both are expected I guess.

**Review by michaelsproul — APPROVED** [review]
Looks good.

**Comment by michaelsproul** [comment]
@mergify queue

**Pull request merged**
