### PR TITLE
Add missing header to `eth/v1/builder/blinded_blocks`

### PR DESCRIPTION
**Pull request by eserilev**
## Issue Addressed

#5405 

## Proposed Changes

Add `Eth-Consensus-Version` header to `/eth/v1/builder/blinded_blocks` request

### CODE REVIEW

**Review by michaelsproul — CHANGES_REQUESTED** [review]
To test this on CI and prevent a regression, could you add something to read the header in the `mock_builder`'s handler?

https://github.com/sigp/lighthouse/blob/2a3c709f8ceec4d47c1934446511660c429fe90a/beacon_node/execution_layer/src/test_utils/mock_builder.rs#L311-L357

Seeing as it is only used in Lighthouse (and `mock-relay`) I think it would be acceptable to _error_ in that handler if the header isn't provided

**Comment by eserilev** [comment]
added the header to the mock builder handle [here](https://github.com/sigp/lighthouse/pull/5407/commits/1877b05e4fbecc9cb5078b9a0dbda24b153deedc)

Since the header isn't optional, this handler should fail in the case that its not provided

**Review by michaelsproul — APPROVED** [review]
lgtm

**Comment by michaelsproul** [comment]
@mergifyio queue

**Comment by michaelsproul** [comment]
@Mergifyio requeue

**Comment by michaelsproul** [comment]
@mergifyio requeue

**Comment by realbigsean** [comment]
@Mergifyio requeue

**Comment by realbigsean** [comment]
@Mergifyio requeue

**Pull request merged**
