### PR TITLE
[Merged by Bors] - Removed all disable_forks

### LINKED ISSUE #2923: Remove `disabled_forks` field
## Description

There's a redundant field on the `BeaconChain` called `disabled_forks` that was once part of our fork-aware networking (https://github.com/sigp/lighthouse/pull/953) but which is no longer used and could be deleted.

https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/beacon_chain/src/beacon_chain.rs#L306-L307

## Steps to resolve

Remove all references to `disabled_forks` so that the code compiles and `git grep disabled_forks` returns no results.

### PR DESCRIPTION
**Pull request by RishiKumarRay**
#2923 

Which issue # does this PR address?
There's a redundant field on the BeaconChain called disabled_forks that was once part of our fork-aware networking (#953) but which is no longer used and could be deleted. so Removed all references to disabled_forks so that the code compiles and git grep disabled_forks returns no results.

## Proposed Changes

Please list or describe the changes introduced by this PR.
Removed all references of disabled_forks

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Looks great, thank you!

**Comment by michaelsproul** [comment]
Will merge this PR after the v2.1.0 release.

**Comment by RishiKumarRay** [comment]
@michaelsproul just wanted to ask , How many days will it take ...to update version?

**Pull request closed without merging**
