### PR TITLE
[Merged by Bors] - Add list of DB migrations to docs

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Add a list of schema version changes to the book.

I hope this will be helpful for users upgrading to v2.5.0, to know that they can downgrade to schema v9 to run v2.3.0/v2.4.0 or to schema v8 to run v2.2.0/v2.1.0.

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
LGTM!

**Comment by michaelsproul** [comment]
Thanks!

bors r+

**Comment by michaelsproul** [comment]
bors retry

**Pull request closed without merging**
