### PR TITLE
enable doppelganger tests for deneb

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

Resolves https://github.com/sigp/lighthouse/issues/4847

## Proposed Changes

- this required changing the eth1 block hash to make sure it still matched the genesis block
- had to update the `new-testnet` command with support for later forks
- also added geth logging in the testnet

### CODE REVIEW

**Comment by realbigsean** [comment]
I think this is failing because `lcli` needs to be re-installed? maybe geth?

**Comment by jimmygchen** [comment]
Could be the lcli, since we don't re-build it when running CI on self-hosted runners:
https://github.com/sigp/lighthouse/blob/c7e5dd1098a145c0d2174dc65bd23faeb5074249/.github/workflows/test-suite.yml#L311-L313

Might have to temporarily turn this off and batch another PR to turn it back on 🙈

**Comment by realbigsean** [comment]
> Might have to temporarily turn this off and batch another PR to turn it back on 🙈

just commented it out here: https://github.com/sigp/lighthouse/pull/5137/commits/05119ad95d5a698a13d31bdcd2f2ad33f2ceb5f6

**Review by dapplion — COMMENTED** [review]
You should call `state.fork_name` or similar assertion at the end to double-check that the state has been advanced to the proper genesis fork.

**Comment by michaelsproul** [comment]
> You should call state.fork_name or similar assertion at the end to double-check that the state has been advanced to the proper genesis fork.

I just pushed this check. Let's merge once CI passes

**Comment by michaelsproul** [comment]
@mergifyio queue

**Review by michaelsproul — APPROVED** [review]

**Pull request merged**
