### PR TITLE
Fix Kurtosis, web3signer and cargo-audit for CI

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Fix the failing Kurtosis jobs on CI, e.g.

https://github.com/sigp/lighthouse/actions/runs/12226785831/job/34102825704?pr=6669

## Proposed Changes

- Kurtosis fix: Remove the `-0` that was being erroneously added to the artifact name reference in the doppelganger script. Something must have changed upstream to break this.
- Web3signer fix: update to Java 21.
- Cargo audit: temporarily ignore vuln for `idna` until upstream patch is available.
- May-as-well: install the latest version of `kurtosis-cli`, rather than pinning `1.3.1`.

### CODE REVIEW

**Review by macladson — APPROVED** [review]
Thank you :pray:

**Comment by jimmygchen** [comment]
There's a breaking change in the new version of Web3Signer - it now requires Java 21 runtime. Created a PR to test the fix:
https://github.com/sigp/lighthouse/pull/6674

**Comment by michaelsproul** [comment]
Just the flaky network tests failing now. I'll try a merge

**Comment by michaelsproul** [comment]
@mergify queue

**Comment by michaelsproul** [comment]
@mergify requeue

**Comment by jimmygchen** [comment]
@mergify requeue

**Pull request merged**
