### PR TITLE
[Merged by Bors] - feat: add chiado

### PR DESCRIPTION
**Pull request by filoozom**
## Issue Addressed

N/A

## Proposed Changes

Adds the Chiado (Gnosis testnet) network to the builtin one.

## Additional Info

It's a fairly trivial change all things considered as the preset already exists, so shouldn't be hard to maintain.

It compiles and seems to work, but I'm sure I missed something?

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Looks good to me, I'm happy to merge.

IMO, the biggest cost here is adding ~0.5mb to our Git history (`genesis.ssz.zip`) and ~3mb to our binary size (`genesis.szz`). The size of the binary will increase by less than 3%, which I think is manageable.

We could implement in-binary compression for the genesis states if we become particularly concerned about binary size.

**Comment by paulhauner** [comment]
Looks like we're failing CI sorry:

```
 ---- tests::hard_coded_nets_work stdout ----
thread 'tests::hard_coded_nets_work' panicked at 'called `Result::unwrap()` on an `Err` value: "YAML configuration incompatible with spec constants for mainnet"', common/eth2_network_config/src/lib.rs:283:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by filoozom** [comment]
I'm sorry, I don't really understand how / why this is happening. I get that the presets aren't compatible (that's by design), but the Gnosis mainnet one uses the same exact ones, and I'm not changing anything specific here.

**Comment by paulhauner** [comment]
> I'm sorry, I don't really understand how / why this is happening. I get that the presets aren't compatible (that's by design), but the Gnosis mainnet one uses the same exact ones, and I'm not changing anything specific here.

No worries, I think I found it. I would have made a code suggestion, but Github wouldn't allow me so I just pushed a commit with the fix: https://github.com/sigp/lighthouse/pull/4530/commits/b35c1dcb71239bb8f074dd0994d6a39191e07133

**Comment by filoozom** [comment]
Hi, are we still waiting for anything regarding this? 🙂

**Comment by paulhauner** [comment]
I've made some changes to get this across the line for our v4.4.0 release (testing has already started!)

Firstly, I had to remove four ENRs because they were causing `Invalid base64 encoding: InvalidPadding`. See https://github.com/sigp/lighthouse/pull/4530/commits/a4f8d44a92ec12c2045bb65939c6fb7943d8feaa.

Secondly, I removed the `genesis.ssz.zip` file so that it can be downloaded via a checkpoint-sync server (as per #4653). Users won't notice anything when doing a checkpoint sync, however if they want to sync from genesis they'll need the `--genesis-state-url` flag. For example:

```bash
lighthouse bn --network chiado --genesis-state-url https://checkpoint.chiado.gnosis.gateway.fm
```

**Review by paulhauner — APPROVED** [review]
bors r+

**Pull request closed without merging**
