### PR TITLE
[Merged by Bors] - v2.1.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump to `v2.1.0`.

## Additional Info

NA

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
:tada:

**Comment by paulhauner** [comment]
bors r-

I'm going to investigate some increase memory usage.

**Comment by paulhauner** [comment]
I noticed increased memory usage on our prod mainnet nodes after updating, from ~2GB up to ~3GB. This increased memory usage was not present on our Prater or Canary nodes during the upgrade. It is also not present on other nodes run by our developers.

We noticed that rebooting those v2.1.0 nodes caused the memory to drop to a level similar to v2.0.1. After some investigation we ruled out some recent changes to gossipsub. We currently believe that a DB [schema migration](https://github.com/sigp/lighthouse/tree/unstable/beacon_node/beacon_chain/src/schema_change) performed a number of state reads and fragmented the heap during startup. We have yet to prove this is the case, since we're yet to reproduce the issue. It likely only occurs when there are several heads on mainnet, a fairly uncommon case.

Whilst it's not *ideal* to have this fragmentation during a schema upgrade, it's an easily-resolved once-off issue. Since we already have several PRs blocked on this much-delayed release, I find that the best strategy is to release this version as-is. I don't imagine a short-lived 150% memory footprint will be critical for our users (especially considering that several months ago Lighthouse used far more than 150%). I still believe that v2.1.0 is an improvement on v2.0.1, even considering the schema issue.

bors r+

**Comment by paulhauner** [comment]
bors r-

Stopping this release so we can sneak in a patch to maintain pre-v1.1.8 Infura (we introduced v1.1.8 in https://github.com/sigp/lighthouse/pull/2893).

**Comment by paulhauner** [comment]
Presently blocked on #2934

**Comment by paulhauner** [comment]
#2934 has merged :tada: 

bors r+

**Pull request closed without merging**
