### PR TITLE
[Merged by Bors] - Custom RPC request management for sync

### PR DESCRIPTION
**Pull request by divagant-martian**
## Proposed Changes
Make `lighthouse_network` generic over request ids, now usable by sync

### CODE REVIEW

**Comment by AgeManning** [comment]
I am getting through this. 

There seems to be a few changes in the sync manager, but looks like its mostly due to the request id segregation and you've split things into their own functions.

Should finish the review soon

**Review by AgeManning — APPROVED** [review]
The changes look good. 

Have you tested this over a syncing node? And watched a live node for errors in doing single block lookups? 

Might be worth checking how this behaves over these cases, make sure nothing was missed.

**Comment by divagant-martian** [comment]
This has been running in fremont for more than a week without problem :+1:

**Pull request closed without merging**
