### PR TITLE
[Merged by Bors] - v3.0.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Bump versions to v3.0.0

## Additional Info

- ~~Blocked on #3439~~
- ~~Blocked on #3459~~
- ~~Blocked on #3463~~
- ~~Blocked on #3462~~
- ~~Requires further testing~~

### CODE REVIEW

**Comment by paulhauner** [comment]
~~I'm going to try adding these tests now: https://github.com/ethereum/consensus-specs/releases/tag/v1.2.0-rc.2~~ Actually, I'll do that here: https://github.com/sigp/lighthouse/pull/3462#issuecomment-1217269038

**Comment by paulhauner** [comment]
I've just rebased this onto `unstable`.

**Comment by paulhauner** [comment]
Once again, rebased on `unstable` :relaxed:

**Comment by paulhauner** [comment]
For those watching, the plan is to test this PR over the weekend and then publish a release Monday (AEST).

**Comment by paulhauner** [comment]
We have had this running over the weekend on Prater and Mainnet on several nodes. I am happy with the amount of testing and I think we're good to review and merge :tada:

**Review by michaelsproul — APPROVED** [review]
Magnifique! :tada: 

I'm excited! :rocket:

**Comment by paulhauner** [comment]
:rocket: :panda_face: :rocket: 

bors r+

**Comment by Sonixier** [comment]
Let's go!

**Comment by michaelsproul** [comment]
spurious CI failure

bors retry

**Comment by michaelsproul** [comment]
bors retry

**Comment by paulhauner** [comment]
Fix for cargo-udeps authored by @michaelsproul has been added in: https://github.com/sigp/lighthouse/pull/3464/commits/6ce9dc72fd7bdd4829fce3468795422e3b6fb041

**Comment by paulhauner** [comment]
Lets just try bors again.

bors r+

**Pull request closed without merging**
