### PR TITLE
Introduce self-hosted runners 

### PR DESCRIPTION
**Pull request by antondlr**
Run the following CI tasks on self-hosted runners: 
- test-suite/release-tests-ubuntu
- test-suite/release-tests-windows
- test-suite/beacon-chain-tests
- test-suite/ef-tests-ubuntu

Some tasks are no longer run inside the workflow ( installation of some dependencies, `rustup update`): 
- the runners come preinstalled with all necessary dependencies
- the images are automatically rebuilt weekly, and the containers are respawned w. updated images after running any task 

Currently there are 2 active runners of each flavour: 
`[windows-1, windows-2, large-1, large-2, small-1, small-2]`

### CODE REVIEW

**Comment by antondlr** [comment]
interesting failure there... I don't have sufficient permissions to manually trigger a re-run

**Comment by paulhauner** [comment]
> interesting failure there... I don't have sufficient permissions to manually trigger a re-run

Re-run triggered!

**Comment by paulhauner** [comment]
I've blocked this on some internal devops changes we need to do (DM me for deets). I should be able to clear those this week 🤞

**Comment by paulhauner** [comment]
> Re-run triggered!

Same weird error 🤔

**Comment by antondlr** [comment]
> > Re-run triggered!
> 
> Same weird error 🤔

oooops... I changed something during / right after submitting this PR, breaking ipv6 tests  
it's fixed now!  
(and of course when these runners are in-use I won't test changes on them but on clones.. so this shouldn't happen again)

**Comment by paulhauner** [comment]
We're waiting on one more senior infosec engineer to get their eyes across this one. ETA one week 🙏

**Comment by paulhauner** [comment]
I've just resolved the merge conflicts. It was fairly straight-forward but I note two things:

- We've moved from ganache to Anvil. Therefore Ganache can probably be removed from the builder images and Anvil can be added.
- Since this PR was made we've moved from Windows LLVM v13 to v15.

If Windows builds start failing we might need to add this snippet to bump LLVM: https://github.com/sigp/lighthouse/blob/0c7eed5e580b0f083042860761809282f2f7362b/.github/workflows/test-suite.yml#L86-L89

**Comment by paulhauner** [comment]
Closed in favour of #4506

**Pull request closed without merging**
