### PR TITLE
Fix incorrect error message in ClientBuilder

### PR DESCRIPTION
**Pull request by ackintosh**
## Proposed Changes

The component that required in the line this PR fixed is RuntimeContext not Logger. 😃

### CODE REVIEW

**Comment by paulhauner** [comment]
Good spotting, thanks! Triggering CI now (I'm sure it will pass)

**Comment by paulhauner** [comment]
Oh I was wrong, it didn't pass! :(

It's just a formatting issue. Could you please run `cargo fmt --all` and commit/push the changes please? :)

**Comment by ackintosh** [comment]
Ahh, sorry for that, I didn't check. 💦 I'll update this PR soon. 💨

**Comment by paulhauner** [comment]
Thank you! I just triggered CI again :)

**Comment by paulhauner** [comment]
Tests passing, yay! Thank you!

**Pull request merged**
