### PR TITLE
Signature scheme update

### PR DESCRIPTION
**Pull request by kirk-baird**
## Issue Addressed

#211 

## Proposed Changes

The signature scheme is update to version v0.5.2 which now uses domains and has verify_multiple as well as compression to and from bytes for signatures and public keys.

## Additional Info

This signature-scheme may need to change again due to the use of a_flag, b_flag and c_flag (Will be confirmed later).

### CODE REVIEW

**Comment by kirk-baird** [comment]
Don't merge this yet!
I am unsure why but the test target/debug/deps/block_producer-f35ddc68a68986c1
Seems to be freezing although it was passsing before and there have been no changes to the code.

**Comment by kirk-baird** [comment]
> Don't merge this yet!
> I am unsure why but the test target/debug/deps/block_producer-f35ddc68a68986c1
> Seems to be freezing although it was passsing before and there have been no changes to the code.

Problem solved. It may have been caused by me updating my system. Fix was to run `cargo clean`

**Comment by paulhauner** [comment]
From a quick glance it doesn't look like we're using `fork_version` when passing the domain. Maybe I'm missing something?

https://github.com/ethereum/eth2.0-specs/blob/v0.3.0/specs/core/0_beacon-chain.md#get_domain

**Comment by kirk-baird** [comment]
> From a quick glance it doesn't look like we're using `fork_version` when passing the domain. Maybe I'm missing something?
> 
> https://github.com/ethereum/eth2.0-specs/blob/v0.3.0/specs/core/0_beacon-chain.md#get_domain

Have a look in types/fork.rs
I implement get_domain and fork_version there

**Comment by kirk-baird** [comment]
I added the fork version for domain in attestation_aggregation.rs.
Also there are TODOs related to #239 for where we need to modify the code further to include the correct fork version and domain.

**Comment by paulhauner** [comment]
Great, thanks. #257 also includes TODOs for correctly generating the domain in validator client services.

**Comment by paulhauner** [comment]
We have a couple of conflicts now, happy to merge once they're resolved :)

**Comment by kirk-baird** [comment]
> We have a couple of conflicts now, happy to merge once they're resolved :)

Done :)

**Pull request merged**
