### PR TITLE
Clap derive

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

Improves ergonomics of handling CLI flags and takes care of tracking config names in different places. This is somewhat helpful in layering config from different sources as well, which is necessary in the following PRs:

- https://github.com/sigp/lighthouse/pull/2808
- https://github.com/sigp/lighthouse/pull/2960

## Proposed Changes

Migrate lighthouse to clap derive

### CODE REVIEW

**Comment by realbigsean** [comment]
The CLI tests are so massive for this! Caught a bunch of issues!

**Comment by realbigsean** [comment]
Script for checking out the `--help` diff between two lighthouse binaries: https://gist.github.com/realbigsean/3b1de807c938348fc0ba5d76709d2a37

**Comment by paulhauner** [comment]
I'm going to drop the `ready-for-review` tags due to conflicts. Sorry about letting this one go stale, we can chat about it sometime :)

**Comment by realbigsean** [comment]
closing, see
-  https://github.com/sigp/lighthouse/issues/5087

**Pull request closed without merging**
