### PR TITLE
614 update block processing tests

### LINKED ISSUE #614: Update block processing tests for v0.9
## Description

In #597 I commented out some of the new block processing tests because they were failing due to the v0.9 update.

## Steps to Resolve

Update the commented out tests (tagged with `FIXME`) in `state_processing/src/per_block_processing/tests.rs`:

https://github.com/sigp/lighthouse/blob/601951ae991cbd17349cff8a5b6539462450ec37/eth2/state_processing/src/per_block_processing/tests.rs#L396-L425

It would be ideal if the updated tests could be made to depend on a minimum number of "magic numbers". Instead we should use spec constants or fields of the state to mutate operations.

You can start on this before v0.9 is merged by checking out the `v0.9` branch.

### PR DESCRIPTION
**Pull request by pscott**
## Issue Addressed

Closes #614 

## Proposed Changes

- Update block processing tests
- Remove use of magic numbers as much as possible

### CODE REVIEW

**Comment by paulhauner** [comment]
Just confirming that this is ready for review?

**Comment by pscott** [comment]
@paulhauner it is!
I noticed
```rust
#![cfg(all(test, not(feature = "fake_crypto")))
``` and wanted to make sure with you that this was indeed the cfg we wanted?

**Comment by paulhauner** [comment]
Please merge in master when you get a chance :)

**Comment by pscott** [comment]
Done!

**Comment by michaelsproul** [comment]
Sorry @pscott, a lot has changed since you opened this PR. One day someone will get around to reviewing your changes and incorporating them into the new spec!

**Comment by paulhauner** [comment]
I'm going to close this fella since the spec and implementation has changed quite significantly since.

Sorry that the changes never made it in @pscott! They didn't become regression tests but they were valuable in actually checking things at the time!

Perhaps we'll come back to this :)

**Pull request closed without merging**
