### PR TITLE
[Merged by Bors] - Remove penalty for attesting to unknown head

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

- Resolves https://github.com/sigp/lighthouse/issues/2902

## Proposed Changes

As documented in https://github.com/sigp/lighthouse/issues/2902, there are some cases where we will score peers very harshly for sending attestations to an unknown head.

This PR removes the penalty when an attestation for an unknown head is received, queued for block look-up, then popped from the queue without the head block being known. This prevents peers from being penalized for an unknown block when that peer was never actually asked for the block.

Peer penalties should still be applied to the peers who *do* get the request for the block and fail to respond with a valid block. As such, peers who send us attestations to non-existent heads should eventually be booted.

## Additional Info

- [ ] Need to confirm that a timeout for a bbroot request will incur a penalty.

### CODE REVIEW

**Review by michaelsproul — CHANGES_REQUESTED** [review]
I don't think we should merge this for the reason described here: https://github.com/sigp/lighthouse/issues/2902#issuecomment-1010504028

**Comment by paulhauner** [comment]
I'll close this so we can work on a different solution.

**Comment by paulhauner** [comment]
I'm bringing this back since we have agreement between myself, @AgeManning and @michaelsproul that this is the best course of action for the time being.

**Review by AgeManning — APPROVED** [review]
As was discussed internally the DOS vector is not particuarly valid. 

An incomming PR will expand on this and add extra penalties

**Pull request closed without merging**
