### PR TITLE
[Merged by Bors] - Update spec tests to v1.1.0-beta.4

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

Bump the spec tests to beta.4, including the new randomised tests (which all pass :tada:)

### CODE REVIEW

**Comment by michaelsproul** [comment]
The only new tests that are omitted currently are the BLS `eth_fast_aggregate_verify`/etc, because we don't have direct implementations of those functions to test. I'm undecided on whether we should write an implementation _just_ so we can test it (I'm leaning towards yes: the more tests the better).

**Comment by michaelsproul** [comment]
This is now ready for review :blush: I ended up adding runners for the new BLS tests.

I'm planning to add the other new BLS tests as part of a separate PR (i.e. the tests from here: https://github.com/ethereum/bls12-381-tests/)

**Review by paulhauner — APPROVED** [review]
LGTM!

**Pull request closed without merging**
