### PR TITLE
[Merged by Bors] - Transition Block Proposer Preparation

### PR DESCRIPTION
**Pull request by ethDreamer**
## Issue Addressed

- #3058

### CODE REVIEW

**Comment by ethDreamer** [comment]
I've tested this commit on a local merge network. The call to `engine_forkchoiceUpdated` occurs 4 seconds before the call to `engine_getPayload` for the transition block:
```
Mar 14 13:22:56.039 2022 REQUEST                                                                                                                                                                                                                                                                                             
{                                                                                                                                                                                                                                                                                                                            
  "jsonrpc": "2.0",                                                                                                                                                                                                                                                                                                          
  "method": "engine_forkchoiceUpdatedV1",                                                                                                                                                                                                                                                                                    
  "params": [                                                                                                                                                                                                                                                                                                                
    {                                                                                                                                                                                                                                                                                                                        
      "finalizedBlockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",                                                                                                                                                                                                                            
      "headBlockHash": "0xd66a428f36526bf00d62f254c676dd33be0b439d1646556b1d9294588a005ce0",                                                                                                                                                                                                                                 
      "safeBlockHash": "0xd66a428f36526bf00d62f254c676dd33be0b439d1646556b1d9294588a005ce0"                                                                                                                                                                                                                                  
    },                                                                                                                                                                                                                                                                                                                       
    {                                                                                                                                                                                                                                                                                                                        
      "prevRandao": "0x5d4de15d796db4e0bce73e72b46c73f4c85015812aa39b8ec94a081f1db8b75a",                                                                                                                                                                                                                                    
      "suggestedFeeRecipient": "0xd8da6bf26964af9d7eed9e03e53415d37aa96045",                                                                                                                                                                                                                                                 
      "timestamp": "0x622f8804"                                                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                                                                        
  ],                                                                                                                                                                                                                                                                                                                         
  "id": 1                                                                                                                                                                                                                                                                                                                    
} 
Mar 14 13:22:56.039 2022 RESPONSE                                                                                                                                                                                                                                                                                            
{                                                                              
  "jsonrpc": "2.0",                                                            
  "id": 1,                                                                     
  "result": {                                                                  
    "payloadStatus": {                                                         
      "status": "VALID",                                                       
      "latestValidHash": "0xd66a428f36526bf00d62f254c676dd33be0b439d1646556b1d9294588a005ce0",                                                                
      "validationError": null                                                  
    },                                                                         
    "payloadId": "0xbd83ff1ad55a3c8e"                                          
  }                                                                            
}
...
Mar 14 13:23:00.022 2022 REQUEST                                               
{                                                                              
  "jsonrpc": "2.0",                                                            
  "method": "engine_getPayloadV1",                                             
  "params": [                                                                  
    "0xbd83ff1ad55a3c8e"                                                       
  ],                                                                           
  "id": 1                                                                      
}                                                                              

Mar 14 13:23:00.022 2022 RESPONSE                                              
{                                                                              
  "jsonrpc": "2.0",                                                            
  "id": 1,                                                                     
  "result": {                                                                  
    "parentHash": "0xd66a428f36526bf00d62f254c676dd33be0b439d1646556b1d9294588a005ce0",                                                                       
    "feeRecipient": "0xd8da6bf26964af9d7eed9e03e53415d37aa96045",                                                                                             
    "stateRoot": "0xfd6717e086c518ac0e03ad0ab6e56797fa44d7dc56698573fff6fb233bd014a0",                                                                        
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",                                                                     
    "logsBloom": "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "prevRandao": "0x5d4de15d796db4e0bce73e72b46c73f4c85015812aa39b8ec94a081f1db8b75a",                                                                       
    "blockNumber": "0x1a",                                                     
    "gasLimit": "0x1be483b",                                                   
    "gasUsed": "0x0",                                                          
    "timestamp": "0x622f8804",                                                 
    "extraData": "0x",                                                         
    "baseFeePerGas": "0x7",                                                    
    "blockHash": "0xc35d9fdc7b7b59af2f80eb3fddda932074a0347bc751e42060043c70612b78dc",                                                                        
    "transactions": []                                                         
  }                                                                            
} 
```

Also the log message did appear:

```
Mar 14 18:22:56.001 INFO Prepared beacon proposer                validator: 89, prepare_slot: 410, already_known: false, service: beacon
Mar 14 18:22:56.023 INFO Found terminal block hash               block_hash: ExecutionBlockHash(0xd66a428f36526bf00d62f254c676dd33be0b439d1646556b1d9294588a005ce0), terminal_total_difficulty: 50, terminal_block_hash_override: ExecutionBlockHash(0x0000000000000000000000000000000000000000000000000000000000000000), service: exec
Mar 14 18:22:56.032 INFO Prepared POS transition block proposer, slot: 410, service: beacon
```

**Review by paulhauner — CHANGES_REQUESTED** [review]
Nice, all this logic here looks good! I made a few suggestions over in [this commit](https://github.com/paulhauner/lighthouse/commit/1505c130cb53c1ea9e6cd5e20969a74dec9b8eb7). They are:

1. Remove an `if is_merge_transition_complete` from `BeaconChain::fork_choice_internal` to ensure this runs from fork choice, not just the proposer prep routine.
1. Add some conditionals to `BeaconChain::prepare_proposer_async` to avoid running if we're earlier than the slot prior to the Bellatrix fork. This is just an optimization for pre-Bellatrix.
1. As above, but for `BeaconChain::update_execution_engine_forkchoice_blocking`.
1. Add a unit test, since I'm quite familiar with the testing frameworks we have for this stuff.

**Comment by ethDreamer** [comment]
@paulhauner great suggestions! I added your commit and modified it slightly to move the post-bellatrix checks **before** these calls to retrieve the execution engine:
```
    let execution_layer = self
        .execution_layer
        .as_ref()
        .ok_or(Error::ExecutionLayerMissing)?;
```
This way, if the user doesn't specify `--execution-engine`, they won't see [these](https://github.com/ethDreamer/lighthouse/blob/transition_block_proposer_prep/beacon_node/beacon_chain/src/beacon_chain.rs#L3692-L3696) critical [messages](https://github.com/ethDreamer/lighthouse/blob/transition_block_proposer_prep/beacon_node/beacon_chain/src/beacon_chain.rs#L3707-L3711) until the `bellatrix` fork epoch.

**Review by paulhauner — APPROVED** [review]
This looks good, sorry it fell off my radar and I forgot to merge it. We have a conflict now, I think it'll be fairly simple to resolve, some new tests were added on `unstable`.

**Review by paulhauner — APPROVED** [review]
Nice one!

bors r+

**Pull request closed without merging**
