### PR TITLE
[Merged by Bors] - Start a release checklist

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Add a checklist to the release draft created by CI. I know @michaelsproul was also working on this and I suspect @realbigsean also might have useful input.

## Additional Info

NA

### CODE REVIEW

**Comment by realbigsean** [comment]
I like the idea! A couple of potential additions: 
- a deploy to sigp testnet nodes? 
- and maybe preparing a Discord announcement
- would love if we could automate a check for compatibility with lighthouse-metrics and lighthouse-docker. For now might be worth at least having a server internally we could quickly `docker-compose pull`  `docker-compose up` on

**Comment by michaelsproul** [comment]
I had some more heavy-weight requirements on my existing list, but I'm not sure if they're worth the time and hassle:

* Start syncing Pyrmont & mainnet nodes from scratch. I think we broke sync/initial start-up in a previous release, and checking these "fresh sync" code paths is a good way to prevent that.
* Update a node running a slasher (we've broken this before). Before we dogfood the slasher I'd like to fix https://github.com/sigp/lighthouse/issues/1890 and https://github.com/sigp/lighthouse/issues/2112, which will make the DB a much more manageable size.

I'd also split the _update testnets_ requirement into:

* Update SigP Pyrmont nodes
* Update SigP canary nodes

**Comment by paulhauner** [comment]
I've incorporated some feedback and I think this is ready to go now. We can always change it later on, it would be nice to get rid of this PR dust :slightly_smiling_face:

**Review by michaelsproul — APPROVED** [review]
LGTM

**Pull request closed without merging**
