### PR TITLE
[Merged by Bors] - Validators endpoint status code

### LINKED ISSUE #2035: validator API endpoint 400 vs 405 status
## Description

Minor API issue (sorry for nitpick), working on testing the whole lighthouse API surface for consistency with spec, and generating test vectors for bindings!

Issue: `/eth/v1/beacon/states/100/validators/morty` returns 405 (unknown route) status instead of 400 (invalid validator ID)

## Version

v1.0.3

## Present Behaviour

405

## Expected Behaviour

400

## Steps to resolve

Change routing logic to match any validator ID format, and only then return a correct error code when parsing in detail.

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

Resolves #2035 

## Proposed Changes

Update 405's to 400's for failures when we are parsing path params.

## Additional Info

Haven't updated the same for non-standard endpoints

### CODE REVIEW

**Review by paulhauner — CHANGES_REQUESTED** [review]
I think a `block_task` is overkill here, this closure is so small we don't need to worry about it blocking the core executor:

```rust
        .and(warp::path::param::<ValidatorId>().or_else(|_| async {
            Err(warp_utils::reject::custom_bad_request(
                "Invalid validator ID".to_string(),
            ))
        }))
```

Let me know your thoughts.

**Comment by realbigsean** [comment]
Yep, makes sense. Updated.

**Review by paulhauner — APPROVED** [review]
Nice!

**Pull request closed without merging**
