### PR TITLE
Fix Sse client api

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

N/A

## Proposed Changes

The `get_events` api in `BeaconNodeHttpClient` uses a regular http get request to stream the events. This doesn't handle a lot of sse params like return of partial bytes, maintaining a heartbeat etc. Using the get_events stream as an api consumer led to the connection getting repeatedly cutoff.
This PR uses reqwest_eventsource to do the sse handling. 

## Additional Info

Using reqwest-eventsource v0.5 to keep the reqwest version same as what we use in lighthouse.

### CODE REVIEW

**Comment by pawanjay176** [comment]
Tests seem to be failing, gonna try and fix it tomorrow

**Review by michaelsproul — APPROVED** [review]
Looks good and the tests are passing, so we're good to go.

**Comment by michaelsproul** [comment]
@mergify queue

**Comment by michaelsproul** [comment]
@mergify requeue

**Comment by michaelsproul** [comment]
@mergify requeue

**Comment by pawanjay176** [comment]
@mergify requeue

**Comment by pawanjay176** [comment]
@mergifyio requeue

**Comment by pawanjay176** [comment]
@mergifyio queue

**Comment by pawanjay176** [comment]
@Mergifyio queue

**Comment by pawanjay176** [comment]
@mergifyio refresh

**Comment by pawanjay176** [comment]
@mergifyio queue

**Pull request merged**
