### PR TITLE
[Merged by Bors] - Clippy 1.49.0 updates and dht persistence test fix

### PR DESCRIPTION
**Pull request by realbigsean**
## Issue Addressed

`test_dht_persistence` failing

## Proposed Changes

Bind `NetworkService::start` to an underscore prefixed variable rather than `_`.  `_` was causing it to be dropped immediately

This was failing 5/100 times before this update, but I haven't been able to get it to fail after updating it

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
Nice one!

bors r+

**Comment by paulhauner** [comment]
bors r-

I just noticed clippy is unhappy.

**Comment by realbigsean** [comment]
I added clippy lints for 1.49.0 here -- was gonna open another PR but forgot which branch I was on :blush:

**Review by paulhauner — APPROVED** [review]
Nice one, clippy fixes are much appreciated!

bors r+

**Comment by paulhauner** [comment]
bors retry

**Comment by michaelsproul** [comment]
Damn, it seems that test is still failing on v1.1.0: https://github.com/sigp/lighthouse/runs/1739536184

**Comment by realbigsean** [comment]
:sob:

**Pull request closed without merging**
