### PR TITLE
[Merged by Bors] - remove withdrawal warning

### PR DESCRIPTION
**Pull request by eserilev**
## Issue Addressed

[#4196](https://github.com/sigp/lighthouse/issues/4196).

## Proposed Changes

Remove withdrawal warning since we are post shapella upgrade

### CODE REVIEW

**Review by michaelsproul — CHANGES_REQUESTED** [review]
This is great, thanks!

The docs are `.md` files in the `book` subdirectory, would you mind updating them too? https://github.com/sigp/lighthouse/tree/stable/book

Thanks!

**Comment by eserilev** [comment]
@michaelsproul thanks! I updated the "withdrawal of exited funds" section in the documentation.

**Review by michaelsproul — APPROVED** [review]

**Comment by amirkhan7javi** [comment]
pending

**Pull request closed without merging**
