### PR TITLE
Fix `lighthouse account validator` subcommands help text

### PR DESCRIPTION
**Pull request by chong-he**
## Issue Addressed

* #6075  

Tested and it's working, though not sure if there is an easier way of doing it

### CODE REVIEW

**Comment by michaelsproul** [comment]
CK and I discussed a simpler approach offline (using `.global(true)`), so putting this on pause until we try it

**Comment by chong-he** [comment]
> CK and I discussed a simpler approach offline (using `.global(true)`), so putting this on pause until we try it

Thank you so much! Brings the diff to only 2 lines, tested and it's working

**Review by michaelsproul — APPROVED** [review]

**Comment by michaelsproul** [comment]
Nice!

**Comment by michaelsproul** [comment]
@mergify queue

**Comment by AgeManning** [comment]
@mergifyio refresh

**Comment by jimmygchen** [comment]
@mergify requeue

**Pull request merged**
