### PR TITLE
Update signed blob sidecar container

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

Update `SignedBlobSidecar` container to latest Deneb spec:

https://github.com/ethereum/consensus-specs/blob/e2e03b16a1038b39f5631c7f044119ee7f6e6f14/specs/deneb/p2p-interface.md#signedblobsidecar

### CODE REVIEW

**Comment by pawanjay176** [comment]
Could you also update the `BlobSidecar` type in this PR?

**Comment by realbigsean** [comment]
@pawanjay176 what needs updating in the `BlobSidecar` type?

**Comment by jimmygchen** [comment]
I've just compared this branch against the spec, looks like all our p2p containers are up to date.

**Comment by pawanjay176** [comment]
Ahh sorry false alarm. The `index` field in `BlobSidecar` is `BlobIndex` which is u64. I thought it was `BlobIdentifier` for some reason.

**Review by pawanjay176 — APPROVED** [review]
Looks good. 
Should we merge this after merging the compilation error fixes in #4075 @divagant-martian @realbigsean ?

**Pull request merged**
