### PR TITLE
[Merged by Bors] - Fix errors from local testnet scripts on MacOS

### PR DESCRIPTION
**Pull request by ackintosh**
## Issue Addressed

Resolves https://github.com/sigp/lighthouse/issues/2763

## Proposed Changes

- Add a workflow which tests that local testnet starts successfully
  - Added `set` option into the scripts in order to fail fast so that we can notice errors during starting local testnet.
- Fix errors on MacOS
  - The redirect `&>>` is supported since bash v4 but the version bundled in macOS(11.6.1) is v3. https://github.com/sigp/lighthouse/pull/2919/commits/a54f119c9b1839fd0909792d219858e727e120a2

### CODE REVIEW

**Comment by ackintosh** [comment]
The error occured in setup.sh.

https://github.com/sigp/lighthouse/runs/4854687564?check_suite_focus=true
> ./setup.sh  >> /Users/runner/.lighthouse/local-testnet/testnet/setup.log 2>&1
> Failed to run lcli: Failed to run deploy-deposit-contract command: Failed to deploy deposit contract: "Failed to deploy contract: Failed to get accounts: Transport(\"failed to send request: error sending request for url (http://localhost:8545/): error trying to connect: tcp connect error: Connection refused (os error 61)\"). Is scripts/ganache_tests_node.sh running?."

This is due to call `lcli deploy-deposit-contract` before ganache-cli has started listening. Also, this could occurs on Linux.

The ideal solution is to wait until the port (http://localhost:8545) is available, but this is a bit of a pain. A simple solution is to extend [the sleep time](https://github.com/sigp/lighthouse/blob/a54f119c9b1839fd0909792d219858e727e120a2/scripts/local_testnet/start_local_testnet.sh#L94).

**Comment by ackintosh** [comment]
This PR is ready for review. 🙆‍♂️

**Review by paulhauner — APPROVED** [review]
This is great, thank you! :pray:

**Comment by michaelsproul** [comment]
A few of the local-testnet CI runs seem to be failing on macOS: https://github.com/sigp/lighthouse/runs/4962371601?check_suite_focus=true

I'm not sure what's causing it yet

**Comment by ackintosh** [comment]
Hmm... I think, to consider from the log below, 

https://github.com/sigp/lighthouse/runs/4962371601?check_suite_focus=true#step:7:52
>  = ============================================================================
> /Users/runner/.lighthouse/local-testnet/testnet/setup.log
> = ============================================================================
> Submitting deposit for validator 69...
> Submitting deposit for validator 70...
> Submitting deposit for validator 71...
> Submitting deposit for validator 72...
> Submitting deposit for validator 73...
> Submitting deposit for validator 74...
> Submitting deposit for validator 75...
> Submitting deposit for validator 76...
> Submitting deposit for validator 77...
> Submitting deposit for validator 78...

https://github.com/sigp/lighthouse/runs/4962371601?check_suite_focus=true#step:7:29
> = ============================================================================
> /Users/runner/.lighthouse/local-testnet/testnet/bootnode.log
> = ============================================================================
> ./bootnode.sh  >> /Users/runner/.lighthouse/local-testnet/testnet/bootnode.log 2>&1
> Generating bootnode enr
> Generated bootnode enr and written to /Users/runner/.lighthouse/local-testnet/testnet/boot_enr.yaml
> Starting bootnode
> Unable to open testnet dir at "/Users/runner/.lighthouse/local-testnet/testnet": Unable to open deploy_block.txt: Os { code: 2, kind: NotFound, message: "No such file or directory" }

https://github.com/sigp/lighthouse/runs/4962371601?check_suite_focus=true#step:7:66
> = ============================================================================
> /Users/runner/.lighthouse/local-testnet/testnet/validator_node_1.log
> = ============================================================================
> ./validator_client.sh /Users/runner/.lighthouse/local-testnet/node_1 http://localhost:8001 info >> /Users/runner/.lighthouse/local-testnet/testnet/validator_node_1.log 2>&1
> Unable to open testnet dir at "/Users/runner/.lighthouse/local-testnet/testnet": Unable to open deploy_block.txt: Os { code: 2, kind: NotFound, message: "No such file or directory" }



this is due to calling [boot_node.sh](https://github.com/sigp/lighthouse/blob/150931950dd2dd531d0643314ae9e3c46503cdf3/scripts/local_testnet/start_local_testnet.sh#L101) , [validator_client.sh](https://github.com/sigp/lighthouse/blob/150931950dd2dd531d0643314ae9e3c46503cdf3/scripts/local_testnet/start_local_testnet.sh#L116) before [setup.sh](https://github.com/sigp/lighthouse/blob/150931950dd2dd531d0643314ae9e3c46503cdf3/scripts/local_testnet/start_local_testnet.sh#L97) has completed. 🤔

**Comment by ackintosh** [comment]
I believe executing [setup.sh](https://github.com/sigp/lighthouse/blob/150931950dd2dd531d0643314ae9e3c46503cdf3/scripts/local_testnet/start_local_testnet.sh#L97) foreground instead of [background](https://github.com/sigp/lighthouse/blob/150931950dd2dd531d0643314ae9e3c46503cdf3/scripts/local_testnet/start_local_testnet.sh#L75) would be a solution. I will file a PR soon.

**Pull request closed without merging**
