### PR TITLE
[Merged by Bors] - Fix bors timeouts

### PR DESCRIPTION
**Pull request by adaszko**
... by moving "license/cla" from `status` to `pr_status` in `bors.toml`.

### CODE REVIEW

**Comment by michaelsproul** [comment]
bors try

Gonna play it safe this time haha

**Comment by michaelsproul** [comment]
ugh

bors r-

**Comment by adaszko** [comment]
bors try

**Comment by adaszko** [comment]
bors try-

**Comment by adaszko** [comment]
bors try

**Comment by adaszko** [comment]
bors try

**Comment by adaszko** [comment]
bors try-
bors try

**Comment by adaszko** [comment]
bors try

**Comment by adaszko** [comment]
bors try-
bors try

**Comment by adaszko** [comment]
bors try-
bors try

**Comment by adaszko** [comment]
bors try

**Comment by adaszko** [comment]
bors try

**Comment by michaelsproul** [comment]
I think _all_ the jobs should be in the pr_status list based on my reading of the RFC (that bors will run once all the checks from pr_status succeed)

**Comment by adaszko** [comment]
> I think all the jobs should be in the pr_status list based on my reading of the RFC (that bors will run once all the checks from pr_status succeed)

From https://bors.tech/rfcs/0388-wait-for-ci-to-finish-instead-of-rejecting-immediately-on-bors-r-when-ci-is-still-pending.html:

> There are two ways to gate on a GitHub Status CI report. The regular status option is used to watch for CI runs on the staging branch. The other, pr_status, is used to watch for integrations that only run on pull requests. Bors will wait for the PR status to complete before it merges into the staging branch.

Since an amalgamation of several pull requests (i.e. a batch in bors terminology) can result in broken tests (this is the very thing bors is built to protect from), I think `status` is the right place for them.

**Comment by adaszko** [comment]
> I meant that to prevent Bors from committing to staging and clogging the queue, the 14 main checks should be in both the pr_status and status lists, but I’m also happy to leave as is

I see.  We can leave GitHub Actions push triggers in place to get a preliminary run of tests on a PR before it gets `r+`'d.

**Pull request closed without merging**
