### PR TITLE
Release v5.2.0

### PR DESCRIPTION
**Pull request by michaelsproul**
## Proposed Changes

New v5.2.0 release.

## Additional Info

Waiting on:

- https://github.com/sigp/lighthouse/pull/5706
- https://github.com/sigp/lighthouse/pull/5768
- https://github.com/sigp/lighthouse/pull/5273
- https://github.com/sigp/lighthouse/pull/5824
- https://github.com/sigp/lighthouse/pull/5845
- https://github.com/sigp/lighthouse/pull/5857
- https://github.com/sigp/lighthouse/pull/5858
- https://github.com/sigp/lighthouse/pull/5863
- https://github.com/sigp/lighthouse/pull/5573
- https://github.com/sigp/lighthouse/pull/5867
- https://github.com/sigp/lighthouse/pull/5876
- https://github.com/sigp/lighthouse/pull/5882
- https://github.com/sigp/lighthouse/pull/5884
- https://github.com/sigp/lighthouse/pull/5006

And further testing.

Closes https://github.com/sigp/lighthouse/issues/5694

### CODE REVIEW

**Comment by realbigsean** [comment]
another to include: https://github.com/sigp/lighthouse/pull/5672

**Comment by realbigsean** [comment]
and this https://github.com/sigp/lighthouse/pull/5675

**Comment by dapplion** [comment]
Note PR
- https://github.com/sigp/lighthouse/pull/5655

Requires the following PR
- https://github.com/sigp/lighthouse/pull/5680

or a fix to fail active requests in the sync network context upon peer disconnection

**Comment by jimmygchen** [comment]
All above PRs mentioned has been included in this branch.

**Comment by michaelsproul** [comment]
FYI for anyone following this PR: we are going to delay this release for a few weeks until after the first Electra devnet. Some bugs were found during testing that need to be fixed, and in parallel we need to keep working on Electra.

**Comment by michaelsproul** [comment]
Rebased on `unstable` and merged in the 3 outstanding PRs that we hope will fix the de-sync issues:

- https://github.com/sigp/lighthouse/pull/5706
- https://github.com/sigp/lighthouse/pull/5722
- https://github.com/sigp/lighthouse/pull/5724

Removed:

- https://github.com/sigp/lighthouse/pull/5696

**Comment by michaelsproul** [comment]
Updated to include this PR which prevents unbounded disk usage!

- https://github.com/sigp/lighthouse/pull/5768

**Comment by michaelsproul** [comment]
Updated to include:

- https://github.com/sigp/lighthouse/pull/5273
- https://github.com/sigp/lighthouse/pull/5824

**Comment by michaelsproul** [comment]
Testing shows this is finally ready to go. I propose we merge it and release tomorrow (Tuesday Aus time)

**Review by jimmygchen — APPROVED** [review]
Let's go 🎉

**Comment by michaelsproul** [comment]
@mergifyio queue

**Pull request merged**
