### PR TITLE
[Merged by Bors] - Resolve RUSTSEC-2020-0146

### LINKED ISSUE #2237: Resolve RUSTSEC-2020-0146
## Description

Our current version of `libp2p` depends transitively on `generic-array 0.12.3` which is vulnerable https://rustsec.org/advisories/RUSTSEC-2020-0146

### PR DESCRIPTION
**Pull request by michaelsproul**
## Issue Addressed

Closes #2237

## Proposed Changes

Bump `generic-array` to patched version `0.12.4`

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
You're not in Rust this week unless you're bumping `generic-array`!

LGTM

**Comment by michaelsproul** [comment]
bors retry

**Comment by michaelsproul** [comment]
looks like cargo udeps is broken by a divergent nightly compiler, I think it might be possible to move udeps off nightly to stable

**Comment by michaelsproul** [comment]
ended up pinning a working version of Nightly Rust instead, we can go back to a floating version in a bit if the pin breaks

**Pull request closed without merging**
