### PR TITLE
[Merged by Bors] - Allow VC to start without any validators

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

- Don't exit early if the VC is without any validators.
- When there are no validators, always create the slashing database (even without `--init-slashing-protection`).

### CODE REVIEW

**Comment by paulhauner** [comment]
When you're back online @michaelsproul (i.e., next week) it would be good to get your input if you agree this is safe for the slashing DB, please :)

**Comment by michaelsproul** [comment]
This was an oversight on my part, and I'm _mostly_ in favour of merging, I'm just a bit hesitant about creating an empty slashing protection DB which users could confuse for their real DB during the v0.3 migration.

A cleaner solution might be to make the slashing protection DB optional in the validator store, initialising it to `None` if 0 validators are provided on start-up, and then creating it via the API if necessary. What do you think?

**Review by michaelsproul — APPROVED** [review]
Having discussed offline, we've decided the `Option` DB is too much of an intrusive change for the purported benefit, so we'll merge as-is and re-assess later :rocket:

**Pull request closed without merging**
