### PR TITLE
[Merged by Bors] - Limit parallelism of head chain sync

### PR DESCRIPTION
**Pull request by AgeManning**
## Description

Currently lighthouse load-balances across peers a single finalized chain. The chain is selected via the most peers. Once synced to the latest finalized epoch Lighthouse creates chains amongst its peers and syncs them all in parallel amongst each peer (grouped by their current head block). 

This is typically fast and relatively efficient under normal operations. However if the chain has not finalized in a long time, the head chains can grow quite long. Peer's head chains will update every slot as new blocks are added to the head. Syncing all head chains in parallel is a bottleneck and highly inefficient in block duplication leads to RPC timeouts when attempting to handle all new heads chains at once. 

This PR limits the parallelism of head syncing chains to 2. We now sync at most two head chains at a time. This allows for the possiblity of sync progressing alongside a peer being slow and holding up one chain via RPC timeouts.

### CODE REVIEW

**Comment by paulhauner** [comment]
Trying to batch this an another PR

bors r-

**Comment by AgeManning** [comment]
Eventually, my friend. You will get merged ahead of all the others....

**Pull request closed without merging**
