### PR TITLE
[Merged by Bors] - Network performance tuning

### PR DESCRIPTION
**Pull request by AgeManning**
There is a pretty significant tradeoff between bandwidth and speed of gossipsub messages. 

We can reduce our bandwidth usage considerably at the cost of minimally delaying gossipsub messages. The impact of delaying messages has not been analyzed thoroughly yet, however this PR in conjunction with some gossipsub updates show considerable bandwidth reduction. 

This PR allows the user to set a CLI value (`network-load`) which is an integer in the range of 1 of 5 depending on their bandwidth appetite. 1 represents the least bandwidth but slowest message recieving and 5 represents the most bandwidth and fastest received message time. 

For low-bandwidth users it is likely to be more efficient to use a lower value. The default is set to 3, which currently represents a reduced bandwidth usage compared to previous version of this PR. The previous lighthouse versions are equivalent to setting the `network-load` CLI to 4.

This PR is awaiting a few gossipsub updates before we can get it into lighthouse.

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
LGTM

**Comment by vyu** [comment]
I noticed that the new `network-load` CLI argument has been hidden from the help command. Is that because this is not recommended for general use, or some other reason? I'm running v2.1.0-rc1 on Prater and unstable on Kintsugi and they seem to recognize `--network-load 5` (log says `bandwidth_config: 5-High`).

**Comment by AgeManning** [comment]
This is not recommended for general use. This was introduced primarily for the development team to do further analysis without having to maintain a fork. It should not be used for mainnet.

**Pull request closed without merging**
