### PR TITLE
Hot-fix v4.0.2-rc.0

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

Avoids clones and state-skips of the head state when an exit is verified across a skip slot.

## Additional Info

NA

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
I've reviewed this

**Comment by TennisBowling** [comment]
with maxperf this reduces spikes from all cores ~70%+ to ~20%+ on a ryzen 9 5950x so might still be hitting hard for pi 4's

**Comment by paulhauner** [comment]
I don't think we should merge this branch into `unstable` since it contains the version bump commits.

Rather, I think we should keep this branch around (i.e., not deleted) so it can be pulled by users and we should make another PR to merge into `unstable`.

**Comment by dom-nie** [comment]
@paulhauner @michaelsproul Will there be a release without the -rc suffix?

**Comment by michaelsproul** [comment]
@dom-nie Yeah, v4.1.0 tomorrow: https://github.com/sigp/lighthouse/pull/4191 (all being well with testing overnight)

**Comment by paulhauner** [comment]
Please expect this branch to be deleted in the near future.

All users should prefer the [latest release](https://github.com/sigp/lighthouse/releases) (v4.1.0 at the time of writing).

**Comment by paulhauner** [comment]
I'm closing this PR but leaving the branch around for the time being.

All users should prefer the [latest release](https://github.com/sigp/lighthouse/releases) (v4.1.0 at the time of writing).

**Pull request closed without merging**
