### PR TITLE
Jenkins setup

### PR DESCRIPTION
**Pull request by spble**
## Proposed Changes

This introduces both a `Jenkinsfile` and a `Dockerfile` which contribute to the build process on Jenkins.

Any branch which contains these files will be detected by Jenkins and perform integration tests.

### CODE REVIEW

**Comment by paulhauner** [comment]
Looks fine to me, I'll have to trust you that it works with Jenkins!

**Comment by spble** [comment]
Ahh, shiz, I don't have all my commits signed.
I will need to go back and do this again I think.

**Comment by paulhauner** [comment]
I can override the commit signing, I've been doing it for external contributors a bit.

We can make that mandatory once we're in production territory. Anyway, signed commits don't give us _that_ much more security, IMO.

**Comment by spble** [comment]
This is ready to land, I have updated it so that the cargo cache is a dedicated, reused, docker volume. This should keep the build time down.

**Comment by paulhauner** [comment]
Thank you!

**Pull request merged**
