### PR TITLE
[Merged by Bors] - Clean `bors.toml`

### PR DESCRIPTION
**Pull request by realbigsean**
unblock https://github.com/sigp/lighthouse/pull/4755

### CODE REVIEW

**Comment by realbigsean** [comment]
bors retry

**Comment by realbigsean** [comment]
bors cancel

**Comment by realbigsean** [comment]
bors retry

**Comment by realbigsean** [comment]
bors retry

**Comment by realbigsean** [comment]
bors retry

**Comment by realbigsean** [comment]
bors retry

**Comment by realbigsean** [comment]
bors retry

**Comment by AgeManning** [comment]
bors retry

**Comment by jimmygchen** [comment]
bors retry

**Pull request closed without merging**
