### PR TITLE
[Merged by Bors] - improve api-bn.md

### PR DESCRIPTION
**Pull request by int88**
## Issue Addressed

NA

## Proposed Changes

improve doc `api-bn.md` to make user convenient to copy and run the command. 

## Additional Info

NA

### CODE REVIEW

**Comment by int88** [comment]
@michaelsproul PTAL :)

**Comment by michaelsproul** [comment]
I'm in two minds about this. On the one hand it's nice to get output through `jq`, but on the other hand it also adds an implicit dependency on `jq`. Some users might not have it installed and might get confused

**Comment by int88** [comment]
> I'm in two minds about this. On the one hand it's nice to get output through `jq`, but on the other hand it also adds an implicit dependency on `jq`. Some users might not have it installed and might get confused

`jq` is used everywhere in `api-lighthouse.md`, just for consistency.

BTW, the output below the command actually is the output after `jq` processing.

**Comment by michaelsproul** [comment]
Oh right, I missed that. Let's merge then

**Pull request closed without merging**
