### PR TITLE
Adds simulator for syncing

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

N/A

## Proposed Changes

Adds a sync simulator for testing syncing under different conditions. 
Also adds a CLI for the existing beacon chain simulation and exposes it as a subcommand to the CLI.

Currently, syncing simulation proceeds as follows with a single syncing node:

- Starts with a single beacon node and validator client.
- Produces blocks for `initial_delay` number of epochs.
- Adds a new beacon node.
- Waits for `sync_delay` number of epochs for new node to sync.

~This is a WIP. Need to add additional syncing strategies.~ Added additional syncing strategies.

### CODE REVIEW

**Comment by mkinney** [comment]
@pawanjay176 Ha! I wish I could take full credit for the macro, but in reality it was copy/pasta. Thanks for incorporating the cli changes.

**Comment by AgeManning** [comment]
Hey, finally got around to having a look at this. 

I dont have push access to your branch, I made a commit, it's in the `syncing-sim` branch. Could you merge that into this PR (it fixes some text and removes a panic). 

Also, I know you asked before, but could we add an extra CLI flag, "strategy" which by default takes "all", and has the options
- one-node
- two-nodes
- mixed (in between)
- all

So that we can optionally run all the sync tests you have. I think in a lot of the future changes, I'll only have to run the `one-node` strat to find bugs. And run the all strat when we have time to do a complete thorough test.

**Comment by AgeManning** [comment]
Looks awesome. We need to merge master in again, sorry. 
Also, I had a quick skim, I didn't see how all gets selected as default. There is a `.default()` you can add to the CLI var that does this, if it's not somewhere else, that i missed.

**Comment by pawanjay176** [comment]
@AgeManning setting the default values here
https://github.com/sigp/lighthouse/blob/5c244af7c4c4a7455a41e482dba3f759d182812d/tests/simulator/src/main.rs#L95-L98

I thought the `value_t` macro was cleaner in parsing the arguments. Can add the default parameter in the cli too though.

**Comment by AgeManning** [comment]
Ah yep cool. Thought i missed it some where.

**Comment by pawanjay176** [comment]
@AgeManning Done!

**Pull request merged**
