### PR TITLE
fix NAT `nat_open` metrics report

### LINKED ISSUE #5384: `nat_open` no longer reports correctly on latest `unstable` (v5.1.0)
## Description

The `nat_open` metric exposed via the `/metrics` endpoint and the `lighthouse/ui/health` endpoint doesn't seem to be reporting the status anymore on latest `unstable`. It seems to be related to the change from #5314.

## Version

`unstable` (v5.1.0 release candidate)

## Present Behaviour

- `nat_open` metric not available on `/metrics`.
- `nat_open` always `false` on `lighthouse/ui/health` even when the node is reachable from external nodes.

## Expected Behaviour

`nat_open` metric should be available and should return `true` if node is reachable.

### PR DESCRIPTION
**Pull request by jxs**
## Issue Addressed

fixes #5384

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]

**Comment by michaelsproul** [comment]
@mergifyio queue

**Comment by jxs** [comment]
@mergifyio refresh

**Comment by jxs** [comment]
@mergifyio queue

**Comment by jimmygchen** [comment]
@mergify requeue

**Comment by jimmygchen** [comment]
@mergifyio refresh

**Comment by jimmygchen** [comment]
@mergify queue

**Comment by jimmygchen** [comment]
@mergifyio requeue

**Pull request merged**
