### PR TITLE
[Merged by Bors] - v2.1.1

### PR DESCRIPTION
**Pull request by paulhauner**
## Issue Addressed

NA

## Proposed Changes

- Bump Lighthouse version to v2.1.1
- Update `thread_local` from v1.1.3 to v1.1.4 to address https://rustsec.org/advisories/RUSTSEC-2022-0006

## Additional Info

- ~~Blocked on #2950~~
- ~~Blocked on #2952~~

### CODE REVIEW

**Comment by paulhauner** [comment]
We have a `cargo audit` failure due to https://rustsec.org/advisories/RUSTSEC-2022-0006

**Comment by paulhauner** [comment]
> We have a `cargo audit` failure due to https://rustsec.org/advisories/RUSTSEC-2022-0006

This is fixed ~~by 29aa650~~ upstream

**Review by michaelsproul — APPROVED** [review]
Ship it! :rocket:

**Pull request closed without merging**
