### PR TITLE
[Merged by Bors] - Downgrade AttestationStateIsFinalized error to debug

### PR DESCRIPTION
**Pull request by eklm**
## Issue Addressed

#2834 

## Proposed Changes

Change log message severity from error to debug in attestation verification when attestation state is finalized.

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Looks good to me, happy to merge once CI passes.

It's a bit strange that this error is reachable at all, because I would have thought `verify_head_block_is_known` should return `false` for finalised blocks. I suspect there's a minor issue with fork choice pruning not being as aggressive as one would naively assume. Either way, that can be a future investigation. This patch definitely addresses the issue in a safe way.

**Comment by michaelsproul** [comment]
Oh, and thank you very much for the contribution! Welcome! :tada:

**Comment by eklm** [comment]
Thanks @michaelsproul, happy to get started:)
Actually it's also strange for me how it passed verify_propagation_slot_range as it checks that attestation slot is not more than slots_per_epoch back from the current slot where state can not be finalized yet in my understanding...

**Comment by michaelsproul** [comment]
> it checks that attestation slot is not more than slots_per_epoch back from the current slot where state can not be finalized yet in my understanding...

This part is explained by a validator lagging a long way behind and making an attestation for an old block. Although the slot of their attestation is recent, the block they select as the head block (which we need to look up) is already finalized

**Comment by eklm** [comment]
> It's a bit strange that this error is reachable at all, because I would have thought verify_head_block_is_known should return false for finalised blocks. I suspect there's a minor issue with fork choice pruning not being as aggressive as one would naively assume. Either way, that can be a future investigation. This patch definitely addresses the issue in a safe way.

https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/consensus/proto_array/src/proto_array.rs#L40-L44

**Comment by paulhauner** [comment]
> I would have thought verify_head_block_is_known should return false for finalised blocks.

I also think this is the case. We check to see if the block descends from the finalized block, regardless of pruning lagging:

https://github.com/sigp/lighthouse/blob/65b1374b587483b11475aa37f0bd2899dd7d4bff/consensus/fork_choice/src/fork_choice.rs#L869-L876

**Comment by michaelsproul** [comment]
Related to this, I've also just noticed that the `WARN Single block lookup failed` messages we log are due to _hitting_ the reject case for finalized blocks. The flow is:

1. Peer attests to an old finalized block just before our finalized checkpoint
2. Block isn't descended from finalized checkpoint so we return `UnknownHeadBlock` here: https://github.com/sigp/lighthouse/blob/65b1374b587483b11475aa37f0bd2899dd7d4bff/beacon_node/beacon_chain/src/attestation_verification.rs#L1006-L1008
3. Sync starts a single block lookup for the block (even though it's one we know): https://github.com/sigp/lighthouse/blob/65b1374b587483b11475aa37f0bd2899dd7d4bff/beacon_node/network/src/beacon_processor/worker/gossip_methods.rs#L1394-L1405
4. Processing the block results in `WouldRevertFinalizedSlot`, a `WARN` and an unfair peer penalty:
```
Jan 09 22:29:00.546 DEBG Searching for block                     block: 0xb995…f4db, peer_id: X, service: sync
Jan 09 22:29:01.150 WARN Single block lookup failed              outcome: Err(WouldRevertFinalizedSlot { block_slot: Slot(2911840), finalized_slot: Slot(2911872) }), service: sync
```

Note that block [`0xb995…f4db`](https://beaconcha.in/block/2911840) is from the canonical chain.

---

I haven't dived deep enough to determine a solution, or whether this could be neatly incorporated with a cleaner fix for the above issue.

**Comment by michaelsproul** [comment]
I think I've worked out how the `AttestationStateIsFinalized` error gets tripped even though we check that the attestation's block root is post-finalization before doing the lookup. It's just a standard race condition. Take aggregate attestations for example:

1. We check whether the `beacon_block_root` is descended from the finalized checkpoint of fork choice, here: https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/beacon_chain/src/attestation_verification.rs#L506 It is, so we keep running.
2. Independently in the beacon chain the finalized checkpoint for fork choice and the store gets updated. The `beacon_block_root` verified in (1) is now _before_ the fork choice's finalized checkpoint _and_ the store's finalized checkpoint.
3. When we call `map_attestation_committee` and miss the cache, it calls `get_inconsistent_state_for_attestation_verification_only` which returns the `AttestationStateIsFinalized`: https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/beacon_chain/src/attestation_verification.rs#L540

I think the patch to just ignore this error is therefore fine. It handles the the concurrency problem in a safe way without locking.

I'm also working on a fix for the `Single block lookup` issue.

**Pull request closed without merging**
