### PR TITLE
[Merged by Bors] - Fix sync committee polling for 0 validators

### PR DESCRIPTION
**Pull request by tthebst**
## Issue Addressed

#2953

## Proposed Changes

Adds empty local validator check. 

## Additional Info

Two other options: 
- add check inside `local_index` collection. Instead of after collection.
- Move `local_index` collection to the beginning of the `poll_sync_committee_duties` function and combine sync committee with altair fork check.

### CODE REVIEW

**Comment by paulhauner** [comment]
This looks good to me, but I'm not so familiar with this part of the code. Perhaps @michaelsproul could give it a glance too? :pray:

**Comment by realbigsean** [comment]
So we do have an equivalent check for attestations here in the `poll_beacon_attesters_for_epoch` method:

https://github.com/sigp/lighthouse/blob/stable/validator_client/src/duties_service.rs#L606

It might be better to include it in `poll_sync_committee_duties` to keep it symmetrical and maybe include a similar debug log.

**Comment by tthebst** [comment]
I think you prefer to have a `local_index` check similar to the one in `poll_beacon_attesters_for_epoch ` but I'm not quite sure if did understand correctly where to place the empty check. 

`duties_service_indices` (checks pubkeys if none are present returns. No logs).
`duties_service_proposers` (checks pubkeys if none are present returns. No logs).
`duties_service_attesters` -> `poll_beacon_attesters_for_epoch` (checks local_indexes logs if empty)
`duties_service_sync_committee` (**my commit** places local_indexes check here and returns if empty) -> `poll_sync_committee_duties_for_period` (not reached if local_indexes empty)

To have it symmetrical there are the following options:
1.  place `local_indexes` check in `duties_service_attesters` instead of `poll_beacon_attesters_for_epoch` and keep my current commit.
2.  move my commit to `poll_sync_committee_duties_for_period`. 
3. (Additionally) Add logs for no pubkeys to `duties_service_indices` and `duties_service_proposers`

Am I correct that you mean option 2? If yes I will move my commit there.

**Comment by realbigsean** [comment]
Yes option 2 was what I was referring to, sorry if it was confusing! 🙂

**Comment by tthebst** [comment]
Thanks for clarifying. I moved the empty check.

**Review by michaelsproul — APPROVED** [review]
Thanks!

**Pull request closed without merging**
