### PR TITLE
[Merged by Bors] - chore: Bellatrix occurred for Gnosis

### PR DESCRIPTION
**Pull request by filoozom**
## Issue Addressed

None

## Proposed Changes

Tiny change to the documentation: Bellatrix happened for Gnosis so also needs a merge-ready config.

## Additional Info

None

### CODE REVIEW

**Comment by michaelsproul** [comment]
ah, can you please re-target this PR at `unstable` and push an empty commit (or rebase on unstable)?

the `target-branch-check` CI will only run again when a new commit is pushed

**Comment by chong-he** [comment]
Thanks for the update

We have also updated the doc here: https://github.com/sigp/lighthouse/pull/4300/files#diff-f35f122b29c362e36834ee6ff8d3f36b2a7e9ca2f7eb611c0a172adf2869e582

**Review by michaelsproul — APPROVED** [review]
In the interests of welcoming contributors, I think we should merge this PR as well as #4300 :blush:

It looks like there are a few minor conflicts in #4300 already, so the conflict with this PR can be fixed up when those are fixed up as well

**Pull request closed without merging**
