### PR TITLE
[Merged by Bors] - Minor documentation fixes

### PR DESCRIPTION
**Pull request by pawanjay176**
## Issue Addressed

N/A

## Proposed Changes

- Fix a wrong command in the validator generation example.
- Replace occurrences of 'passphrase' with 'password'. This is mostly because I felt that there was a lot of mixing of the two phrases in the documentation and the actual commands which is a bit confusing. Picked 'password' everywhere because it felt more appropriate but I don't mind changing it to 'passphrase' as long it's consistent everywhere.

### CODE REVIEW

**Comment by paulhauner** [comment]
Good call, I've found this annoying too. If it's OK, can we sit on this until after Altona launch so I don't need to change tooling before then? :D

**Comment by pawanjay176** [comment]
> Good call, I've found this annoying too. If it's OK, can we sit on this until after Altona launch so I don't need to change tooling before then? :D

Haha of course. Merge at your convenience :)

**Comment by AgeManning** [comment]
Are these changes still relevant? Do want to get these in?

**Comment by pawanjay176** [comment]
I think having a consistent password or passphrase all across the commands is still relevant. Will merge master.

**Review by AgeManning — APPROVED** [review]
LGTM

**Pull request closed without merging**
