### PR TITLE
Merge F2F

### PR DESCRIPTION
**Pull request by paulhauner**
## Overview

**This is the canonical "Merge F2F" branch for interop testing.**

Credits to @ethDreamer for starting this branch.

## Notes to Interop Teams

We're keeping scripts that can run Lighthouse testnets against the EL clients at [sig/lighthouse-merge-f2f](https://github.com/sigp/lighthouse-merge-f2f).

### Building Lighthouse from Source

You'll need to install Rust, we recommend using the standard [`rustup`](https://www.rust-lang.org/tools/install) tool. The commands here will install the binaries to `~/.cargo/bin`, so you'll need to make sure that's on your `PATH`.

Once you have installed Rust, install Lighthouse with:

```bash
git clone git@github.com:sigp/lighthouse.git
cd lighthouse
git checkout merge-f2f
make
```

*Optional: to get the `lcli` binary, run `make install-lcli`.* 

### Lighthouse via Docker

Our CI will update the [`sigp/lighthouse:merge-f2f`](https://hub.docker.com/r/sigp/lighthouse/tags?page=1&ordering=last_updated&name=merge-f2f) branch whenever this PR is updated. Run it with:

```bash
docker run sigp/lighthouse:merge-f2f lighthouse --version
```

Sometimes we use `lcli` (Lighthouse CLI) for creating testnets. You can also find it on Dockerhub at [`sigp/lcli:merge-f2f`](https://hub.docker.com/r/sigp/lcli/tags?page=1&ordering=last_updated&name=merge-f2f).

## Resources

- Consensus Specifications: https://github.com/ethereum/consensus-specs/tree/v1.1.0/specs/merge
- Engine API Subset for the Merge Interop: https://github.com/ethereum/execution-apis/blob/v1.0.0-alpha.2/src/engine/interop/specification.md
- Scripts for starting LH testnets: https://github.com/sigp/lighthouse-merge-f2f

## Ground Rules

*This section contains some ground-rules for developing and using this PR.*

- Avoid pushing changes directly, prefer to create a feature PR on `sigp/lighthouse` (this repo) with `merge-f2f` (this branch) as the target branch.
- When merging changes, do a squash merge via the Github UI (or something that creates the same commit messages).
- PRs being merged here have a lower requirement for quality and review when compared to `unstable`. **This is not production code, we have no user-facing guarantees for stability.**
- Expect this branch to get rebased onto unstable from time to time.

We should also try to extract functionality and merge it to `unstable` from time-to-time to avoid a big nasty merge into `unstable`.

### Before Interop

*All complete*

### During Interop

- [ ] Fix failing `arbitrary` CI check (see [comment](https://github.com/sigp/lighthouse/pull/2620#issuecomment-940641925)).
- [ ] End blocking tasks created by the ExecutionLayer when the shutdown signal is called.
- [ ] Follow up once Clarification on get_pow_block ethereum/consensus-specs#2636 is resolved.
- [ ] Call preparePayload when block producer is known, prior to producing a block
- [ ] Add per-endpoint caches for payload ids
- [ ] Add tests with a terminal block hash override.
- [ ] Add tests for newly added CLI flags.

## Additional Info

This PR contains a new Github Action to push to Dockerhub whenever this branch is updated. We should remove that before merging into `unstable`.

**Do not merge this branch!**

### CODE REVIEW

**Comment by paulhauner** [comment]
I've just rebased this branch on the latest `unstable`, primarily in response to #2579 being merged into `unstable`.

It was a rather hairy rebase, since the commits from #2579 were applied to this branch in non-consecutive commits. I ended up checking out `unstable`, then manually cherry-picking each non-#2579 commit onto this branch. Then, I squashed all those commits into 42f04b0 and then cherry-picked the remaining 3 squash-merge PRs on top of that (#2622, #2626, #2630). 

Ultimately, I think we should end up with the same set of changes we had before. In case anything was lost, I've made a backup of this branch *before* my big rebase here: https://github.com/paulhauner/lighthouse/tree/merge-f2f-backup

**Comment by paulhauner** [comment]
I just force-pushed to rebase onto `unstable` to fix a conflict introduced by #2632 and also to remove an mistake merge (not *squash* merge) commit.

**Comment by paulhauner** [comment]
I just rebased onto `unstable` to fix conflicts in:

- `Cargo.lock`
- `beacon_node/beacon_chain/src/beacon_chain.rs`

**Comment by paulhauner** [comment]
**I have just merged a breaking change into this branch (#2676).**

Previously, Lighthouse was very awkwardly parsing `--terminal-total-difficulty-override` as non-0x-prefixed-hex. So, if you provided `--terminal-total-difficulty-override 16` , you were *actually* providing 22 decimal.

With #2676, we now accept *only* decimal values (no hex, regardless of 0x-prefix). So, from now on `--terminal-total-difficulty-override 16` mean 16 decimal (*not* 22 decimal).

I can't do this in a backwards-compatible way, so any setup using `--terminal-total-difficulty-override` is probably broken. I'm very sorry for this :pray:. We would need to "rip the band-aid off" at some point, and sooner is better than later IMO.

**Comment by paulhauner** [comment]
I've just rebased on `unstable` and force-pushed. There were no notable conflicts.

**Comment by paulhauner** [comment]
In order to get `Arbitrary` tests working it looks like we'll need to do the equivalent of this PR, but for `ethereum_types::Uint256` (and similar types):

https://github.com/paritytech/parity-common/pull/378

**Comment by MariusVanDerWijden** [comment]
I get an `ForkChoiceError(InvalidProtoArrayBytes("Failed to decode ProtoArrayForkChoice: OffsetOutOfBounds(60562903)"))` after updating to the newest version

Edit: ah nvm nuking the db and restarting worked

**Comment by paulhauner** [comment]
> I get an `ForkChoiceError(InvalidProtoArrayBytes("Failed to decode ProtoArrayForkChoice: OffsetOutOfBounds(60562903)"))` after updating to the newest version

This was a breaking DB change documented https://github.com/sigp/lighthouse/pull/2686.

Apologies for the inconvenience. Nuking the DB is indeed the correct solution. It won't happen again after that.

**Comment by paulhauner** [comment]
I have just rebased this branch onto `unstable`. There should be no substantive changes.

**Comment by paulhauner** [comment]
I am closing this branch, but I will leave the `merge-f2f` branch on this repository for the foreseeable future.

This branch will be frozen with the purpose of providing support for the [Pithos testnet](https://pithos-explorer.ethdevops.io/). 

We will not continue to develop atop this branch. Instead, we will be working on #2768 which targets a new series of specifications.

Thanks to everyone who contributed! Your work will live on in #2768 :rocket:

**Pull request closed without merging**
